id:
name: Issue Triage
description: Assign label to issues 
owner:
resource: repository
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bcuda\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bcuda\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:CUDA
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:Java
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bdirect\s*ml\b|\bdml\b)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bdirect\s*ml\b|\bdml\b)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:DML
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bobj(?:ective)?-?c\b|\bnnapi\b|\bmobile\b|\bandroid\b|\bios\b|\bxamarin\b|\bmaui\b)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bobj(?:ective)?-?c\b|\bnnapi\b|\bmobile\b|\bandroid\b|\bios\b|\bxamarin\b|\bmaui\b)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: platform:mobile
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bwindows\b|\bwinrt\b|\bwinml\b)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bwindows\b|\bwinrt\b|\bwinml\b)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: platform:windows
          - if:
              - or:
                  - titleContains:
                      pattern: '/\btransformers(?!\.js)\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\btransformers(?!\.js)\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: model:transformer
onFailure:
onSuccess:
