id:
name: Issue Triage
description: Assign label to issues
owner:
resource: repository
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add api:java label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)\bjava\b
                  isRegex: True
              - bodyContains:
                  pattern: (?i)\bjava\b
                  isRegex: True
        then:
          - addLabel:
              label: api:java
      - description: Add api:javascript label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)\bjavascript\b
                  isRegex: True
              - bodyContains:
                  pattern: (?i)\bjavascript\b
                  isRegex: True
        then:
          - addLabel:
              label: api:javascript
      - description: Add ep:CUDA label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - titleContains:
              pattern: (?i)\bcuda\b
              isRegex: True
        then:
          - addLabel:
              label: ep:CUDA 
      - description: Add ep:DML label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)(\bdirect\s*ml\b|\bdml\b)
                  isRegex: True
              - bodyContains:
                  pattern: (?i)(\bdirect\s*ml\b|\bdml\b)
                  isRegex: True
        then:
          - addLabel:
              label: ep:DML 
      - description: Add ep:TensorRT label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - titleContains:
                  pattern: (?i)(\btensor\s*rt\b|\btrt\b)
                  isRegex: True
        then:
          - addLabel:
              label: ep:TensorRT
      - description: Add platform:jetson label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)(\bjetson\b|\bjetpack\b)
                  isRegex: True
              - bodyContains:
                  pattern: (?i)(\bjetson\b|\bjetpack\b)
                  isRegex: True
        then:
          - addLabel:
              label: platform:jetson
      - description: Add platform:mobile label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)(\bobj(?:ective)?-?c\b|\bnnapi\b|\bmobile\b|\bandroid\b|\bios\b|\bxamarin\b|\bmaui\b)
                  isRegex: True
              - bodyContains:
                  pattern: (?i)(\bobj(?:ective)?-?c\b|\bnnapi\b|\bmobile\b|\bandroid\b|\bios\b|\bxamarin\b|\bmaui\b)
                  isRegex: True
        then:
          - addLabel:
              label: platform:mobile
      - description: Add platform:windows label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - titleContains:
              pattern: (?i)(\bwindows\b|\bwinrt\b|\bwinml\b)
              isRegex: True
        then:
          - addLabel:
              label: platform:windows
      - description: Add model:transformer label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - or:
              - titleContains:
                  pattern: (?i)\btransformers(?!\.js)\b
                  isRegex: True
              - bodyContains:
                  pattern: (?i)\btransformers(?!\.js)\b
                  isRegex: True
        then:
          - addLabel:
              label: model:transformer
      - description: Add quantization label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - titleContains:
              pattern: (?i)(quant|\bqdq\b)
              isRegex: True
        then:
          - addLabel:
              label: quantization
onFailure:
onSuccess:
