id:
name: Issue Triage
description: Assign label to issues
owner:
resource: repository
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add ep:CUDA label to new issues
        if:
          - payloadType: Issues
          - isOpen
          - titleContains:
              pattern: /\bcuda\b/i
              isRegex: True
        then:
          - addLabel:
              label: ep:CUDA 
onFailure:
onSuccess:
