<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" Version="0.14.1" Condition=" '$(UseLocalGenAI)' != 'true' AND ('$(Configuration)' == 'Debug' OR '$(Configuration)' == 'Release') " />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.14.1" Condition=" '$(UseLocalGenAI)' != 'true' AND ('$(Configuration)' == 'Debug_Cuda' OR '$(Configuration)' == 'Release_Cuda') " />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(UseLocalGenAI)' == 'true' ">
    <ProjectReference Include="../../../src/csharp/Microsoft.ML.OnnxRuntimeGenAI.csproj" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.28.0-dev-20260610-0510-50c9510000" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Common/Common.cs" Link="Common/Common.cs" />
  </ItemGroup>

</Project>