// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include "telemetry.h"
#include "device_info.h"
#include "error_scrubber.h"
#include "telemetry_environment.h"
#include "../logging.h"

#if defined(ORTGENAI_ENABLE_TELEMETRY)
#include "Enums.hpp"
#include "ILogConfiguration.hpp"
#include "LogManager.hpp"
#include "LogManagerProvider.hpp"
// Generated by CMake into the build tree. Defines ORTGENAI_TELEMETRY_TENANT_TOKEN only when an override
// was supplied via CMake or environment; keeps the token off the compiler command line.
#include "ortgenai_telemetry_tenant_token.h"
#endif

#include <cstdio>
#include <filesystem>
#include <random>
#include <string>

// Version string defined by the build system
#ifndef ORTGENAI_VERSION
#define ORTGENAI_VERSION "unknown"
#endif

#if defined(ORTGENAI_ENABLE_TELEMETRY) && defined(__ANDROID__)
extern "C" bool OrtGenAIIsAndroidTelemetryReady() noexcept;
#endif

namespace Generators {

namespace {

#if defined(ORTGENAI_ENABLE_TELEMETRY)

// Decode a base64-encoded string at runtime.
std::string DecodeBase64(const std::string& encoded) {
  auto DecodeChar = [](char c) -> int {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
  };

  std::string result;
  result.reserve(encoded.size() * 3 / 4);
  uint32_t accum = 0;
  int bits = 0;
  for (char c : encoded) {
    int val = DecodeChar(c);
    if (val < 0) continue;
    accum = (accum << 6) | static_cast<uint32_t>(val);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      result.push_back(static_cast<char>((accum >> bits) & 0xFF));
    }
  }
  return result;
}

std::string GetToken() {
  static constexpr char kMaskKey[] = "OnnxRuntimeGenAI";
  constexpr size_t klen = sizeof(kMaskKey) - 1;
  std::string decoded = DecodeBase64(
      "LA1WHDYXWhILD1FwUQhyLXdfX0g3RFoRX19Vf1IPcnFiCFcaZUAIEgxAUH5cX2x9eQpYVTNHC0REVVclVFx4fC0LDU9hWFlHXlo=");
  for (size_t i = 0; i < decoded.size(); ++i)
    decoded[i] = static_cast<char>(decoded[i] ^ kMaskKey[i % klen]);
  return decoded;
}

// Generate a random v4 UUID as a hex string (e.g. "f81d4fae-7dec-41d0-8f12-00a0c91e6bf6").
// Used for the process-wide AppSessionGuid (Tier 1 identity).
std::string GenerateGuidV4() {
  // Draw directly from std::random_device rather than seeding a PRNG from one sample.
  std::random_device rd;
  uint64_t hi = (static_cast<uint64_t>(rd()) << 32) | rd();
  uint64_t lo = (static_cast<uint64_t>(rd()) << 32) | rd();
  // Set version (4) and variant (10xx) bits.
  hi = (hi & 0xFFFFFFFFFFFF0FFFULL) | 0x0000000000004000ULL;
  lo = (lo & 0x3FFFFFFFFFFFFFFFULL) | 0x8000000000000000ULL;

  char buf[37];
  std::snprintf(buf, sizeof(buf),
                "%08x-%04x-%04x-%04x-%012llx",
                static_cast<uint32_t>(hi >> 32),
                static_cast<uint32_t>((hi >> 16) & 0xFFFF),
                static_cast<uint32_t>(hi & 0xFFFF),
                static_cast<uint32_t>(lo >> 48),
                static_cast<unsigned long long>(lo & 0xFFFFFFFFFFFFULL));
  return std::string(buf);
}

#endif  // ORTGENAI_ENABLE_TELEMETRY

}  // namespace

#if defined(ORTGENAI_ENABLE_TELEMETRY)

struct GenAiTelemetry::Impl {
  MAT::ILogConfiguration config;  // must outlive log_manager (SDK holds a reference)
  MAT::ILogManager* log_manager{nullptr};
  MAT::ILogger* logger{nullptr};
};

#else

struct GenAiTelemetry::Impl {};

#endif  // ORTGENAI_ENABLE_TELEMETRY

// Guard against access after static destruction
static std::atomic<bool> s_instance_destroyed{false};

GenAiTelemetry& GenAiTelemetry::Instance() {
  static GenAiTelemetry instance;
  return instance;
}

bool GenAiTelemetry::IsDestroyed() {
  return s_instance_destroyed.load();
}

void GenAiTelemetry::Initialize() {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  std::unique_lock<std::mutex> lock(init_mutex_);
  if (initialized_.load()) return;

  // In a CI / build-pipeline environment, or inside onnxruntime-genai's own unit-test binaries,
  // collect nothing: do not initialize the SDK or write any identifier, so not even ProcessInfo is
  // emitted.
  if (TelemetryInternal::IsRunningInCI() || TelemetryInternal::IsRunningUnitTests()) {
    enabled_.store(false);
    return;
  }

  // ORT_TELEMETRY_DISABLED (shared with ONNX Runtime) and ORT_GENAI_TELEMETRY_DISABLED suppress the
  // non-essential lifecycle events. The SDK still initializes outside CI/testing so the one-shot
  // ProcessInfo event can report device counting metadata.
  if (TelemetryInternal::IsTelemetryDisabledByEnvVar()) {
    env_disabled_.store(true);
    enabled_.store(false);
  }

#if defined(__ANDROID__)
  // The Android SDK requires its Java HTTP bridge before native initialization. AAR builds install
  // it automatically; native-only consumers without a Java context safely run without telemetry.
  if (!OrtGenAIIsAndroidTelemetryReady()) {
    const bool should_warn =
        g_log.enabled && g_log.warning && !android_readiness_warning_logged_.exchange(true);
    lock.unlock();
    if (should_warn) {
      try {
        Log("warning", "Android telemetry is waiting for the 1DS Java HttpClient");
      } catch (...) {
        // Diagnostics must not affect host control flow.
      }
    }
    return;
  }
#endif

  // Telemetry must never affect host control flow: any SDK failure here is
  // swallowed and simply leaves telemetry uninitialized (a later call retries).
  // enabled_ is not cleared on failure paths, so a successful retry still emits.
  try {
    // Ingestion token: an official build's override from the generated header
    // (ORTGENAI_TELEMETRY_TENANT_TOKEN) if present, otherwise the encoded in-repo default.
#if defined(ORTGENAI_TELEMETRY_TENANT_TOKEN)
    const std::string ikey = ORTGENAI_TELEMETRY_TENANT_TOKEN;
#else
    const std::string ikey = GetToken();
#endif
    if (ikey.empty()) return;  // no token -> cannot send; stay uninitialized

    impl_ = std::make_unique<Impl>();

    // Configuration is owned by impl_ so it outlives the log manager (the SDK holds a reference to it).
    auto& config = impl_->config;
    config[MAT::CFG_STR_COLLECTOR_URL] = "https://mobile.events.data.microsoft.com/OneCollector/1.0";
    config[MAT::CFG_STR_PRIMARY_TOKEN] = ikey;
    config[MAT::CFG_INT_TRACE_LEVEL_MASK] = 0;
    config[MAT::CFG_INT_SDK_MODE] = MAT::SdkModeTypes::SdkModeTypes_CS;
    config[MAT::CFG_INT_RAM_QUEUE_SIZE] = 512 * 1024;

    // Do not block process teardown to upload: persisted events are sent on the next
    // run. 0 keeps Shutdown non-blocking and avoids adding exit latency to host apps.
    config[MAT::CFG_INT_MAX_TEARDOWN_TIME] = 0;

#if !defined(__ANDROID__)
    const std::string cache_dir = GetTelemetryStorageDir();
    if (!cache_dir.empty()) {
      // Product-specific cache file name: the .onnxruntime directory is shared with ONNX Runtime (and
      // Olive) for the device id, but each product needs its OWN 1DS offline cache so two log managers
      // with different tenant tokens never share one SQLite db (which could mix or misroute events).
      config[MAT::CFG_STR_CACHE_FILE_PATH] = (std::filesystem::path{cache_dir} / "onnxruntime-genai.db").string();
    }
#endif

    // Create a dedicated log manager via LogManagerProvider (recommended over the
    // LOGMANAGER_INSTANCE singleton for library use). wantController=true makes this
    // instance the host (name == host), so Flush/FlushAndTeardown act on it.
    MAT::status_t status = MAT::STATUS_SUCCESS;
    impl_->log_manager =
        MAT::LogManagerProvider::CreateLogManager("OnnxRuntimeGenAI", true, config, status);
    if (status != MAT::STATUS_SUCCESS || impl_->log_manager == nullptr) {
      impl_.reset();
      return;
    }
    impl_->logger = impl_->log_manager->GetLogger(ikey);
    impl_->log_manager->SetTransmitProfile(MAT::TransmitProfile_BestEffort);

    // Process-wide AppSessionGuid stamped on every event as logger context (not a
    // per-event property). An explicit, SDK-independent correlator that answers
    // "which events came from the same process run?" and makes the lightweight
    // per-event sessionId / generatorId counters globally unique.
    if (app_session_guid_.empty()) app_session_guid_ = GenerateGuidV4();
    impl_->logger->SetContext("AppSessionGuid", app_session_guid_);
    impl_->logger->SetContext("LibraryName", "ONNXRuntimeGenAI");
    impl_->logger->SetContext("LibraryVersion", ORTGENAI_VERSION);

    const auto& device = GetDeviceInfo();
    // Desktop builds override the 1DS SDK's device id with a privacy-preserving generated-id hash.
    // Android/iOS leave this empty so the SDK uses its platform device id.
    if (!device.device_id.empty()) {
      impl_->logger->GetSemanticContext()->SetDeviceId(device.device_id);
    }

    initialized_.store(true);
  } catch (...) {
    // Never propagate a telemetry-init failure to the host.
    impl_.reset();
  }
#endif
}

void GenAiTelemetry::Shutdown() {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  std::lock_guard<std::mutex> lock(init_mutex_);
  if (!initialized_.load()) return;

  // Mark uninitialized first so concurrent Log* calls bail in IsEnabled() before
  // teardown begins. Log* and Shutdown must not run concurrently (OgaShutdown API
  // contract); this only narrows the window.
  initialized_.store(false);

  // 1DS-recommended shutdown sequence: Flush() persists in-memory events to disk,
  // FlushAndTeardown() quiesces background activity (PauseActivity/WaitPause), and
  // LogManagerProvider::Release() disposes the instance. Wrapped so a teardown
  // failure can never propagate (Shutdown runs from ~GenAiTelemetry and the
  // extern-C OgaShutdown, where an escaping exception would call std::terminate).
  try {
    if (impl_ && impl_->log_manager) {
      impl_->log_manager->Flush();
      impl_->log_manager->FlushAndTeardown();
      MAT::LogManagerProvider::Release(impl_->config);
      impl_->log_manager = nullptr;
      impl_->logger = nullptr;
    }
  } catch (...) {
  }
  impl_.reset();
#endif
}
GenAiTelemetry::~GenAiTelemetry() {
  s_instance_destroyed.store(true);
  Shutdown();
}

bool GenAiTelemetry::IsEnabled() const {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  return enabled_.load() && initialized_.load();
#else
  return false;
#endif
}

void GenAiTelemetry::SetEnabled(bool enabled) {
  enabled_.store(enabled && !env_disabled_.load());
}

uint32_t GenAiTelemetry::AllocateSessionId() {
  return next_session_id_.fetch_add(1);
}

#if defined(ORTGENAI_ENABLE_TELEMETRY)
std::unique_lock<std::mutex> GenAiTelemetry::LockForLogging(bool require_enabled) {
  std::unique_lock<std::mutex> lock(init_mutex_);
  if ((require_enabled && !enabled_.load()) || !initialized_.load() || !impl_ || !impl_->logger)
    return {};  // empty (unlocked) -> caller bails
  return lock;  // locked; ownership moves to caller
}

#endif

void GenAiTelemetry::LogProcessInfo() {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  bool emitted = false;
  bool warn_device_id_fallback = false;
  // require_enabled=false: ProcessInfo emits whenever telemetry is initialized (outside CI/testing),
  // even when ORT_GENAI_TELEMETRY_DISABLED or SetEnabled(false) has disabled detailed lifecycle events.
  RunLocked([&] {
    // Only log once per process, and only mark it logged while telemetry is live.
    bool expected = false;
    if (!process_info_logged_.compare_exchange_strong(expected, true)) {
      emitted = true;
      return;
    }

    const auto& device = GetDeviceInfo();
    warn_device_id_fallback = device.device_id_status == "Failed";

    MAT::EventProperties event("OnnxRuntimeGenAI.ProcessInfo");
    // sessionId 0 = process scope (model sessions are numbered from 1); ProcessInfo
    // correlates with model/generate events via the AppSessionGuid logger context.
    event.SetProperty("sessionId", static_cast<int64_t>(0));
    event.SetProperty("libraryVersion", ORTGENAI_VERSION);
    // Device id is sent as ext.device.localId by the SDK (desktop override in Initialize, platform id
    // on Android/iOS), so it is not duplicated as a custom property here.
    event.SetProperty("osArchitecture", device.os_architecture);
    event.SetProperty("processorCount", static_cast<int64_t>(device.processor_count));
    event.SetProperty("totalMemoryMB", static_cast<int64_t>(device.total_memory_mb));
    event.SetProperty("cpuModel", device.cpu_model);
    event.SetProperty("processName", device.process_name);
    event.SetProperty("deviceIdStatus", device.device_id_status);

    impl_->logger->LogEvent(event);
    emitted = true;
  },
            /*require_enabled=*/false);
  if (warn_device_id_fallback && g_log.enabled && g_log.warning) {
    try {
      Log("warning", "Failed to persist telemetry device ID; using an in-memory identifier");
    } catch (...) {
      // Diagnostics must not affect host control flow.
    }
  }
  // Allow a retry if telemetry was not live (or threw before emitting).
  if (!emitted) process_info_logged_.store(false);
#endif
}

void GenAiTelemetry::LogModelLoadStart(uint32_t session_id) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.ModelLoadStart");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogModelLoad(uint32_t session_id, const ModelLoadInfo& info) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.ModelLoad");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("modelType", info.model_type);
    event.SetProperty("modelFamily", info.model_family);
    event.SetProperty("modality", info.modality);
    event.SetProperty("attentionType", info.attention_type);
    event.SetProperty("transcriptionMode", info.transcription_mode);
    event.SetProperty("executionProviders", info.execution_providers);
    event.SetProperty("selectedDevice", info.selected_device);
    event.SetProperty("vocabSize", static_cast<int64_t>(info.vocab_size));
    event.SetProperty("contextLength", static_cast<int64_t>(info.context_length));
    event.SetProperty("numHiddenLayers", static_cast<int64_t>(info.num_hidden_layers));
    event.SetProperty("hiddenSize", static_cast<int64_t>(info.hidden_size));
    event.SetProperty("numAttentionHeads", static_cast<int64_t>(info.num_attention_heads));
    event.SetProperty("numKeyValueHeads", static_cast<int64_t>(info.num_key_value_heads));
    event.SetProperty("intraOpNumThreads", static_cast<int64_t>(info.intra_op_num_threads));
    event.SetProperty("graphOptimizationLevel", static_cast<int64_t>(info.graph_optimization_level));
    event.SetProperty("gpuMemoryMB", static_cast<int64_t>(info.gpu_memory_mb));
    event.SetProperty("isInMemory", info.is_in_memory);

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogModelLoadEnd(uint32_t session_id, bool is_success,
                                     double load_time_ms,
                                     const std::string& error_message) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.ModelLoadEnd");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("isSuccess", is_success);
    event.SetProperty("loadTimeMs", load_time_ms);
    if (!error_message.empty()) {
      // Scrub filesystem paths (privacy), then cap length (size guard).
      auto scrubbed = TelemetryInternal::TruncateUtf8AtBoundary(
          TelemetryInternal::ScrubErrorMessage(error_message), 256);
      event.SetProperty("errorMessage", scrubbed);
    }

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogGeneratorCreate(uint32_t session_id, uint32_t generator_id,
                                        int batch_size, int num_beams, int max_length,
                                        int top_k, float top_p, float temperature,
                                        bool do_sample, bool use_graph_capture, bool has_guidance) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.GeneratorCreate");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("generatorId", static_cast<int64_t>(generator_id));
    event.SetProperty("batchSize", static_cast<int64_t>(batch_size));
    event.SetProperty("numBeams", static_cast<int64_t>(num_beams));
    event.SetProperty("maxLength", static_cast<int64_t>(max_length));
    event.SetProperty("topK", static_cast<int64_t>(top_k));
    event.SetProperty("topP", static_cast<double>(top_p));
    event.SetProperty("temperature", static_cast<double>(temperature));
    event.SetProperty("doSample", do_sample);
    event.SetProperty("useGraphCapture", use_graph_capture);
    event.SetProperty("hasGuidance", has_guidance);

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogGenerateStart(uint32_t session_id, uint32_t generator_id,
                                      int prompt_tokens, const std::string& input_modality) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.GenerateStart");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("generatorId", static_cast<int64_t>(generator_id));
    event.SetProperty("promptTokens", static_cast<int64_t>(prompt_tokens));
    event.SetProperty("inputModality", input_modality);

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogGenerateEnd(uint32_t session_id, uint32_t generator_id,
                                    int total_tokens,
                                    double time_to_first_token_ms, double total_time_ms,
                                    double tokens_per_second) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.GenerateEnd");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("generatorId", static_cast<int64_t>(generator_id));
    event.SetProperty("totalTokens", static_cast<int64_t>(total_tokens));
    event.SetProperty("timeToFirstTokenMs", time_to_first_token_ms);
    event.SetProperty("totalTimeMs", total_time_ms);
    event.SetProperty("tokensPerSecond", tokens_per_second);

    impl_->logger->LogEvent(event);
  },
            // Complete a GenerateStart/GenerateEnd pair even if runtime telemetry was disabled
            // while generation was in flight. Callers suppress end events for requests not started.
            /*require_enabled=*/false);
#endif
}

void GenAiTelemetry::LogAdapterActivated(uint32_t session_id, uint32_t generator_id) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.AdapterActivated");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("generatorId", static_cast<int64_t>(generator_id));

    impl_->logger->LogEvent(event);
  });
#endif
}

void GenAiTelemetry::LogRuntimeError(uint32_t session_id,
                                     const std::string& error_type,
                                     const std::string& error_message,
                                     const std::string& context) {
#if defined(ORTGENAI_ENABLE_TELEMETRY)
  RunLocked([&] {
    MAT::EventProperties event("OnnxRuntimeGenAI.RuntimeError");
    event.SetProperty("sessionId", static_cast<int64_t>(session_id));
    event.SetProperty("errorType", error_type);
    // Scrub filesystem paths (privacy), then cap length (size guard).
    auto scrubbed = TelemetryInternal::TruncateUtf8AtBoundary(
        TelemetryInternal::ScrubErrorMessage(error_message), 256);
    event.SetProperty("errorMessage", scrubbed);
    event.SetProperty("context", context);

    impl_->logger->LogEvent(event);
  });
#endif
}

}  // namespace Generators
