parameters:
- name: arch
  type: string
- name: ep
  type: string
- name: ort_version
  type: string
- name: cuda_version
  type: string
jobs:
- job: Windows_CAPI_Packaging_${{ parameters.arch }}_${{ parameters.ep }}
  pool: 'onnxruntime-Win-CPU-2022'
  timeoutInMinutes: 180
  variables:
  - name: artifactName
    value : 'onnxruntime-genai-capi-win-${{ parameters.ep }}-${{ parameters.arch }}'
  - name: ort_filename
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: 'onnxruntime-win-${{ parameters.arch }}-${{ parameters.ort_version }}'
    ${{ else}}:
      ${{if eq(parameters.cuda_version, '11.8') }}:
        value: 'onnxruntime-win-${{ parameters.arch }}-gpu-${{ parameters.ort_version }}'
      ${{ else }}:
        value: 'onnxruntime-win-${{ parameters.arch }}-cuda12-${{ parameters.ort_version }}'
  workspace:
    clean: all
  steps:
  - template: steps/win-build-step.yml
    parameters:
      arch: ${{ parameters.arch }}
      cuda_version: ${{ parameters.cuda_version }}
      ep: ${{ parameters.ep }}
      ort_filename: $(ort_filename)
      ort_version: ${{ parameters.ort_version }}
      target: 'onnxruntime-genai'

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse
    displayName: 'List all files in the repo for ${{ parameters.arch }} ${{ parameters.ep }}'

  - task: CopyFiles@2
    displayName: 'Copy Onnxruntime C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\ort\lib'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactName)\lib'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\build\release\${{ parameters.ep }}_default\Release'
      Contents: |
        onnxruntime-genai.dll
        onnxruntime-genai.lib
        onnxruntime-genai.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactName)\lib'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API header to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\src'
      Contents: |
        ort_genai_c.h
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactName)\include'

  - task: CopyFiles@2
    displayName: 'Copy other files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        VERSION_INFO
        LICENSE
        SECURITY.md
        README.md
        ThirdPartyNotices.txt
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactName)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\$(artifactName)'
      includeRootFolder: true
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)\$(artifactName).zip'
      replaceExistingArchive: true

  - task: DeleteFiles@1
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)\$(artifactName)'
      Contents: '*'
      RemoveSourceFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai capi'
    inputs:
      ArtifactName: $(artifactName)

  - template: steps/compliant-and-cleanup-step.yml

