parameters:
- name: arch
  type: string
- name: ep
  type: string
- name: ort_version
  type: string
- name: cuda_version
  type: string
jobs:
- job: Windows_CAPI_Packaging_${{ parameters.arch }}_${{ parameters.ep }}
  pool: 'onnxruntime-Win-CPU-2022'
  variables:
  - name: artifactName
    value: onnxruntime-genai-capi-win-${{ parameters.ep }}-${{ parameters.arch }}
  - name: build_dir
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: 'build\release\cpu_default'
    ${{ if eq(parameters.ep, 'gpu') }}:
      value: 'build\release\cuda_default'
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - template: steps/capi-win-build-step.yml
    parameters:
      arch: ${{ parameters.arch }}
      ort_version: ${{ parameters.ort_version }}
      ep: ${{ parameters.ep }}
      cuda_version: ${{ parameters.cuda_version }}

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse
    displayName: 'List all files in the repo for ${{ parameters.arch }} ${{ parameters.ep }}'

  - task: CopyFiles@2
    displayName: 'Copy Onnxruntime C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\ort\lib'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\lib'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\$(build_dir)\Release'
      Contents: |
        onnxruntime-genai.dll
        onnxruntime-genai.lib
        onnxruntime-genai.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)\lib'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API header to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\src'
      Contents: |
        ort_genai_c.h
      TargetFolder: '$(Build.ArtifactStagingDirectory)\include'

  - task: CopyFiles@2
    displayName: 'Copy other files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        VERSION_INFO
        LICENSE
        SECURITY.md
        README.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai capi'
    inputs:
      ArtifactName: $(artifactName)

  - template: steps/compliant-and-cleanup-step.yml

