parameters:
  ort_version: '1.17.0'
  cuda_version: '11.8'
  ep: 'cpu'
  arch: 'x64'
jobs:
- job: Windows_CAPI_Packaging_${{ parameters.arch }}_${{ parameters.ep }}
  pool: 'onnxruntime-Win-CPU-2022'
  variables:
  - name: build_config
    value: 'RelWithDebInfo'
  - name: build_dir
    ${{ if eq(parameters.arch, 'x64') }}:
      value: 'win-x64'
    ${{ if eq(parameters.arch, 'arm64') }}:
      value: 'win-arm64'
  - name: arch
    value: ${{ parameters.arch }}
  - name: ep
    value: ${{ parameters.ep }}
  - name: artifactName
    value: onnxruntime-genai-capi-win-${{ parameters.arch }}-${{ parameters.arch }}
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - template: steps/capi-win-build-step.yml
    parameters:
      arch: $(arch)
      ort_version: ${{ parameters.ort_version }}
      ep: $(ep)
      build_config: $(build_config)
      build_dir: $(build_dir)
      cuda_version: ${{ parameters.cuda_version }}

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse

  - task: CopyFiles@2
    displayName: 'Copy Onnxruntime C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\ort\lib'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\lib'

  - task: CopyFiles@2
    displayName: 'Copy Onnxruntime C API header files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\ort\include'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\include'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API library files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\$(build_dir)\$(build_config)'
      Contents: |
        '*genai.dll'
        '*genai.lib'
        '*genai.pdb'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\lib'

  - task: CopyFiles@2
    displayName: 'Copy GenAi C API header to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\src'
      Contents: |
        ort_genai_c.h
      TargetFolder: '$(Build.ArtifactStagingDirectory)\include'

  - task: CopyFiles@2
    displayName: 'Copy other files to ArtifactStagingDirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        VERSION_INFO
        LICENSE
        SECURITY.md
        README.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai python wheel'
    inputs:
      ArtifactName: $(artifactName)

  - template: steps/compliant-and-cleanup-step.yml

