parameters:
- name: build_config
  type: string
- name: ort_version
  type: string

jobs:
- job: macos_ios_cocoapods_packaging
  pool:
    vmImage: 'macOS-latest'
  variables:
    buildSettingsFile: "tools/ci_build/github/apple/default_full_apple_framework_build_settings.json"

  workspace:
    clean: all
  steps:
    - checkout: self
      clean: true
      submodules: none

    - template: steps/utils/set-genai-version.yml
    - template: steps/utils/set-cmake-build-type.yml
      parameters:
        build_config: ${{parameters.build_config}}


    - task: CmdLine@2
      displayName: Build MacOS & iOS CocoaPods Packages
      inputs:
        script: |
          set -e -x
          python tools/ci_build/github/apple/build_and_assemble_apple_pods.py \
            --build-dir "$(Build.BinariesDirectory)/apple_framework" \
            --staging-dir "$(Build.BinariesDirectory)/staging" \
            --pod-version "$(genai_version)" \
            --test \
            --variant Full \
            --build-settings-file "${{ variables.buildSettingsFile }}" \
            --build-apple-framework-args==--config=$(cmake_build_type) \
            --ort-version ${{parameters.ort_version}}
