parameters:
- name: arch
  type: string
- name: ep
  type: string
- name: ort_version
  type: string
- name: cuda_version
  type: string
jobs:
- job: Windows_Nuget_Packaging_${{ parameters.arch }}_${{ parameters.ep }}
  pool: 'onnxruntime-Win-CPU-2022'
  variables:
  - name: artifactName
    value: onnxruntime-genai-nuget-win-${{ parameters.ep }}-${{ parameters.arch }}
  - name: build_dir
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: 'build/release/cpu_default'
    ${{ if eq(parameters.ep, 'gpu') }}:
      value: 'build/release/cuda_default'
  - name: id
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: Microsoft.ML.OnnxRuntimeGenAI
    ${{ if eq(parameters.ep, 'gpu') }}:
      value: Microsoft.ML.OnnxRuntimeGenAI.Gpu
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - template: steps/win-build-step.yml
    parameters:
      arch: ${{ parameters.arch }}
      ort_version: ${{ parameters.ort_version }}
      ep: ${{ parameters.ep }}
      cuda_version: ${{ parameters.cuda_version }}
  - template: steps/nuget-win-packaging-step.yml
    parameters:
      id: $(id)
      build_dir: $(build_dir)
      artifactName: $(artifactName)
      version: '0.1.0-rc1'

  - template: steps/compliant-and-cleanup-step.yml

