parameters:
- name: ep
  type: string

jobs:
- job: nuget_${{ parameters.ep }}_packaging
  variables:
  - name: genai_nuget_ext
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: ''
    ${{ if eq(parameters.ep, 'cuda') }}:
      value: '.Cuda'
    ${{ if eq(parameters.ep, 'directml') }}:
      value: '.DirectML'
  - name: ort_nuget_ext
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: ''
    ${{ if eq(parameters.ep, 'cuda') }}:
      value: '.Gpu'
    ${{ if eq(parameters.ep, 'directml') }}:
      value: '.DirectML'
  steps:
  - powershell: |
      dotnet build Microsoft.ML.OnnxRuntimeGenAI.csproj -p:Configuration="$(buildConfig)" -p:NativeBuildOutputDir="$(buildDir)\$(buildConfig)"
      displayName: 'Build CSharp'
      workingDirectory: '$(Build.Repository.LocalPath)\src\csharp'

  - task: BinSkim@4
    displayName: 'Run BinSkim'
    inputs:
      AnalyzeTargetGlob: '$(Build.Repository.LocalPath)\src\csharp\**\*.dll'
      continueOnError: true

  - template: steps/compliant/win-esrp-dll-step.yml
    parameters:
      FolderPath: '$(Build.Repository.LocalPath)\src\csharp\bin\$(buildConfig)\'
      DisplayName: 'ESRP - Sign C# dlls'
      Pattern: '*OnnxRuntimeGenAI*.dll'

  - powershell: |
      $VERSION = '0.4.0-dev'
      $nugetPath = Join-Path "C:\Program Files" "NuGet\nuget.exe"
      & $nugetPath pack Microsoft.ML.OnnxRuntimeGenAI.nuspec `
        -Prop version=$VERSION `
        -Prop genai_nuget_ext=$(genai_nuget_ext) `
        -Prop configuration=$(buildConfig) `
        -Prop buildPath=$(buildDir) `
        -Prop ort_nuget_ext=$(ort_nuget_ext) `
        -Prop ort_version=$(ort_version)
      & $nugetPath pack Microsoft.ML.OnnxRuntimeGenAI.Managed.nuspec `
        -Prop version=$VERSION `
        -Prop configuration=$(buildConfig)
      displayName: 'Nuget Packaging'
      workingDirectory: '$(Build.Repository.LocalPath)\nuget'

  - powershell: |
      Get-ChildItem -Path $(Build.Repository.LocalPath) -Recurse
      displayName: 'List all files in the repo for'

  - task: CopyFiles@2
    displayName: 'Copy Nuget to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\nuget'
      Contents: '*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\nuget'

  - template: steps/compliant/esrp_nuget.yml
    parameters:
      DisplayName: 'ESRP - sign NuGet package'
      FolderPath: '$(Build.ArtifactStagingDirectory)\nuget'
      DoEsrp: 'true'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai NuGet'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\nuget'
      ArtifactName: $(artifactName)-nuget