parameters:
  ort_version: '1.17.1'
  cuda_version: '11.8'
  build_x64_cpu: true
  build_gpu: true
  build_arm64_cpu: false
jobs:
- job: Windows_Wheels
  strategy:
    matrix:
      x64_cpu:
        arch: 'x64'
        ep: cpu
        build_dir: win-x64
        artifactName: onnxruntime-genai-nuget-win-cpu-x64
        id: Microsoft.ML.OnnxRuntimeGenAI
      ${{ if eq(parameters.build_arm64, true) }}:
        arm64_cpu:
          arch: 'arm64'
          ep: cpu
          build_dir: win-arm64
          artifactName: onnxruntime-genai-nuget-win-cpu-arm64
          id: Microsoft.ML.OnnxRuntimeGenAI
      ${{ if eq(parameters.build_gpu, true) }}:
        x64_gpu:
          arch: 'x64'
          ep: gpu
          build_dir: win-x64
          artifactName: onnxruntime-genai-nuget-win-gpu-x64
          id: Microsoft.ML.OnnxRuntimeGenAI.Gpu
  pool: 'onnxruntime-Win-CPU-2022'
  variables:
    build_config: 'RelWithDebInfo'
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - template: steps/capi-win-build-step.yml
    parameters:
      arch: $(arch)
      ort_version: ${{ parameters.ort_version }}
      ep: $(ep)
      build_config: $(build_config)
      cuda_version: ${{ parameters.cuda_version }}

  - bash:
      dotnet build Microsoft.ML.OnnxRuntimeGenAI.csproj -p:Configuration="$(build_config)" -p:NativeBuildOutputDir="$(build_dir)\$(build_config)"
    displayName: 'Build CSharp'
    workingDirectory: '$(Build.SourcesDirectory)\src\csharp'

  - powershell: |
      $VERSION = Get-Content $(Build.SourcesDirectory)\VERSION_INFO
      nuget.exe pack Microsoft.ML.OnnxRuntimeGenAI.nuspec `
        -Prop version=$VERSION `
        -Prop id=$(id)
      nuget.exe pack Microsoft.ML.OnnxRuntimeGenAI.Managed.nuspec `
        -Prop version=$VERSION
    displayName: 'Nuget Packaging'
    workingDirectory: '$(Build.SourcesDirectory)\nuget'

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse
  - task: CopyFiles@2
    displayName: 'Copy Nuget to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\nuget'
      Contents: '*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai python wheel'
    inputs:
      ArtifactName: $(artifactName)

  - template: steps/compliant-and-cleanup-step.yml

