parameters:
- name: arch
  type: string
- name: ep
  type: string
- name: ort_version
  type: string
- name: cuda_version
  type: string
  default: ''

jobs:
- job: Linux_Nuget_Packaging_${{ parameters.ep }}_${{ parameters.arch }}
  pool: 'onnxruntime-Ubuntu2204-AMD-CPU'
  timeoutInMinutes: 180
  variables:
  - name: artifactName
    value: 'onnxruntime-genai-capi-linux-${{ parameters.ep }}-${{ parameters.arch }}'
  - name: ort_version
    value: ${{ parameters.ort_version }}
  - name: arch
    value: ${{ parameters.arch }}
  - name: ep
    value: ${{ parameters.ep }}
  - name: buildDir
    value: ''$(Build.SourcesDirectory)/onnxruntime-genai/build/gcc_${{ parameters.ep }}'
  - name: ort_filename
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: 'onnxruntime-linux-${{ parameters.arch }}-${{ parameters.ort_version }}'
    ${{ else}}:
      ${{if eq(parameters.cuda_version, '11.8') }}:
        value: 'onnxruntime-linux-${{ parameters.arch }}-gpu-${{ parameters.ort_version }}'
      ${{ else }}:
        value: 'onnxruntime-linux-${{ parameters.arch }}-cuda12-${{ parameters.ort_version }}'
  workspace:
    clean: all
  steps:
  - template: steps/capi-linux-step.yml
    parameters:
      target: 'onnxruntime-genai'
      genai_src: '$(Build.SourcesDirectory)/onnxruntime-genai'

# TODO: Add a step to build the nuget package

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai capi'
    inputs:
      ArtifactName: $(artifactName)

  - template: steps/compliant-and-cleanup-step.yml

