parameters:
- name: cuda_version
  type: string
  default: '11.8'
  values:
  - 11.8
  - 12.2
- name: ort_version
  type: string
  default: '1.17.1'
jobs:
- job: Linux_GPU_Wheels
  timeoutInMinutes: 240
  workspace:
    clean: all
  pool: onnxruntime-Ubuntu2204-AMD-CPU
  variables:
  # The build machine pool doesn't have dotnet, so it can't run CG.
  - name: skipComponentGovernanceDetection
    value: true
  - name: ort_version
    value: '1.17.1'

  steps:
  - template: steps/linux-build-step.yml
    parameters:
      arch: ${{ parameters.arch }}
      ort_version: ${{ parameters.ort_version }}
      ep: ${{ parameters.ep }}
      cuda_version: ${{ parameters.cuda_version }}

  - script: |
      set -e -x
      az login --identity --username 63b63039-6328-442f-954b-5a64d124e5b4
      az acr login --name onnxruntimebuildcache  --subscription 00c06639-6ee4-454e-8058-8d8b1703bd87
      python3 tools/ci_build/get_docker_image.py --dockerfile tools/ci_build/github/linux/docker/manylinux//Dockerfile.manylinux2_28_cuda \
        --context tools/ci_build/github/linux/docker/manylinux \
        --docker-build-args "--build-arg BUILD_UID=$( id -u )" \
        --container-registry onnxruntimebuildcache \
        --manylinux-src $(Build.SourcesDirectory)/manylinux \
        --multiple_repos \
        --repository onnxruntimegpubuild
    displayName: 'Get Docker Image'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'

  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src \
      -w /onnxruntime_src/ onnxruntimegpubuild \
        bash -c " \
          /usr/bin/cmake --preset linux_gcc_cuda_release \
          -DENABLE_TESTS=OFF \
          -DMANYLINUX=ON \
          -DCMAKE_CUDA_ARCHITECTURES=\"60;61;70;75;80;86\" \
          -DPYTHON_EXECUTABLE=/opt/python/cp38-cp38/bin/python3.8 && \
          /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel 3.8'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'

  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src \
      -w /onnxruntime_src/ onnxruntimegpubuild \
        bash -c " \
          /usr/bin/cmake --preset linux_gcc_cuda_release \
          -DENABLE_TESTS=OFF \
          -DMANYLINUX=ON -DCMAKE_CUDA_ARCHITECTURES=\"60;61;70;75;80;86\" \
          -DPYTHON_EXECUTABLE=/opt/python/cp39-cp39/bin/python3.9 && \
          /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel 3.9'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'
  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src \
      -w /onnxruntime_src/ onnxruntimegpubuild \
        bash -c " \
          /usr/bin/cmake --preset linux_gcc_cuda_release \
          -DENABLE_TESTS=OFF \
          -DMANYLINUX=ON -DCMAKE_CUDA_ARCHITECTURES=\"60;61;70;75;80;86\" \
          -DPYTHON_EXECUTABLE=/opt/python/cp310-cp310/bin/python3.10 && \
          /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel 3.10'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'
  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src \
      -w /onnxruntime_src/ onnxruntimegpubuild \
        bash -c " \
          /usr/bin/cmake --preset linux_gcc_cuda_release \
          -DENABLE_TESTS=OFF \
          -DMANYLINUX=ON -DCMAKE_CUDA_ARCHITECTURES=\"60;61;70;75;80;86\" \
          -DPYTHON_EXECUTABLE=/opt/python/cp311-cp311/bin/python3.11 && \
          /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel 3.11'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'
  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src \
      -w /onnxruntime_src/ onnxruntimegpubuild \
        bash -c " \
          /usr/bin/cmake --preset linux_gcc_cuda_release \
          -DENABLE_TESTS=OFF \
          -DMANYLINUX=ON -DCMAKE_CUDA_ARCHITECTURES=\"60;61;70;75;80;86\" \
          -DPYTHON_EXECUTABLE=/opt/python/cp312-cp312/bin/python3.12 && \
          /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel 3.12'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'

  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/onnxruntime-genai/build/gcc_cuda/release/wheel'
      Contents: '*manylinux*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime python wheel'
    inputs:
      ArtifactName: onnxruntime-genai-linux-gpu

  - template: steps/component-governance-component-detection-step.yml
    parameters:
      condition: 'succeeded'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
