parameters:
- name: cuda_version
  type: string
  default: '11.8'
  values:
  - 11.8
  - 12.2
jobs:
- job: Linux_GPU_Wheels
  timeoutInMinutes: 240
  workspace:
    clean: all
  pool: onnxruntime-Ubuntu2204-AMD-CPU
  variables:
  # The build machine pool doesn't have dotnet, so it can't run CG.
  - name: skipComponentGovernanceDetection
    value: true
  - ort_version: '1.17.0'

  steps:
  - checkout: self # due to checkout multiple repos, the root directory is $(Build.SourcesDirectory)/onnxruntime-genai,
    clean: true
    submodules: recursive

  - checkout: manylinux # due to checkout multiple repos, the root directory is $(Build.SourcesDirectory)/manylinux,
    submodules: false

  - template: steps/set-nightly-build-option-variable-step.yml

  #  - bash: |
  #      pip3 install -r requirements.txt
  #      python3 download_onnxruntime.py --ort_version 1.17.0 --os linux --is_gpu True --arch x64
  #    displayName: Download OnnxRuntime
  #    workingDirectory: $(Build.SourcesDirectory)/onnxruntime-genai/scripts

  - task: DownloadGitHubRelease@0
    inputs:
      connection: 'GitHub - Release'
      userRepository: 'microsoft/onnxruntime'
      defaultVersionType: 'specificTag'
      version: 'v$(ort_version)'
      itemPattern: '*-linux-$(buildArch)-gpu-$(ort_version)*'
      downloadPath: '$(Build.SourcesDirectory)'
    displayName: Download the ONNXRuntime prebuilt package.
      -
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.tgz'
      destinationFolder: '$(Build.SourcesDirectory)/onnxruntime-genai/ort'
      cleanDestinationFolder: false
      overwriteExistingFiles: true
    displayName: Unpack ONNXRuntime package.

  - script: |
      set -e -x
      python3 tools/ci_build/get_docker_image.py --dockerfile tools/ci_build/github/linux/docker/manylinux//Dockerfile.manylinux2_28_cuda \
        --context tools/ci_build/github/linux/docker/manylinux \
        --docker-build-args "--build-arg BUILD_UID=$( id -u )" \
        --container-registry onnxruntimebuildcache \
        --manylinux-src $(Build.SourcesDirectory)/manylinux \
        --repository onnxruntimegpubuild
    displayName: 'Get Docker Image'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'

  - script: |
      set -e -x
      docker run \
        --gpus all \
        --rm \
        --volume $(Build.SourcesDirectory)/onnxruntime-genai:/onnxruntime_src  \
        -w /onnxruntime_src onnxruntimegpubuild bash -c "echo $PATH && /usr/bin/cmake -DCMAKE_CUDA_ARCHITECTURES=86 --preset linux_gcc_cuda_release && /usr/bin/cmake --build --preset linux_gcc_cuda_release"
    displayName: 'Build Python Wheel'
    workingDirectory: '$(Build.SourcesDirectory)/onnxruntime-genai'

  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/onnxruntime-genai/build/gcc_gpu/release/wheel'
      Contents: '*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime python wheel'
    inputs:
      ArtifactName: onnxruntime-genai-linux-gpu

  - template: steps/component-governance-component-detection-step.yml
    parameters:
      condition: 'succeeded'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
