parameters:
  - name: arch
    type: string
    default: 'x64'
jobs:
- job: Linux_CPU_Wheels
  strategy:
    matrix:
      x64:
        buildArch: 'x64'
        machine_pool: 'onnxruntime-Ubuntu2204-AMD-CPU'
        docker_arch: 'x64'
      ${{ if eq(parameters.arch, 'arm64') }}:
        arm64:
          buildArch: 'arm64'
          machine_pool: 'onnxruntime-linux-ARM64-CPU-2019'
          docker_arch: 'aarch64'
  timeoutInMinutes: 240
  workspace:
    clean: all
  pool: $(machine_pool)
  variables:
  # The build machine pool doesn't have dotnet, so it can't run CG.
  - name: skipComponentGovernanceDetection
    value: true

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - template: steps/set-nightly-build-option-variable-step.yml

  - bash: |
      pip install -r scripts/requirements.txt
      python3 scripts/download_onnxruntime.py --ort_version 1.17.0 --os linux --is_gpu False --arch $(buildArch)
    displayName: Download OnnxRuntime
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      set -e -x
      python3 tools/ci_build/get_docker_image.py --dockerfile tools/ci_build/github/linux/docker/manylinux/Dockerfile.manylinux2_28_cpu \
        --context tools/ci_build/github/linux/docker/manylinux \
        --docker-build-args "--build-arg BUILD_UID=$( id -u )" \
        --container-registry onnxruntimebuildcache \
        --repository onnxruntimecpubuild$(docker_arch)
    displayName: 'Get Docker Image'

  - script: |
      set -e -x
      docker run \
      --rm \
      --volume $(Build.SourcesDirectory):/onnxruntime_src \
      -w /onnxruntime_src onnxruntimecpubuild$(docker_arch) bash -c "echo $PATH && /usr/bin/cmake --preset linux_gcc_cpu_release && /usr/bin/cmake --build --preset linux_gcc_cpu_release"
    displayName: 'Build Python Wheel'

  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/build/gcc_cpu/release/wheel'
      Contents: '*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime python wheel'
    inputs:
      ArtifactName: onnxruntime-genai-linux-cpu-$(buildArch)

  - template: steps/component-governance-component-detection-step.yml
    parameters:
      condition: 'succeeded'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()