parameters:
- name: arch
  type: string
- name: ep
  type: string
- name: ort_version
  type: string
- name: cuda_version
  type: string
  default: ''
- name: cuda_display_version
  type: string
  default: ''
- name: os
  type: string
  values:
  - 'linux'
  - 'win'
- name: build_config
  type: string
  default: 'release'


jobs:
- job: python_${{ parameters.os }}_${{ parameters.ep }}${{ parameters.cuda_display_version }}_${{ parameters.arch }}_packaging
  ${{ if eq(parameters.os, 'linux') }}:
    ${{ if eq(parameters.arch, 'x64') }}:
      pool: 'onnxruntime-Ubuntu2204-AMD-CPU'
    ${{ elseif eq(parameters.arch, 'arm64') }}:
      pool: 'onnxruntime-genai-Ubuntu2004-ARM-CPU'
    ${{ else }}:
      pool: 'nnxruntime-Ubuntu2204-AMD-CPU'
  ${{ if eq(parameters.os, 'win') }}:
    ${{ if eq(parameters.arch, 'x64') }}:
      pool: 'onnxruntime-Win-CPU-2022'
    ${{ elseif eq(parameters.arch, 'arm64') }}:
      pool: 'onnxruntime-genai-windows-vs-2022-arm64'
    ${{ else }}:
      pool: 'onnxruntime-Win-CPU-2022'

  strategy:
    ${{ if eq(parameters.arch, 'arm64') }}:
      matrix:
        Python311:
          PyDotVer: '3.11'
          PyNoDotVer: '311'
        Python312:
          PyDotVer: '3.12'
          PyNoDotVer: '312'
    ${{ else }}:
      matrix:
        Python38:
          PyDotVer: '3.8'
          PyNoDotVer: '38'
        Python39:
          PyDotVer: '3.9'
          PyNoDotVer: '39'
        Python310:
          PyDotVer: '3.10'
          PyNoDotVer: '310'
        Python311:
          PyDotVer: '3.11'
          PyNoDotVer: '311'
        Python312:
          PyDotVer: '3.12'
          PyNoDotVer: '312'
    
  timeoutInMinutes: 240
  workspace:
    clean: all
  #  set variables here to be used in the template and steps
  variables:
  - name: skipComponentGovernanceDetection
    ${{ if eq(parameters.os, 'linux') }}:
      value: true
    ${{ if eq(parameters.os, 'win') }}:
      value: false
  - name: arch
    value: ${{ parameters.arch }}
  - name: artifactName
    value: 'onnxruntime-genai-${{ parameters.os }}-${{ parameters.ep }}-${{ parameters.arch }}'
  - name: build_config
    value: ${{ parameters.build_config }}
  - name: buildDir
    value: 'build/${{ parameters.ep }}'
  - name: cuda_version
    value: ${{ parameters.cuda_version }}
  - name: ep
    value: ${{ parameters.ep }}
  - name: ort_version
    value: ${{ parameters.ort_version }}
  - name: os
    value: ${{ parameters.os }}

  - name: feed_name
    value: '7982ae20-ed19-4a35-a362-a96ac99897b7'

  - name: ort_filename
    ${{ if eq(parameters.ep, 'cpu') }}:
      value: 'Microsoft.ML.OnnxRuntime'
    ${{ elseif eq(parameters.ep, 'cuda') }}:
      ${{if eq(parameters.os, 'win') }}:
        value: 'Microsoft.ML.OnnxRuntime.Gpu.Windows'
      ${{ else }}:
        value: 'Microsoft.ML.OnnxRuntime.Gpu.Linux'
    ${{ elseif eq(parameters.ep, 'directml')}}:
      value: 'Microsoft.ML.OnnxRuntime.DirectML'
    ${{ elseif eq(parameters.ep, 'rocm')}}:
      value: 'Microsoft.ML.OnnxRuntime.ROCm'
    ${{ else }}:
      value: 'Microsoft.ML.OnnxRuntime'

  - name: dml_dir
    value: 'Microsoft.AI.DirectML.1.15.1'
  - name: dml_zip
    value: 'Microsoft.AI.DirectML.1.15.1.zip'
  - name: dml_url
    value: "https://www.nuget.org/api/v2/package/Microsoft.AI.DirectML/1.15.1"

  - name: d3d12_dir
    value: 'Microsoft.Direct3D.D3D12.1.614.0'
  - name: d3d12_zip
    value: 'Microsoft.Direct3D.D3D12.1.614.0.zip'
  - name: d3d12_url
    value: "https://www.nuget.org/api/v2/package/Microsoft.Direct3D.D3D12/1.614.0"

  steps:
  - script: |
      MKDIR $(Agent.ToolsDirectory)\Python\3.12.3\arm64 
      XCOPY /s /y /h /e /c /q "C:\Python\Python312\*.*" $(Agent.ToolsDirectory)\Python\3.12.3\arm64\
      COPY NUL $(Agent.ToolsDirectory)\Python\3.12.3\arm64.complete
      DIR $(Agent.ToolsDirectory)\Python
      DIR $(Agent.ToolsDirectory)\Python\3.12.3
      DIR $(Agent.ToolsDirectory)\Python\3.12.3\arm64
      DIR "C:\Python"
    displayName: Copy python 3.12.3 version to agent tools directory
    condition: and(eq(variables['arch'], 'arm64'), eq(variables['os'], 'win'), eq(variables['PyDotVer'], '3.12'))

  - script: |
      MKDIR $(Agent.ToolsDirectory)\Python\3.11.0\arm64
      XCOPY /s /y /h /e /c /q "C:\Python\Python311\*.*" $(Agent.ToolsDirectory)\Python\3.11.0\arm64\
      COPY NUL $(Agent.ToolsDirectory)\Python\3.11.0\arm64.complete
      DIR $(Agent.ToolsDirectory)\Python
      DIR $(Agent.ToolsDirectory)\Python\3.11.0
      DIR $(Agent.ToolsDirectory)\Python\3.11.0\arm64
      DIR "C:\Python"
    displayName: Copy python 3.11.0 version to agent tools directory
    condition: and(eq(variables['arch'], 'arm64'), eq(variables['os'], 'win'), eq(variables['PyDotVer'], '3.11'))

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PyDotVer)
      addToPath: true
      architecture: $(arch)
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import sys
        import subprocess
        subprocess.call(['pip', 'install', '-q', 'setuptools', 'wheel', 'build', 'packaging', 'twine'])
      workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Install python modules'

  - ${{ if eq(parameters.os, 'linux') }}:
    - template: steps/capi-linux-step.yml
      parameters:
        target: 'python'
        arch: ${{ parameters.arch }}
        ep: ${{ parameters.ep }}
        build_config: ${{ parameters.build_config }}

  # Windows job needs to set the python version and install the required packages
  - ${{ if eq(parameters.os, 'win') }}:
    - template: steps/capi-win-step.yml
      parameters:
        target: 'python'
        arch: ${{ parameters.arch }}
        ep: ${{ parameters.ep }}
        build_config: ${{ parameters.build_config }}

  - template: steps/compliant-and-cleanup-step.yml

