parameters:
  arch: 'x64'
  ort_version: '1.17.1'

jobs:
- job: Windows_CPU_Wheels
  pool: 'onnxruntime-Win-CPU-2022'
  strategy:
    matrix:
      Python38_x64:
        PythonVersion: '3.8'
        buildArch: ${{ parameters.arch }}
      Python39_x64:
        PythonVersion: '3.9'
        buildArch: ${{ parameters.arch }}
      Python310_x64:
        PythonVersion: '3.10'
        buildArch: ${{ parameters.arch }}
      Python311_x64:
        PythonVersion: '3.11'
        buildArch: ${{ parameters.arch }}
      Python312_x64:
        PythonVersion: '3.12'
        buildArch: ${{ parameters.arch }}
  variables:
    BuildConfig: 'RelWithDebInfo'
    ort_version: '1.17.1'
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PythonVersion)
      addToPath: true
      architecture: $(buildArch)
  - task: onebranch.pipeline.tsaoptions@1
    displayName: 'OneBranch TSAOptions'
    inputs:
      tsaConfigFilePath: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
      appendSourceBranchName: false

  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import sys
        import subprocess
        subprocess.call(['pip', 'install', '-q', 'setuptools', 'wheel', 'build', 'packaging'])
      workingDirectory: '$(Build.BinariesDirectory)'
      displayName: 'Install python modules'

  - template: steps/set-nightly-build-option-variable-step.yml

  - task: DownloadGitHubRelease@0
    inputs:
      connection: 'GitHub - Release'
      userRepository: 'microsoft/onnxruntime'
      defaultVersionType: 'specificTag'
      version: 'v${{ parameters.ort_version }}'
      itemPattern: 'onnxruntime-win-$(buildArch)-${{ parameters.ort_version }}*'
      downloadPath: '$(Build.SourcesDirectory)'
    displayName: Download ONNXRuntime
      -
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.zip'
      destinationFolder: '$(Build.SourcesDirectory)'
      cleanDestinationFolder: false
      overwriteExistingFiles: true
    displayName: Unzip OnnxRuntime

  - powershell: |
      Rename-Item -Path onnxruntime-win-$(buildArch)-${{ parameters.ort_version }} -NewName ort
    displayName: Rename Onnxruntime to ort
    workingDirectory: '$(Build.SourcesDirectory)'

  - powershell: |
      cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=$(BuildConfig) -DUSE_CUDA=OFF -DENABLE_TESTS=OFF -S . -B build
      cmake --build build --config $(BuildConfig)  --parallel --target python
    displayName: 'Build pybind with CMake'

  # BinSkim is skipped because onnxruntime-genai is build as static library

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory)\build\wheel -Recurse

  - template: steps/win-esrp-dll-step.yml
    parameters:
      FolderPath: '$(Build.SourcesDirectory)\build\wheel\onnxruntime_genai'
      DisplayName: 'ESRP - Sign Native dlls'
      DoEsrp: true
      Pattern: '*.pyd,*.dll'
  #
  - powershell: |
      cmake --build build --config $(BuildConfig) --parallel --target PyPackageBuild
    displayName: 'Build Python Wheel'

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse

  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\build\wheel\'
      Contents: '*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai python wheel'
    inputs:
      ArtifactName: onnxruntime-genai-win-cpu-$(buildArch)

  - script: |
      7z x *.whl
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    displayName: 'unzip the package'

  - powershell: |
      Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -Recurse
    displayName: 'Verify the package'

  - task: CredScan@3
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
    continueOnError: true

  - task: TSAUpload@2
    displayName: 'TSA upload'
    condition: and(and (succeeded(), and(eq(variables['buildArch'], 'x64'), eq(variables['PythonVersion'], '3.8'))), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      GdnPublishTsaOnboard: false
      GdnPublishTsaConfigFile: '$(Build.sourcesDirectory)\.config\tsaoptions.json'
    continueOnError: true

  - template: steps/component-governance-component-detection-step.yml
    parameters:
      condition: 'succeeded'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()