jobs:
- job: Windows_GPU_Wheels
  pool: 'onnxruntime-Win-CPU-2022'
#  pool: 'onnxruntime-Win2022-GPU-A10'
  strategy:
    matrix:
      Python38:
        PythonVersion: '3.8'
      Python39:
        PythonVersion: '3.9'
      Python310:
        PythonVersion: '3.10'
      Python311:
        PythonVersion: '3.11'
      Python312:
        PythonVersion: '3.12'
  variables:
    BuildConfig: 'RelWithDebInfo'
    cuda_version: '12.2'
    cuda_dir: '$(Build.SourcesDirectory)\cuda_sdk'
    ort_version: '1.17.0'
  timeoutInMinutes: 180
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PythonVersion)
      addToPath: true
      architecture: x64
  - task: onebranch.pipeline.tsaoptions@1
    displayName: 'OneBranch TSAOptions'
    inputs:
      tsaConfigFilePath: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
      appendSourceBranchName: false

  - template: steps/set-nightly-build-option-variable-step.yml

#  - bash: |
#      pip3 install -r requirements.txt
##      python3 download_onnxruntime.py --ort_version 1.17.0 --is_gpu True --os win --arch x64
#    displayName: Download requirements.txt
#    workingDirectory: '$(Build.SourcesDirectory)\scripts'

  - task: DownloadGitHubRelease@0
    inputs:
      connection: 'GitHub - Release'
      userRepository: 'microsoft/onnxruntime'
      defaultVersionType: 'specificTag'
      version: 'v$(ort_version)'
      itemPattern: 'onnxruntime-win-$(buildArch)-gpu-$(ort_version).zip'
      downloadPath: '$(Build.SourcesDirectory)'
    displayName: Download ONNXRuntime
      -
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.zip'
      destinationFolder: '$(Build.SourcesDirectory)'
      cleanDestinationFolder: false
      overwriteExistingFiles: true
    displayName: Unzip OnnxRuntime

  - powershell: |
      Rename-Item -Path onnxruntime-win-$(buildArch)-gpu-$(ort_version) -NewName ort
    displayName: Rename Onnxruntime to ort
    workingDirectory: '$(Build.SourcesDirectory)'

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse

  - powershell: |
      azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v$(cuda_version)" $(cuda_dir)
    displayName: 'Download CUDA'

  - powershell: |
      Get-ChildItem -Path $(cuda_dir) -Recurse
    displayName: 'Verify CUDA download'

  - powershell: |
      cmake -G "Visual Studio 17 2022" -A x64 -T cuda=$(cuda_dir)\v$(cuda_version) -DCMAKE_BUILD_TYPE=$(BuildConfig) -DUSE_CUDA=TRUE -S . -B build
      cmake --build build --config $(BuildConfig) --parallel
    displayName: 'Build pybind with CMake'
  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory)\build\wheel\ -Recurse
#   Esrp signing
  - template: steps/win-esrp-dll-step.yml
    parameters:
      FolderPath: '$(Build.SourcesDirectory)\build\wheel\onnxruntime-genai\'
      DisplayName: 'ESRP - Sign Native dlls'
      DoEsrp: true
      Pattern: '*.pyd,*.dll'

#  - task: PythonScript@0
#    displayName: 'Build wheel'
#    inputs:
#      scriptPath: '$(Build.SourcesDirectory)\setup.py'
#      arguments: 'bdist_wheel ${{ parameters.BUILD_PY_PARAMETERS }} $(NightlyBuildOption) --wheel_name_suffix=${{ parameters.EP_NAME }}'
#      workingDirectory: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo'
#  - bash: |
#      cmake --build build --config $(BuildConfig) --parallel
#    displayName: 'Build Python Wheel'
  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse
  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\build\wheel\'
      Contents: '*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ONNXRuntime Genai python wheel'
    inputs:
      ArtifactName: onnxruntime-genai-win-gpu

  - script: |
      7z x *.whl
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    displayName: 'unzip the package'

  - task: CredScan@3
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
    continueOnError: true

  - task: BinSkim@4
    displayName: 'Run BinSkim'
    inputs:
      AnalyzeTargetGlob: '+:file|$(Build.ArtifactStagingDirectory)\**\*.dll;-:file|$(Build.ArtifactStagingDirectory)\**\DirectML.dll'
    continueOnError: true

  - task: TSAUpload@2
    displayName: 'TSA upload'
    condition: and(and (succeeded(), eq(variables['PythonVersion'], '3.8')), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      GdnPublishTsaOnboard: false
      GdnPublishTsaConfigFile: '$(Build.sourcesDirectory)\.gdn\.gdntsa'
    continueOnError: true

  - template: steps/component-governance-component-detection-step.yml
    parameters:
      condition: 'succeeded'

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
