parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_gpu
  type: boolean
- name: enable_win_arm
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_gpu
  type: boolean
- name: enable_linux_arm
  type: boolean
- name: ort_version
  type: string
- name: cuda_version
  type: string

stages:
- stage: capi_packaging
  jobs:
  - ${{ if eq(parameters.enable_win_cpu, true) }}:
    - template: jobs/capi-win-packaging-job.yml
      parameters:
        cuda_version: ${{ parameters.cuda_version }}
        ort_version: ${{ parameters.ort_version }}
        arch: 'x64'
        ep: 'cpu'
  - ${{ if eq(parameters.enable_win_gpu, true) }}:
    - template: jobs/capi-win-packaging-job.yml
      parameters:
        cuda_version: ${{ parameters.cuda_version }}
        ort_version: ${{ parameters.ort_version }}
        arch: 'x64'
        ep: 'gpu'
  - ${{ if eq(parameters.enable_win_arm, true) }}:
    - template: jobs/capi-win-packaging-job.yml
      parameters:
        cuda_version: ${{ parameters.cuda_version }}
        ort_version: ${{ parameters.ort_version }}
        arch: 'arm64'
        ep: 'cpu'
