parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_gpu
  type: boolean
- name: enable_win_arm
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_gpu
  type: boolean
- name: enable_linux_arm
  type: boolean
- name: ort_version
  type: string
- name: cuda_version
  type: string

stages:
- stage: capi_packaging
  variables:
  - name: arch
    ${{ if or(eq(parameters.enable_win_cpu, true), eq(parameters.enable_win_gpu, true)) }}:
      value: 'x64'
    ${{ if eq(parameters.enable_win_arm, true) }}:
      value: 'arm64'
  - name: ep
    ${{ if or(eq(parameters.enable_win_cpu, true), eq(parameters.enable_win_arm, true)) }}:
      value: 'cpu'
    ${{ if eq(parameters.enable_win_gpu, true) }}:
      value: 'gpu'
  jobs:
  - template: jobs/capi-win-packaging-job.yml
    parameters:
      cuda_version: ${{ parameters.cuda_version }}
      ort_version: ${{ parameters.ort_version }}
      arch: $(arch)
      ep: $(ep)
