parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_cuda
  type: boolean
- name: enable_win_dml
  type: boolean
- name: enable_win_arm64
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_cuda
  type: boolean
- name: ort_version
  type: string
- name: ort_cuda_version
  type: string
- name: ort_dml_version
  type: string
- name: cuda_version
  type: string
  default: ''
- name: build_config
  type: string
  default: 'release'


stages:
- stage: capi_packaging
  jobs:
  - ${{ if eq(parameters.enable_win_cpu, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'win'
        build_config: ${{ parameters.build_config }}

  - ${{ if eq(parameters.enable_win_arm64, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'arm64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'win'
        build_config: ${{ parameters.build_config }}

  - ${{ if eq(parameters.enable_win_dml, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'x64'
        ep: 'directml'
        ort_version: ${{ parameters.ort_dml_version }}
        os: 'win'
        build_config: ${{ parameters.build_config }}

  - ${{ if and(eq(parameters.enable_win_arm64, true), eq(parameters.enable_win_dml, true)) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'arm64'
        ep: 'directml'
        ort_version: ${{ parameters.ort_dml_version }}
        os: 'win'
        build_config: ${{ parameters.build_config }}

  - ${{ if eq(parameters.enable_win_cuda, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'x64'
        cuda_version: ${{ parameters.cuda_version }}
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_version }}
        os: 'win'
        build_config: ${{ parameters.build_config }}

  - ${{ if eq(parameters.enable_linux_cpu, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'linux'
        build_config: ${{ parameters.build_config }}

  - ${{ if eq(parameters.enable_linux_cuda, true) }}:
    - template: jobs/capi-packaging-job.yml
      parameters:
        arch: 'x64'
        cuda_version: ${{ parameters.cuda_version }}
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_version }}
        os: 'linux'
        build_config: ${{ parameters.build_config }}