parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_gpu
  type: boolean
- name: enable_win_arm
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_gpu
  type: boolean
- name: enable_linux_arm
  type: boolean
- name: ort_version
  type: string
- name: cuda_version
  type: string

stages:
- stage: nuget_packaging
  jobs:
  - template: jobs/nuget-win-packaging-job.yml
    parameters:
      cuda_version: ${{ parameters.cuda_version }}
      ort_version: ${{ parameters.ort_version }}
      build_x64_cpu: ${{ parameters.enable_win_cpu }}
      build_gpu: ${{ parameters.enable_win_gpu }}
      build_arm64_cpu: ${{ parameters.enable_win_arm }}

#  - ${{ if eq(parameters.enable_linux_cpu, true) }}:
#    - template: jobs/nuget-linux-cpu-packaging-job.yml
#      parameters:
#        ort_version: ${{ parameters.ort_version }}
#  - ${{ if eq(parameters.enable_linux_gpu, true) }}:
#    - template: jobs/nuget-linux-gpu-packaging-job.yml
#      parameters:
#        ort_version: ${{ parameters.ort_version }}
#  - ${{ if eq(parameters.enable_linux_arm, true) }}:
#    - template: jobs/nuget-linux-cpu-packaging-job.yml
#      parameters:
#        arch: 'arm64'
#        ort_version: ${{ parameters.ort_version }}