parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_gpu
  type: boolean
- name: enable_win_arm
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_gpu
  type: boolean
- name: enable_linux_arm
  type: boolean
- name: ort_version
  type: string

stages:
- stage: nuget_packaging
  jobs:
  - ${{ if eq(parameters.enable_win_cpu, true) }}:
    - template: jobs/nuget-win-cpu-packaging-job.yml
      parameters:
        ort_version: ${{ parameters.ort_version }}
  - ${{ if eq(parameters.enable_win_gpu, true) }}:
    - template: jobs/nuget-win-gpu-packaging-job.yml
      parameters:
        ort_version: ${{ parameters.ort_version }}
  - ${{ if eq(parameters.enable_win_arm, true) }}:
    - template: jobs/nuget-win-cpu-packaging-job.yml
      parameters:
        arch: 'arm64'
        ort_version: ${{ parameters.ort_version }}

#  - ${{ if eq(parameters.enable_linux_cpu, true) }}:
#    - template: jobs/nuget-linux-cpu-packaging-job.yml
#      parameters:
#        ort_version: ${{ parameters.ort_version }}
#  - ${{ if eq(parameters.enable_linux_gpu, true) }}:
#    - template: jobs/nuget-linux-gpu-packaging-job.yml
#      parameters:
#        ort_version: ${{ parameters.ort_version }}
#  - ${{ if eq(parameters.enable_linux_arm, true) }}:
#    - template: jobs/nuget-linux-cpu-packaging-job.yml
#      parameters:
#        arch: 'arm64'
#        ort_version: ${{ parameters.ort_version }}