parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

- name: enable_macos_cpu
  displayName: 'Whether MacOS CPU package is built.'
  type: boolean
  default: true

- name: ort_version
  type: string
- name: ort_cuda_version
  type: string
- name: ort_dml_version
  type: string
- name: build_config
  type: string
  default: 'release'

stages:
- stage: nuget_packaging
  jobs:
    - ${{ if or(eq(parameters.enable_linux_cpu, true), eq(parameters.enable_win_cpu, true), eq(parameters.enable_macos_cpu, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cpu'
          ort_version: ${{ parameters.ort_version }}
          build_config: ${{ parameters.build_config }}
          enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
          enable_win_cpu: ${{ parameters.enable_win_cpu }}
          enable_win_arm64: ${{ parameters.enable_win_arm64 }}
          enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
    - ${{ if or(eq(parameters.enable_linux_cuda, true), eq(parameters.enable_win_cuda, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cuda'
          ort_version: ${{ parameters.ort_cuda_version }}
          build_config: ${{ parameters.build_config }}
          enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
          enable_win_cuda: ${{ parameters.enable_win_cuda }}
    - ${{ if eq(parameters.enable_win_dml, true) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'directml' 
          ort_version: ${{ parameters.ort_dml_version }}
          build_config: ${{ parameters.build_config }}
          enable_win_dml: ${{ parameters.enable_win_dml }}
          enable_win_arm64: ${{ parameters.enable_win_arm64 }}
