parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

- name: enable_macos_cpu
  displayName: 'Whether MacOS CPU package is built.'
  type: boolean
  default: true

- name: enable_android
  displayName: 'Whether Android AAR package is built.'
  type: boolean
  default: true

- name: enable_apple_framework
  displayName: 'Whether Apple framework for iOS & MacCatalyst is built.'
  type: boolean
  default: true

- name: enable_win_qnn
  displayName: Whether QNN nuget package should be built.'
  type: boolean
  default: true

- name: ort_version
  type: string
- name: ort_cuda_version
  type: string
- name: ort_dml_version
  type: string
- name: build_config
  type: string
  default: 'release'

- name: nuget_version_type
  type: string
  default: 'stable'

stages:
- stage: nuget_packaging
  jobs:
    - ${{ if or(eq(parameters.enable_linux_cpu, true), eq(parameters.enable_win_cpu, true), eq(parameters.enable_macos_cpu, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cpu'
          ort_version: ${{ parameters.ort_version }}
          build_config: ${{ parameters.build_config }}
          enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
          enable_win_cpu: ${{ parameters.enable_win_cpu }}
          enable_win_arm64: ${{ parameters.enable_win_arm64 }}
          enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
          enable_android: ${{ parameters.enable_android }}
          enable_apple_framework: ${{ parameters.enable_apple_framework }}
          nuget_version_type: ${{ parameters.nuget_version_type }}
    - ${{ if or(eq(parameters.enable_linux_cuda, true), eq(parameters.enable_win_cuda, true)) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cuda'
          ort_version: ${{ parameters.ort_cuda_version }}
          build_config: ${{ parameters.build_config }}
          enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
          enable_win_cuda: ${{ parameters.enable_win_cuda }}
          nuget_version_type: ${{ parameters.nuget_version_type }}
    - ${{ if eq(parameters.enable_win_dml, true) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'directml'
          ort_version: ${{ parameters.ort_dml_version }}
          build_config: ${{ parameters.build_config }}
          enable_win_dml: ${{ parameters.enable_win_dml }}
          enable_win_arm64: ${{ parameters.enable_win_arm64 }}
    - ${{ if eq(parameters.enable_win_qnn, true) }}:
      - template: jobs/nuget-packaging-job.yml
        parameters:
          ep: 'cpu'
          ort_version: ${{ parameters.ort_version }}
          build_config: ${{ parameters.build_config }}
          enable_linux_cpu: false
          enable_win_cpu: false
          enable_win_arm64: true
          enable_macos_cpu: false
          enable_android: false
          enable_apple_framework: false
          enable_win_qnn: true
          nuget_version_type: ${{ parameters.nuget_version_type }}
