parameters:
- name: enable_win_cpu
  type: boolean
- name: enable_win_cuda
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_cuda
  type: boolean
- name: ort_version
  type: string
- name: cuda_version
  type: string
  default: ''
stages:
- stage: Python_Packaging_Stage
  jobs:
  - ${{ if eq(parameters.enable_win_cpu, true) }}:
    - template: jobs/py-win-packaging-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
  - ${{ if eq(parameters.enable_win_cuda, true) }}:
    - template: jobs/py-win-packaging-job.yml
      parameters:
        arch: 'x64'
        cuda_version: ${{ parameters.cuda_version }}
        ep: 'cuda'
        ort_version: ${{ parameters.ort_version }}


  - ${{ if eq(parameters.enable_linux_cpu, true) }}:
    - template: jobs/py-linux-packaging-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
  - ${{ if eq(parameters.enable_linux_cuda, true) }}:
    - template: jobs/py-linux-packaging-job.yml
      parameters:
        arch: 'x64'
        cuda_version: ${{ parameters.cuda_version }}
        ep: 'cuda'
        ort_version: ${{ parameters.ort_version }}




