parameters:
- name: SpecificArtifact
  displayName: Use Specific Artifact
  type: boolean
  default: false
- name: BuildId
  displayName: Specific Artifact's BuildId
  type: string
  default: '0'
- name: enable_win_cpu
  type: boolean
- name: enable_win_cuda
  type: boolean
- name: enable_win_dml
  type: boolean
- name: enable_win_arm64_cpu
  type: boolean
- name: enable_linux_cpu
  type: boolean
- name: enable_linux_cuda
  type: boolean
- name: enable_macos_cpu
  type: boolean
- name: ort_version
  type: string
- name: ort_cuda_118_version
  type: string
- name: ort_cuda_122_version
  type: string
- name: ort_rocm_version
  type: string
- name: ort_dml_version
  type: string
- name: cuda_versions
  type: string
  default: '11.8,12.2'


stages:
- stage: python_validation
  jobs:
  - ${{ if eq(parameters.enable_win_cpu, true) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'win'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if eq(parameters.enable_win_arm64_cpu, true) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'arm64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'win'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if eq(parameters.enable_win_dml, true) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        ep: 'directml'
        ort_version: ${{ parameters.ort_dml_version }}
        os: 'win'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if and(eq(parameters.enable_win_cuda, true), contains(parameters.cuda_versions, '11.8')) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        cuda_version: '11.8'
        cuda_display_version: '118'
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_118_version }}
        os: 'win'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if and(eq(parameters.enable_win_cuda, true), contains(parameters.cuda_versions, '12.2')) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        cuda_version: '12.2'
        cuda_display_version: '122'
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_122_version }}
        os: 'win'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if eq(parameters.enable_linux_cpu, true) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'linux'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if and(eq(parameters.enable_linux_cuda, true), contains(parameters.cuda_versions, '11.8')) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        cuda_version: '11.8'
        cuda_display_version: '118'
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_118_version }}
        os: 'linux'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}
  - ${{ if and(eq(parameters.enable_linux_cuda, true), contains(parameters.cuda_versions, '12.2')) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        cuda_version: '12.2'
        cuda_display_version: '122'
        ep: 'cuda'
        ort_version: ${{ parameters.ort_cuda_122_version }}
        os: 'linux'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}

  - ${{ if eq(parameters.enable_macos_cpu, true) }}:
    - template: jobs/py-validation-job.yml
      parameters:
        arch: 'x64'
        ep: 'cpu'
        ort_version: ${{ parameters.ort_version }}
        os: 'osx'
        SpecificArtifact: ${{ parameters.SpecificArtifact }}
        BuildId: ${{ parameters.BuildId }}