// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
#pragma once

#include <stdint.h>
#include <memory>
#include <vector>
#include <list>

#include "block.h"
#include "request.h"

namespace Generators {

struct BlockTable {
  std::shared_ptr<Request> request;
  std::vector<std::shared_ptr<Block>> blocks;  // List of blocks alloted to the request.
};

struct PagedKeyValueCache {
 public:
  PagedKeyValueCache(std::shared_ptr<Model> model);

  bool CanAdd(std::shared_ptr<Request> request) const;

  void Add(std::shared_ptr<Request> request);

  bool CanAppendTokens(std::shared_ptr<Request> request, size_t num_tokens) const;

  void AppendTokens(std::shared_ptr<Request> request, size_t num_tokens);

  void Remove(std::shared_ptr<Request> request);

  // Returns the K, V cache for the given layer_id.
  std::pair<OrtValue*, OrtValue*> Cache(size_t layer_id);

  // Shape: [batch_size, max_num_blocks_per_sequence]
  // Assume that the block tables are requested for sequences with ids [2, 5, 7]
  // Assume the block tables for given sequence ids are:
  // {
  //   2: [0, 1, 2],
  //   5: [3, 7, 9],
  //   7: [4, 5, 6, 8]
  // }
  // Invoking this function will return the block tables as:
  // [ [0, 1, 2, -1],
  //   [3, 7, 9, -1],
  //   [4, 5, 6, 8] ]
  //
  // This implies that the sequence with sequence id 2 has its kv cache stored in blocks with ids [0, 1, 2],
  // the sequence with sequence id 5 has its kv cache stored in blocks with ids [3, 7, 9], and and
  // the sequencewith sequence id 7 has its kv cache stored in blocks with ids [4, 5, 6, 8].
  // -1 is used to pad the block tables to the max blocks per sequence from the given sequences.
  // The order of the block tables is based on the order the provided sequence_ids.
  std::unique_ptr<OrtValue> BlockTables(const std::vector<size_t>& sequence_ids) const;

  // Shape: [num_tokens]
  // Prompt stage:
  // Assume the cache contains the blocks for sequences with ids [2, 5, 7]
  // Assume that the slot mapping for the given sequence ids are:
  // {
  //   2: 32, 33, 34, 35
  //   5: 0, 1, 2, 3, 4
  //   7: 16, 17, 18
  // }
  // And assume that the block size is 16.
  // The slot mapping tells us that the sequence with id 2 should fill its prompt KV cache tokens at slots
  // [0, 1, 2, 3] (slot_id % 16) in block 2 (slot_id / 16), the sequence with id 5 should fill its prompt KV
  // cache tokens at slots [0, 1, 2, 3, 4] in block 0, and the sequence with id 7 should fill its prompt KV
  // cache tokens at slots [0, 1, 2] in block 1.
  // Invoking this function will return the slot mapping as:
  // [ | 32, 33, 34, 35, | 0, 1, 2, 3, 4, | 16, 17, 18 | ]
  // Decoding stage:
  // The same principle applies for the decoding stage, but the slot mapping will only contain
  // the slot ids for the new token generated by the model.
  // For example, assume that the cache contains the blocks for sequences with ids [2, 5, 7]
  // Assume that the slot mapping for the given sequence ids are:
  // {
  //   2: 43,
  //   5: 29,
  //   7: 12
  // }
  // And assume that the block size is 16.
  // The slot mapping tells us that the sequence with id 2 should fill its KV cache token at slot
  // 11 (43 % 16) in block 2 (43 / 16), the sequence with id 5 should fill its KV cache token at slot
  // 13 (29 % 16) in block 1, and the sequence with id 7 should fill its KV cache token at slot
  // 12 (12 % 16) in block 0.
  // The order of the clot mapping is based on the order the provided sequence_ids.
  std::unique_ptr<OrtValue> SlotMapping(const std::vector<size_t>& sequence_ids) const;

 private:
  using LayerCache = std::unique_ptr<OrtValue>;  // Shape: [num_blocks, block_size * num_kv_heads * head_size]

  //   The key and the value cache is represented as an array of blocks. Each block contains
  //   a number of slots equal to the block size. Each slot contains num_kv_heads * head_size
  //   elements. Here the slot represents data generated by the model for a single token.
  //   This key-value cache is allocated for each layer in the model.
  //   Although the cache is preallocated, the actual memory is alloted to a sequence_id only as needed.
  //   View of the cache for each layer (LayerCache):
  //         -->|size of each block = block_size(M) * size of each slot|<--
  //            |______________________________________________________|
  //            |       -->|          |<-- size of each slot = num_kv_heads * head_size
  //            |          |          |                                |
  //            |__________|__________|________________________________|
  //   block 0  |  slot 0  |  slot 1  |  slot 2  |     .    |  slot M  |
  //   block 1  |          |          |          |          |          |
  //   block 2  |          |          |          |          |          |
  //   block 3  |          |          |          |          |          |
  //      .     |          |          |          |          |          |
  //      .     |          |          |          |          |          |
  //      .     |          |          |          |          |          |
  //            |          |          |          |          |          |
  //   block N  |__________|__________|__________|__________|__________|
  //   N = num_blocks per layer
  //   M = block_size per block

  std::shared_ptr<Model> model_;
  std::vector<std::pair<LayerCache, LayerCache>> cache_;                      // Pair of key and value caches for all layers
  std::unique_ptr<BlockPool> block_pool_;                                     // Allocator for blocks
  std::list<BlockTable> block_table_pool_;                                    // The pool of all block tables
  std::unordered_map<size_t, std::list<BlockTable>::iterator> block_tables_;  // Mapping of sequence_id to block_info
  std::unordered_map<size_t, size_t> copy_on_writes_;                         // Mapping of block ids to copy
};

}  // namespace Generators