#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
"""Fix type stubs generated by pybind11_stubgen for onnxruntime_genai."""
import argparse


def _strip_numpy_ndarray_generics(content: str) -> str:
    """Remove the generic parameter list from numpy.ndarray[...] annotations.

    pybind11_stubgen emits complex parameterized numpy array types such as:
      numpy.ndarray[numpy.float32, numpy.ndarray[numpy.dtype[numpy.float32], ...]]
    which are not portable and cause type-checker errors.  Replace them all
    with the plain ``numpy.ndarray``.
    """
    needle = "numpy.ndarray"
    parts: list[str] = []
    i = 0
    while i < len(content):
        pos = content.find(needle, i)
        if pos == -1:
            parts.append(content[i:])
            break
        # Copy everything up to (and including) the ndarray token
        parts.append(content[i : pos + len(needle)])
        i = pos + len(needle)
        # If a generic bracket group follows, skip it entirely
        if i < len(content) and content[i] == "[":
            depth = 0
            while i < len(content):
                if content[i] == "[":
                    depth += 1
                elif content[i] == "]":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
    return "".join(parts)


def fix_pyi_content(content: str) -> str:
    content = _strip_numpy_ndarray_generics(content)

    # Ensure 'import numpy' is present when numpy types are referenced
    if "numpy" in content and "import numpy" not in content:
        lines = content.splitlines(keepends=True)
        insert_pos = 0
        for i, line in enumerate(lines):
            if line.startswith("import ") or line.startswith("from "):
                insert_pos = i + 1
        lines.insert(insert_pos, "import numpy\n")
        content = "".join(lines)

    return content


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fix type stubs generated by pybind11_stubgen"
    )
    parser.add_argument(
        "-i",
        dest="input",
        required=True,
        help="Path to the .pyi file to fix in-place",
    )
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        content = f.read()

    content = fix_pyi_content(content)

    with open(args.input, "w", encoding="utf-8") as f:
        f.write(content)


if __name__ == "__main__":
    main()
