#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
"""Fix type stubs generated by pybind11_stubgen for onnxruntime_genai."""
import argparse
import re


def _strip_numpy_ndarray_generics(content: str) -> str:
    """Remove the generic parameter list from numpy.ndarray[...] annotations.

    pybind11_stubgen emits complex parameterized numpy array types such as:
      numpy.ndarray[numpy.float32, numpy.ndarray[numpy.dtype[numpy.float32], ...]]
    which are not portable and cause type-checker errors.  Replace them all
    with the plain ``numpy.ndarray``.
    """
    needle = "numpy.ndarray"
    parts: list[str] = []
    i = 0
    while i < len(content):
        pos = content.find(needle, i)
        if pos == -1:
            parts.append(content[i:])
            break
        # Copy everything up to (and including) the ndarray token
        parts.append(content[i : pos + len(needle)])
        i = pos + len(needle)
        # If a generic bracket group follows, skip it entirely
        if i < len(content) and content[i] == "[":
            depth = 0
            while i < len(content):
                if content[i] == "[":
                    depth += 1
                elif content[i] == "]":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
    return "".join(parts)


def _has_numpy_import(content: str) -> bool:
    """Return True if *content* contains a real 'import numpy' statement."""
    # Match bare 'import numpy' or 'import numpy as ...' at the start of a line
    return bool(re.search(r"^import numpy\b", content, re.MULTILINE))


def _insert_numpy_import(content: str) -> str:
    """Insert 'import numpy' after any existing import block.

    Handles module-level docstrings and ensures that ``from __future__``
    imports are not displaced.
    """
    lines = content.splitlines(keepends=True)

    # Find the end of the import block:
    # Skip module docstrings and blank lines, then find the last consecutive
    # import/from line.
    last_import_line = -1
    in_docstring = False
    docstring_quote = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        # Track triple-quoted docstrings so we don't mistake their contents
        # for imports.
        if not in_docstring:
            for quote in ('"""', "'''"):
                if stripped.startswith(quote):
                    # Single-line docstring: starts AND ends with the same
                    # quote and has content (or is empty) between them.
                    if stripped.endswith(quote) and len(stripped) >= len(quote) * 2:
                        # e.g. """text""" or """"""  – closed on this line
                        break
                    in_docstring = True
                    docstring_quote = quote
                    break
        else:
            if docstring_quote and docstring_quote in stripped:
                in_docstring = False
            continue

        if stripped.startswith("import ") or stripped.startswith("from "):
            last_import_line = i

    if last_import_line == -1:
        # No import statements found; find the first non-docstring, non-blank
        # line so we insert after any module docstring.
        after_docstring = 0
        in_ds = False
        ds_quote = None
        for i, line in enumerate(lines):
            stripped = line.strip()
            if not in_ds:
                for quote in ('"""', "'''"):
                    if stripped.startswith(quote):
                        if stripped.endswith(quote) and len(stripped) >= len(quote) * 2:
                            after_docstring = i + 1
                            break
                        in_ds = True
                        ds_quote = quote
                        break
                else:
                    if stripped:
                        # First non-blank, non-docstring line
                        break
            else:
                if ds_quote and ds_quote in stripped:
                    in_ds = False
                    after_docstring = i + 1
        insert_pos = after_docstring
    else:
        insert_pos = last_import_line + 1

    lines.insert(insert_pos, "import numpy\n")
    return "".join(lines)


def fix_pyi_content(content: str) -> str:
    content = _strip_numpy_ndarray_generics(content)

    # Ensure 'import numpy' is present when numpy types are referenced
    if "numpy" in content and not _has_numpy_import(content):
        content = _insert_numpy_import(content)

    return content


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fix type stubs generated by pybind11_stubgen"
    )
    parser.add_argument(
        "-i",
        dest="input",
        required=True,
        help="Path to the .pyi file to fix in-place",
    )
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        content = f.read()

    content = fix_pyi_content(content)

    with open(args.input, "w", encoding="utf-8") as f:
        f.write(content)


if __name__ == "__main__":
    main()
