# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License

"""
Tests for the LFM2-Audio pipeline against the tiny models in test/models/lfm2-audio.

The models are generated by test/python/create/create_dummy_lfm2_audio_models.py, and the tokenizer
is checked in zipped alongside them, so `_model_path` assembles a runnable model directory in a
temporary directory once per session. The speech model
emits one feature per 8 mel frames, the embedding model scatters those features over the placeholders
the processor writes, and the decoder's logits depend on the conv state, so generation only succeeds,
and only matches between runs, when the processor, the speech/embedding hand-off and the conv state
cache agree.

Run with:
    python -m pytest test/python/models/test_lfm2_audio_models.py --test_models test/models
"""

from __future__ import annotations

import json
import math
import os
import shutil
import tempfile
import wave
import zipfile
from pathlib import Path

import numpy as np
import onnxruntime_genai as og
import pytest

AUDIO_MARKER = "<|audio|>"
AUDIO_START_TOKEN_ID = 128  # <|audio_start|>: the model switching from text to speech
AUDIO_TOKEN_ID = 133  # <|reserved_123|>, model.audio_token_id in the fixture's genai_config.json
NUM_MELS = 128
SAMPLE_RATE = 16000
FFT_SIZE = 512
WIN_LENGTH = 400
HOP_LENGTH = 160
SUBSAMPLING_FACTOR = 8
LOG_EPS = 2.0**-24
NORM_EPS = 1e-5
# Settings of LiquidAI/LFM2-Audio-1.5B and LFM2.5-Audio-1.5B (config.json "preprocessor").
PREPROCESSOR_CONFIG = {
    "sample_rate": SAMPLE_RATE,
    "normalize": "per_feature",
    "window_size": 0.025,
    "window_stride": 0.01,
    "window": "hann",
    "features": NUM_MELS,
    "n_fft": FFT_SIZE,
    "log": True,
    "frame_splicing": 1,
    "dither": 1.0e-05,
    "pad_to": 0,
    "pad_value": 0.0,
}


# The tokenizer is checked in zipped: its 4.8 MB of vocabulary compresses to under 1 MB, and no test
# reads it as text. Refresh it with, from the model directory,
#   python -c "import zipfile; \
#              [zipfile.ZipFile('tokenizer.zip', 'w').writestr(n, open(n, 'rb').read()) for n in NAMES]"
# or take a fresh copy from LiquidAI/LFM2.5-Audio-1.5B.
TOKENIZER_ARCHIVE = "tokenizer.zip"
TOKENIZER_FILES = ("tokenizer.json", "tokenizer_config.json")

# One assembled directory per source, kept alive (and so undeleted) for the whole session.
_MODEL_DIRECTORIES: dict[str, tempfile.TemporaryDirectory] = {}


def _model_path(test_data_path) -> str:
    """The fixture model directory, with the tokenizer unpacked, assembled once per session.

    Everything the runtime loads has to sit in one directory, so the ONNX models and the config are
    copied next to the unpacked tokenizer rather than the archive being unpacked over the checkout.
    """
    source = Path(test_data_path) / "lfm2-audio"
    if not (source / "genai_config.json").exists():
        pytest.skip(f"LFM2-Audio test model not found at {source}")

    key = os.fspath(source)
    if key not in _MODEL_DIRECTORIES:
        holder = tempfile.TemporaryDirectory(prefix="lfm2-audio-")
        destination = Path(holder.name)
        for item in source.iterdir():
            if item.is_file() and item.name != TOKENIZER_ARCHIVE:
                shutil.copy(item, destination)
        with zipfile.ZipFile(source / TOKENIZER_ARCHIVE) as archive:
            # Named rather than extractall: the archive holds exactly these two files, and naming
            # them keeps a stray path in the archive from landing outside the directory.
            for name in TOKENIZER_FILES:
                (destination / name).write_bytes(archive.read(name))
        _MODEL_DIRECTORIES[key] = holder
    return _MODEL_DIRECTORIES[key].name


def _copy_model(test_data_path, tmp_path) -> Path:
    destination = tmp_path / "lfm2-audio"
    shutil.copytree(_model_path(test_data_path), destination)
    return destination


def _edit_json(path: Path, edit):
    config = json.loads(path.read_text())
    edit(config)
    path.write_text(json.dumps(config))


def _synthetic_signal(seconds: float, seed: int = 0) -> np.ndarray:
    """A few tones plus noise, quantized to 16-bit like the WAV that carries it."""
    rng = np.random.default_rng(seed)
    t = np.arange(int(seconds * SAMPLE_RATE)) / SAMPLE_RATE
    signal = 0.3 * np.sin(2 * np.pi * 440 * t) + 0.1 * np.sin(2 * np.pi * 3000 * t) + 0.05 * rng.standard_normal(t.size)
    return np.round(np.clip(signal, -1, 1) * 32767).astype(np.int16).astype(np.float32) / 32768.0


def _write_wav(path: Path, samples: np.ndarray, sample_rate: int = SAMPLE_RATE, channels: int = 1) -> str:
    pcm = np.round(samples * 32768.0).clip(-32768, 32767).astype("<i2")
    if channels > 1:
        pcm = np.repeat(pcm[:, None], channels, axis=1)
    with wave.open(os.fspath(path), "wb") as handle:
        handle.setnchannels(channels)
        handle.setsampwidth(2)
        handle.setframerate(sample_rate)
        handle.writeframes(pcm.tobytes())
    return os.fspath(path)


def _num_frames(num_samples: int) -> int:
    # torch.stft(center=True): one frame per hop plus one.
    return num_samples // HOP_LENGTH + 1


def _num_tokens(num_samples: int) -> int:
    return math.ceil(_num_frames(num_samples) / SUBSAMPLING_FACTOR)


def _slaney_mel_filterbank() -> np.ndarray:
    """librosa.filters.mel(sr, n_fft, n_mels, fmin=0, fmax=sr/2, norm="slaney") without librosa."""

    def hz_to_mel(hz):
        hz = np.asarray(hz, dtype=np.float64)
        mel = hz / (200.0 / 3)
        log_region = hz >= 1000.0
        mel[log_region] = 15.0 + np.log(hz[log_region] / 1000.0) / (np.log(6.4) / 27.0)
        return mel

    def mel_to_hz(mel):
        mel = np.asarray(mel, dtype=np.float64)
        hz = mel * (200.0 / 3)
        log_region = mel >= 15.0
        hz[log_region] = 1000.0 * np.exp((np.log(6.4) / 27.0) * (mel[log_region] - 15.0))
        return hz

    fft_freqs = np.linspace(0, SAMPLE_RATE / 2, FFT_SIZE // 2 + 1)
    mel_points = mel_to_hz(np.linspace(hz_to_mel([0.0])[0], hz_to_mel([SAMPLE_RATE / 2])[0], NUM_MELS + 2))
    fdiff = np.diff(mel_points)
    ramps = mel_points[:, None] - fft_freqs[None, :]
    weights = np.maximum(0, np.minimum(-ramps[:-2] / fdiff[:-1, None], ramps[2:] / fdiff[1:, None]))
    weights *= (2.0 / (mel_points[2 : NUM_MELS + 2] - mel_points[:NUM_MELS]))[:, None]
    return weights.astype(np.float32)


def _reference_mel(samples: np.ndarray) -> np.ndarray:
    """NeMo's AudioToMelSpectrogramPreprocessor in eval mode, as liquid-audio ships it, in numpy.

    Pre-emphasis, constant center padding, symmetric Hann window, power spectrum, Slaney mel filter
    bank, log with the 2^-24 guard, then per-feature normalization over the num_samples // hop
    frames get_seq_len counts as valid, with the frames past that zeroed.
    """
    preemphasized = np.concatenate([samples[:1], samples[1:] - 0.97 * samples[:-1]])
    padded = np.pad(preemphasized, FFT_SIZE // 2)
    num_frames = _num_frames(len(samples))
    window = np.zeros(FFT_SIZE, np.float64)
    window[(FFT_SIZE - WIN_LENGTH) // 2 :][:WIN_LENGTH] = 0.5 * (
        1 - np.cos(2 * np.pi * np.arange(WIN_LENGTH) / (WIN_LENGTH - 1))
    )
    frames = np.stack([padded[t * HOP_LENGTH : t * HOP_LENGTH + FFT_SIZE] * window for t in range(num_frames)])
    power = np.abs(np.fft.rfft(frames, axis=1)) ** 2
    log_mel = np.log(power @ _slaney_mel_filterbank().T.astype(np.float64) + LOG_EPS)

    valid = len(samples) // HOP_LENGTH
    mean = log_mel[:valid].mean(axis=0)
    std = np.sqrt(((log_mel[:valid] - mean) ** 2).sum(axis=0) / (valid - 1)) + NORM_EPS
    normalized = (log_mel - mean) / std
    normalized[valid:] = 0.0
    return normalized.astype(np.float32)


def _process(model_path: str, prompt: str, audios):
    model = og.Model(model_path)
    inputs = model.create_multimodal_processor()(prompt, audios=audios)
    return model, inputs


def _placeholder_runs(input_ids: np.ndarray) -> list[int]:
    """Lengths of the consecutive AUDIO_TOKEN_ID runs, in order."""
    runs = []
    run = 0
    for token in input_ids:
        if token == AUDIO_TOKEN_ID:
            run += 1
        elif run:
            runs.append(run)
            run = 0
    if run:
        runs.append(run)
    return runs


def test_lfm2_audio_processor_single_clip(test_data_path, tmp_path):
    samples = _synthetic_signal(1.3)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    prompt = f"<|startoftext|><|im_start|>user\n{AUDIO_MARKER}<|im_end|>\n<|im_start|>assistant\n"
    model, inputs = _process(_model_path(test_data_path), prompt, og.Audios.open(clip))
    tokenizer = og.Tokenizer(model)

    # Same token stream as liquid-audio's ChatState: the text on either side of the clip is tokenized
    # on its own and one placeholder per encoder frame sits between.
    num_frames = _num_frames(len(samples))
    expected_ids = (
        tokenizer.encode("<|startoftext|><|im_start|>user\n").tolist()
        + [AUDIO_TOKEN_ID] * _num_tokens(len(samples))
        + tokenizer.encode("<|im_end|>\n<|im_start|>assistant\n").tolist()
    )
    input_ids = inputs["input_ids"].as_numpy()
    assert input_ids.shape == (1, len(expected_ids))
    assert input_ids[0].tolist() == expected_ids

    mel = inputs["audio_embeds"].as_numpy()
    assert mel.shape == (1, num_frames, NUM_MELS)
    assert mel.dtype == np.float32
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [num_frames])
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [_num_tokens(len(samples))])


def test_lfm2_audio_processor_text_only(test_data_path):
    _, inputs = _process(_model_path(test_data_path), "<|startoftext|>Just text.", None)
    assert AUDIO_TOKEN_ID not in inputs["input_ids"].as_numpy()
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [0])
    with pytest.raises(RuntimeError, match="audio_embeds"):
        _ = inputs["audio_embeds"]


def test_lfm2_audio_processor_two_clips_of_different_lengths(test_data_path, tmp_path):
    short = _synthetic_signal(0.5, seed=1)
    long = _synthetic_signal(1.7, seed=2)
    clips = [_write_wav(tmp_path / "short.wav", short), _write_wav(tmp_path / "long.wav", long)]
    prompt = f"First {AUDIO_MARKER} then {AUDIO_MARKER} done"
    _, inputs = _process(_model_path(test_data_path), prompt, og.Audios.open(*clips))

    # Clips are staged as one zero-padded tensor, each with its real length, in prompt order; the
    # placeholders follow the same order. The encoder itself runs once per clip on those lengths.
    assert _placeholder_runs(inputs["input_ids"].as_numpy()[0]) == [_num_tokens(len(short)), _num_tokens(len(long))]
    mel = inputs["audio_embeds"].as_numpy()
    assert mel.shape == (2, _num_frames(len(long)), NUM_MELS)
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [_num_frames(len(short)), _num_frames(len(long))])
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [_num_tokens(len(short)), _num_tokens(len(long))])
    assert np.all(mel[0, _num_frames(len(short)) :] == 0)
    np.testing.assert_allclose(mel[0, : _num_frames(len(short))], _reference_mel(short), atol=2e-3)
    np.testing.assert_allclose(mel[1], _reference_mel(long), atol=2e-3)


@pytest.mark.parametrize(
    "prompt,num_clips,expected",
    [
        ("No marker here", 1, "contains 0 <|audio|> markers but 1 audio clips"),
        (f"{AUDIO_MARKER} twice {AUDIO_MARKER}", 1, "contains 2 <|audio|> markers but 1 audio clips"),
        (f"marker without a clip {AUDIO_MARKER}", 0, "contains 1 <|audio|> markers but 0 audio clips"),
    ],
)
def test_lfm2_audio_rejects_marker_count_mismatch(test_data_path, tmp_path, prompt, num_clips, expected):
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(0.4, seed=i)) for i in range(num_clips)]
    audios = og.Audios.open(*clips) if clips else None
    with pytest.raises(RuntimeError, match=expected):
        _process(_model_path(test_data_path), prompt, audios)


def test_lfm2_audio_open_bytes_matches_open(test_data_path, tmp_path):
    clip = Path(_write_wav(tmp_path / "clip.wav", _synthetic_signal(0.9, seed=7)))
    model = og.Model(_model_path(test_data_path))
    processor = model.create_multimodal_processor()

    from_path = processor(AUDIO_MARKER, audios=og.Audios.open(os.fspath(clip)))
    from_bytes = processor(AUDIO_MARKER, audios=og.Audios.open_bytes(clip.read_bytes()))

    np.testing.assert_array_equal(from_bytes["input_ids"].as_numpy(), from_path["input_ids"].as_numpy())
    np.testing.assert_array_equal(from_bytes["audio_embeds"].as_numpy(), from_path["audio_embeds"].as_numpy())
    np.testing.assert_array_equal(from_bytes["audio_sizes"].as_numpy(), from_path["audio_sizes"].as_numpy())


@pytest.mark.parametrize("source_rate", [22050, 44100, 48000])
def test_lfm2_audio_resamples_to_the_encoder_rate(test_data_path, tmp_path, source_rate):
    # Whatever the file's rate, the clip reaches the mel front end at the encoder's 16 kHz, so the
    # frame count follows the resampled length rather than the original sample count.
    seconds = 0.75
    samples = _synthetic_signal(seconds, seed=8)[: int(seconds * source_rate)]
    if source_rate > SAMPLE_RATE:  # _synthetic_signal only makes 16 kHz worth of samples
        samples = np.interp(
            np.linspace(0, 1, int(seconds * source_rate)), np.linspace(0, 1, samples.size), samples
        ).astype(np.float32)
    clip = _write_wav(tmp_path / "clip.wav", samples, sample_rate=source_rate)

    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))

    resampled_length = round(samples.size * SAMPLE_RATE / source_rate)
    num_frames = int(inputs["audio_lengths"].as_numpy()[0])
    # The resampler may land a sample either side of the exact ratio, so allow one hop of slack.
    assert abs(num_frames - _num_frames(resampled_length)) <= 1, f"{num_frames} frames for {resampled_length} samples"
    assert inputs["audio_embeds"].as_numpy().shape == (1, num_frames, NUM_MELS)
    assert int(inputs["audio_sizes"].as_numpy()[0]) == math.ceil(num_frames / SUBSAMPLING_FACTOR)


def test_lfm2_audio_rejects_a_clip_recorded_below_the_encoder_rate(test_data_path, tmp_path):
    # The decoder resamples downwards only, so 8 kHz telephone audio cannot be read as 16 kHz. The
    # message has to name the clip and say what to do, not just repeat the decoder's complaint.
    clip = _write_wav(tmp_path / "telephone.wav", _synthetic_signal(0.5, seed=11)[:4000], sample_rate=8000)
    with pytest.raises(RuntimeError, match="could not decode audio clip 0 at 16000 Hz.*resampled up"):
        _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))


@pytest.mark.parametrize(
    "field,value",
    [("hop_length", 320), ("win_length", 320), ("fft_size", 1024), ("num_mels", 64), ("sample_rate", 8000)],
)
def test_lfm2_audio_honors_the_mel_config_overrides(test_data_path, tmp_path, field, value):
    # The front end defaults to the published checkpoints' settings, and genai_config.json can
    # override each one; a fine-tune that changed them would otherwise be silently mis-framed.
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({field: value}))
    samples = _synthetic_signal(1.0, seed=9)
    clip = _write_wav(tmp_path / "clip.wav", samples)

    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()

    expected_mels = value if field == "num_mels" else NUM_MELS
    expected_hop = value if field == "hop_length" else HOP_LENGTH
    # A different sample rate resamples the clip instead of changing the framing arithmetic.
    expected_samples = len(samples) * value // SAMPLE_RATE if field == "sample_rate" else len(samples)
    expected_frames = expected_samples // expected_hop + 1

    assert mel.shape[2] == expected_mels
    assert abs(mel.shape[1] - expected_frames) <= 1, f"{mel.shape[1]} frames, expected about {expected_frames}"
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [mel.shape[1]])


def test_lfm2_audio_subsampling_factor_override_changes_the_placeholder_count(test_data_path, tmp_path):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({"subsampling_factor": 4}))
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(1.0, seed=10))

    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))

    num_frames = int(inputs["audio_lengths"].as_numpy()[0])
    assert int(inputs["audio_sizes"].as_numpy()[0]) == math.ceil(num_frames / 4)
    assert _placeholder_runs(inputs["input_ids"].as_numpy()[0]) == [math.ceil(num_frames / 4)]


def test_lfm2_audio_rejects_a_clip_too_short_to_normalize(test_data_path, tmp_path):
    # Per-feature normalization needs two valid frames (num_samples // hop >= 2).
    clip = _write_wav(tmp_path / "blip.wav", _synthetic_signal(0.015))
    with pytest.raises(RuntimeError, match="too short"):
        _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))


def test_lfm2_audio_single_prompt_list_matches_the_string_form(test_data_path, tmp_path):
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.6))
    model = og.Model(_model_path(test_data_path))
    processor = model.create_multimodal_processor()
    prompt = f"Transcribe {AUDIO_MARKER}"
    from_string = processor(prompt, audios=og.Audios.open(clip))
    from_list = processor([prompt], audios=og.Audios.open(clip))
    np.testing.assert_array_equal(from_list["input_ids"].as_numpy(), from_string["input_ids"].as_numpy())
    np.testing.assert_array_equal(from_list["audio_embeds"].as_numpy(), from_string["audio_embeds"].as_numpy())


def test_lfm2_audio_rejects_batched_prompts(test_data_path):
    model = og.Model(_model_path(test_data_path))
    with pytest.raises(RuntimeError, match="batched prompts are not supported"):
        model.create_multimodal_processor()(["one", "two"], audios=None)


def test_lfm2_audio_mel_matches_reference(test_data_path, tmp_path):
    samples = _synthetic_signal(2.0, seed=3)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()[0]

    reference = _reference_mel(samples)
    assert mel.shape == reference.shape
    np.testing.assert_allclose(mel, reference, atol=2e-3)
    # NeMo counts one frame fewer than the STFT produces; that last frame is zeroed but still fed.
    assert np.all(mel[-1] == 0)
    assert np.any(mel[-2] != 0)


def test_lfm2_audio_downmixes_stereo_to_mono(test_data_path, tmp_path):
    samples = _synthetic_signal(0.8, seed=4)
    mono = _write_wav(tmp_path / "mono.wav", samples)
    stereo = _write_wav(tmp_path / "stereo.wav", samples, channels=2)
    model_path = _model_path(test_data_path)
    _, from_mono = _process(model_path, AUDIO_MARKER, og.Audios.open(mono))
    _, from_stereo = _process(model_path, AUDIO_MARKER, og.Audios.open(stereo))
    np.testing.assert_allclose(from_stereo["audio_embeds"].as_numpy(), from_mono["audio_embeds"].as_numpy(), atol=1e-4)


def test_lfm2_audio_mel_matches_liquid_audio(test_data_path, tmp_path):
    """The reference implementation itself, when the liquid-audio package is installed."""
    torch = pytest.importorskip("torch")
    processor_module = pytest.importorskip("liquid_audio.model.conformer.processor")
    reference_processor = processor_module.AudioToMelSpectrogramPreprocessor(**PREPROCESSOR_CONFIG).eval()

    samples = _synthetic_signal(1.5, seed=5)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()[0]

    with torch.no_grad():
        wave_tensor = torch.from_numpy(samples)[None, :]
        reference, _ = reference_processor(wave_tensor, torch.tensor([wave_tensor.shape[1]]))
    np.testing.assert_allclose(mel, reference[0].T.numpy(), atol=2e-3)


def test_lfm2_audio_casts_mel_to_the_speech_input_type(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_path = _copy_model(test_data_path, tmp_path)
    speech_path = model_path / "dummy_speech.onnx"
    speech = onnx.load(speech_path)
    # Take mel_spectrogram as float16 and cast it back to float32 for the rest of the graph.
    speech.graph.input[0].type.tensor_type.elem_type = onnx.TensorProto.FLOAT16
    for node in speech.graph.node:
        node.input[:] = ["mel_spectrogram_fp16" if name == "mel_spectrogram" else name for name in node.input]
    speech.graph.node.insert(
        0, onnx.helper.make_node("Cast", ["mel_spectrogram"], ["mel_spectrogram_fp16"], to=onnx.TensorProto.FLOAT)
    )
    onnx.save(speech, speech_path)

    samples = _synthetic_signal(0.7, seed=6)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()
    assert mel.dtype == np.float16
    np.testing.assert_allclose(mel[0].astype(np.float32), _reference_mel(samples), atol=2e-2)

    # And the fp16 features still flow through generation.
    generator, _ = _generate(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip), num_tokens=2)
    assert len(generator.get_sequence(0)) == mel.shape[1] // SUBSAMPLING_FACTOR + 1 + 2


@pytest.mark.parametrize("field", ["audio_embeds", "audio_lengths"])
def test_lfm2_audio_rejects_speech_input_name_missing_from_the_graph(test_data_path, tmp_path, field):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(
        model_path / "genai_config.json", lambda config: config["model"]["speech"]["inputs"].update({field: "nope"})
    )
    with pytest.raises(RuntimeError, match=f'no input named "nope".*model.speech.inputs.{field}'):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def test_lfm2_audio_rejects_non_int64_lengths(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_path = _copy_model(test_data_path, tmp_path)
    speech_path = model_path / "dummy_speech.onnx"
    speech = onnx.load(speech_path)
    # Take mel_lengths as int32 and widen it for the rest of the graph.
    speech.graph.input[1].type.tensor_type.elem_type = onnx.TensorProto.INT32
    for node in speech.graph.node:
        node.input[:] = ["mel_lengths_i64" if name == "mel_lengths" else name for name in node.input]
    speech.graph.node.insert(
        0, onnx.helper.make_node("Cast", ["mel_lengths"], ["mel_lengths_i64"], to=onnx.TensorProto.INT64)
    )
    onnx.save(speech, speech_path)
    with pytest.raises(RuntimeError, match='"mel_lengths" must be int64, got int32'):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def test_lfm2_audio_requires_audio_token_id(test_data_path, tmp_path):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].pop("audio_token_id"))
    with pytest.raises(RuntimeError, match="audio_token_id must be set"):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def _generate(model_path: str, prompt: str, audios, num_tokens: int, chunk_size: int | None = None):
    model = og.Model(model_path)
    processor = model.create_multimodal_processor()
    params = og.GeneratorParams(model)
    options = {"do_sample": False, "max_length": 4096}
    if chunk_size is not None:
        options["chunk_size"] = chunk_size
    params.set_search_options(**options)

    inputs = processor(prompt, audios=audios)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    for _ in range(num_tokens):
        generator.generate_next_token()
    return generator, inputs


def _reference_generation(model_path: str, inputs, num_tokens: int) -> np.ndarray:
    """Greedy generation replayed with plain ONNX Runtime.

    Runs the speech model once per clip on that clip's own frames — the padding never reaches the
    encoder, which is what the runtime does and what the published encoder export requires — then
    scatters the concatenated features through the embedding model, and finally one decoder run per
    token carrying the KV cache and conv state by hand.
    """
    ort = pytest.importorskip("onnxruntime")
    config = json.loads((Path(model_path) / "genai_config.json").read_text())["model"]
    decoder_config = config["decoder"]
    speech = ort.InferenceSession(os.path.join(model_path, config["speech"]["filename"]))
    embedding = ort.InferenceSession(os.path.join(model_path, config["embedding"]["filename"]))
    decoder = ort.InferenceSession(os.path.join(model_path, decoder_config["filename"]))
    output_names = [output.name for output in decoder.get_outputs()]
    hidden_size = decoder_config["hidden_size"]

    input_ids = inputs["input_ids"].as_numpy()[0]
    tokens_per_clip = inputs["audio_sizes"].as_numpy()
    if tokens_per_clip.sum() > 0:
        mel = inputs["audio_embeds"].as_numpy()
        frames_per_clip = inputs["audio_lengths"].as_numpy()
        per_clip = [
            speech.run(None, {"mel_spectrogram": mel[i : i + 1, :frames], "mel_lengths": frames_per_clip[i : i + 1]})[
                0
            ][0]
            for i, frames in enumerate(frames_per_clip)
        ]
        audio_features = np.concatenate(
            [features[:count] for features, count in zip(per_clip, tokens_per_clip, strict=True)]
        )
    else:
        audio_features = np.zeros((0, hidden_size), np.float32)

    state = {}
    for layer, layer_type in enumerate(decoder_config["layer_types"]):
        if layer_type == "conv":
            state[f"past.{layer}.conv"] = np.zeros((1, hidden_size, decoder_config["conv_cache_size"]), np.float32)
        else:
            for kind in ("key", "value"):
                state[f"past_key_values.{layer}.{kind}"] = np.zeros(
                    (1, decoder_config["num_key_value_heads"], 0, decoder_config["head_size"]), np.float32
                )

    sequence = [int(token) for token in input_ids]
    step_ids = sequence
    for _ in range(num_tokens):
        embeds = embedding.run(
            None, {"input_ids": np.array([step_ids], dtype=np.int64), "audio_features": audio_features}
        )[0]
        feeds = {"inputs_embeds": embeds, "attention_mask": np.ones((1, len(sequence)), np.int64), **state}
        outputs = dict(zip(output_names, decoder.run(None, feeds), strict=True))
        for name in state:
            state[name] = outputs[name.replace("past_key_values.", "present.").replace("past.", "present.")]
        next_token = int(outputs["logits"][0, -1].argmax())
        sequence.append(next_token)
        step_ids = [next_token]
        audio_features = np.zeros((0, hidden_size), np.float32)
    return np.array(sequence, dtype=np.int32)


@pytest.mark.parametrize(
    "num_clips,chunk_size",
    [(0, None), (0, 3), (1, None), (1, 3), (1, 10), (2, None), (2, 5)],
    ids=["text", "text-chunk3", "audio", "audio-chunk3", "audio-chunk10", "two-clips", "two-clips-chunk5"],
)
def test_lfm2_audio_generation_matches_onnxruntime_reference(test_data_path, tmp_path, num_clips, chunk_size):
    # The decoder's logits read the conv state over the last few embeddings, so the prompt ends with
    # the audio: the first generated tokens depend on the scattered features, and the runtime only
    # matches the hand-carried reference if it passes both the features and the conv state along,
    # including across prefill chunk boundaries. The clips run longest first, so the last one is the
    # one the mel batch pads: feeding the encoder that padding instead of the clip's own frames
    # changes its final feature, and with it the first token generated.
    model_path = _model_path(test_data_path)
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.7 - 0.7 * i, seed=10 + i)) for i in range(num_clips)]
    prompt = "<|startoftext|>Transcribe the following. " + " and ".join([AUDIO_MARKER] * num_clips)
    num_tokens = 6

    generator, inputs = _generate(model_path, prompt, og.Audios.open(*clips) if clips else None, num_tokens, chunk_size)
    input_ids = inputs["input_ids"].as_numpy()[0]
    assert chunk_size is None or len(input_ids) > chunk_size, "the prompt must span several chunks"

    np.testing.assert_array_equal(generator.get_sequence(0), _reference_generation(model_path, inputs, num_tokens))


def test_lfm2_audio_generation_depends_on_the_audio(test_data_path, tmp_path):
    model_path = _model_path(test_data_path)
    outputs = []
    for seed in (20, 21):
        clip = _write_wav(tmp_path / f"{seed}.wav", _synthetic_signal(0.5, seed=seed))
        generator, inputs = _generate(model_path, f"<|startoftext|>{AUDIO_MARKER}", og.Audios.open(clip), num_tokens=4)
        outputs.append(generator.get_sequence(0)[len(inputs["input_ids"].as_numpy()[0]) :].tolist())
    assert outputs[0] != outputs[1], "two different clips must not decode to the same tokens"


def test_lfm2_audio_features_follow_the_clip_order(test_data_path, tmp_path):
    # Two clips of the same length, so a swapped concatenation would still have the right shape.
    model_path = _model_path(test_data_path)
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.0, seed=30 + i)) for i in range(2)]
    prompt = "<|startoftext|>Compare {} and {}"

    outputs = []
    for order in (clips, clips[::-1]):
        generator, inputs = _generate(
            model_path, prompt.format(AUDIO_MARKER, AUDIO_MARKER), og.Audios.open(*order), num_tokens=4
        )
        start = len(inputs["input_ids"].as_numpy()[0])
        outputs.append(generator.get_sequence(0)[start:].tolist())
    assert outputs[0] != outputs[1], "swapping the clips must change what the decoder sees"


def _generate_with_eos(model_path, clip, eos, num_tokens):
    model = og.Model(os.fspath(model_path))
    processor = model.create_multimodal_processor()
    inputs = processor(AUDIO_MARKER, audios=og.Audios.open(clip))
    prompt_length = inputs["input_ids"].as_numpy().shape[1]
    params = og.GeneratorParams(model)
    params.set_search_options(do_sample=False, max_length=prompt_length + num_tokens)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    generated = []
    while not generator.is_done():
        generator.generate_next_token()
        generated.append(int(generator.get_next_tokens()[0]))
    return generated


def test_lfm2_audio_generation_stops_when_the_model_starts_speaking(test_data_path, tmp_path):
    # Everything the model emits after <|audio_start|> is audio codes for a depthformer this runtime
    # does not have, so the builder puts that token in eos_token_id and generation has to end on it.
    # The fixture decoder never emits 128 on its own, so this pins the mechanism on a token it does
    # emit: whichever id is named as the audio stop, the run ends at its first occurrence.
    model_path = _copy_model(test_data_path, tmp_path)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=40))

    unrestricted = _generate_with_eos(model_path, clip, [7], num_tokens=40)
    assert len(unrestricted) == 40, "the fixture should run to max_length without a stop token"

    stop_token = unrestricted[5]
    first = unrestricted.index(stop_token)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({"eos_token_id": [stop_token]}))

    stopped = _generate_with_eos(model_path, clip, [stop_token], num_tokens=40)

    assert stopped == unrestricted[: first + 1], "generation must end at the stop token, with nothing after it"


def test_lfm2_audio_audio_start_in_eos_leaves_normal_stopping_alone(test_data_path, tmp_path):
    # Adding <|audio_start|> alongside <|im_end|> must not change a run that never starts speaking.
    model_path = _copy_model(test_data_path, tmp_path)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=41))

    without = _generate_with_eos(model_path, clip, [7], num_tokens=25)
    _edit_json(
        model_path / "genai_config.json",
        lambda config: config["model"].update({"eos_token_id": [7, AUDIO_START_TOKEN_ID]}),
    )
    with_audio_stop = _generate_with_eos(model_path, clip, [7, AUDIO_START_TOKEN_ID], num_tokens=25)

    assert AUDIO_START_TOKEN_ID not in without, "the fixture is not expected to emit <|audio_start|>"
    assert with_audio_stop == without


def test_lfm2_audio_fixture_config_is_what_the_builder_writes(test_data_path):
    # The tiny model stands in for a built one; its stop tokens have to match what the builder emits
    # for these checkpoints, or the tests above would be exercising a different contract.
    config = json.loads((Path(_model_path(test_data_path)) / "genai_config.json").read_text())
    assert config["model"]["type"] == "lfm2_audio"
    assert config["model"]["audio_token_id"] == AUDIO_TOKEN_ID


def test_lfm2_audio_rejects_rewind(test_data_path, tmp_path):
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5))
    generator, _ = _generate(_model_path(test_data_path), f"{AUDIO_MARKER}Hi", og.Audios.open(clip), num_tokens=1)
    sequence = generator.get_sequence(0).copy()

    # The conv state cannot be rewound; the generator must refuse before touching the sequence.
    with pytest.raises(RuntimeError, match="RewindTo is currently not supported for lfm2_audio"):
        generator.rewind_to(0)
    np.testing.assert_array_equal(generator.get_sequence(0), sequence)
