# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License

"""
Tests for the LFM2-Audio pipeline against the tiny models in test/models/lfm2-audio.

The models are generated by test/python/create/create_dummy_lfm2_audio_models.py, and the tokenizer
is checked in zipped alongside them, so `_model_path` assembles a runnable model directory in a
temporary directory once per session. The speech model
emits one feature per 8 mel frames, the embedding model scatters those features over the placeholders
the processor writes, and the decoder's logits depend on the conv state, so generation only succeeds,
and only matches between runs, when the processor, the speech/embedding hand-off and the conv state
cache agree.

Run with:
    python -m pytest test/python/models/test_lfm2_audio_models.py --test_models test/models
"""

from __future__ import annotations

import json
import math
import os
import shutil
import tempfile
import wave
import zipfile
from pathlib import Path

import numpy as np
import onnxruntime_genai as og
import pytest

AUDIO_MARKER = "<|audio|>"
AUDIO_START_TOKEN_ID = 128  # <|audio_start|>: the answer is spoken from here on
TEXT_END_TOKEN_ID = 130  # <|text_end|>: the text half of an interleaved answer is over
AUDIO_TOKEN_ID = 133  # <|reserved_123|>, model.audio_token_id in the fixture's genai_config.json
NUM_MELS = 128
SAMPLE_RATE = 16000
FFT_SIZE = 512
WIN_LENGTH = 400
HOP_LENGTH = 160
SUBSAMPLING_FACTOR = 8
LOG_EPS = 2.0**-24
NORM_EPS = 1e-5
# Settings of LiquidAI/LFM2-Audio-1.5B and LFM2.5-Audio-1.5B (config.json "preprocessor").
PREPROCESSOR_CONFIG = {
    "sample_rate": SAMPLE_RATE,
    "normalize": "per_feature",
    "window_size": 0.025,
    "window_stride": 0.01,
    "window": "hann",
    "features": NUM_MELS,
    "n_fft": FFT_SIZE,
    "log": True,
    "frame_splicing": 1,
    "dither": 1.0e-05,
    "pad_to": 0,
    "pad_value": 0.0,
}


# The tokenizer is checked in zipped: its 4.8 MB of vocabulary compresses to under 1 MB, and no test
# reads it as text. The files come from LiquidAI/LFM2.5-Audio-1.5B; _write_tokenizer_archive rebuilds it.
TOKENIZER_ARCHIVE = "tokenizer.zip"
TOKENIZER_FILES = ("tokenizer.json", "tokenizer_config.json")


def _write_tokenizer_archive(directory: Path, archive_path: Path):
    """Zips the tokenizer files in `directory`, with the timestamp and mode pinned so that refreshing
    the archive from the same files does not show up as a changed binary."""
    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name in TOKENIZER_FILES:
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, (directory / name).read_bytes(), compresslevel=9)


# One assembled directory per source, kept alive (and so undeleted) for the whole session.
_MODEL_DIRECTORIES: dict[str, tempfile.TemporaryDirectory] = {}


def _model_path(test_data_path) -> str:
    """The fixture model directory, with the tokenizer unpacked, assembled once per session.

    Everything the runtime loads has to sit in one directory, so the ONNX models and the config are
    copied next to the unpacked tokenizer rather than the archive being unpacked over the checkout.
    """
    source = Path(test_data_path) / "lfm2-audio"
    if not (source / "genai_config.json").exists():
        pytest.skip(f"LFM2-Audio test model not found at {source}")

    key = os.fspath(source)
    if key not in _MODEL_DIRECTORIES:
        holder = tempfile.TemporaryDirectory(prefix="lfm2-audio-")
        destination = Path(holder.name)
        for item in source.iterdir():
            if item.is_file() and item.name != TOKENIZER_ARCHIVE:
                shutil.copy(item, destination)
        with zipfile.ZipFile(source / TOKENIZER_ARCHIVE) as archive:
            # Named rather than extractall: the archive holds exactly these two files, and naming
            # them keeps a stray path in the archive from landing outside the directory.
            for name in TOKENIZER_FILES:
                (destination / name).write_bytes(archive.read(name))
        _MODEL_DIRECTORIES[key] = holder
    return _MODEL_DIRECTORIES[key].name


def test_lfm2_audio_tokenizer_archive_can_be_rebuilt(test_data_path, tmp_path):
    # Rebuilding from the unpacked files gives the same archive every time, holding what is checked in.
    unpacked = Path(_model_path(test_data_path))
    _write_tokenizer_archive(unpacked, tmp_path / "first.zip")
    _write_tokenizer_archive(unpacked, tmp_path / "second.zip")

    assert (tmp_path / "first.zip").read_bytes() == (tmp_path / "second.zip").read_bytes()
    with (
        zipfile.ZipFile(tmp_path / "first.zip") as rebuilt,
        zipfile.ZipFile(Path(test_data_path) / "lfm2-audio" / TOKENIZER_ARCHIVE) as checked_in,
    ):
        assert rebuilt.namelist() == checked_in.namelist() == list(TOKENIZER_FILES)
        for name in TOKENIZER_FILES:
            assert rebuilt.read(name) == checked_in.read(name)
            assert rebuilt.getinfo(name).date_time == checked_in.getinfo(name).date_time


def _copy_model(test_data_path, tmp_path) -> Path:
    destination = tmp_path / "lfm2-audio"
    shutil.copytree(_model_path(test_data_path), destination)
    return destination


def _edit_json(path: Path, edit):
    config = json.loads(path.read_text())
    edit(config)
    path.write_text(json.dumps(config))


def _synthetic_signal(seconds: float, seed: int = 0) -> np.ndarray:
    """A few tones plus noise, quantized to 16-bit like the WAV that carries it."""
    rng = np.random.default_rng(seed)
    t = np.arange(int(seconds * SAMPLE_RATE)) / SAMPLE_RATE
    signal = 0.3 * np.sin(2 * np.pi * 440 * t) + 0.1 * np.sin(2 * np.pi * 3000 * t) + 0.05 * rng.standard_normal(t.size)
    return np.round(np.clip(signal, -1, 1) * 32767).astype(np.int16).astype(np.float32) / 32768.0


def _write_wav(path: Path, samples: np.ndarray, sample_rate: int = SAMPLE_RATE, channels: int = 1) -> str:
    pcm = np.round(samples * 32768.0).clip(-32768, 32767).astype("<i2")
    if channels > 1:
        pcm = np.repeat(pcm[:, None], channels, axis=1)
    with wave.open(os.fspath(path), "wb") as handle:
        handle.setnchannels(channels)
        handle.setsampwidth(2)
        handle.setframerate(sample_rate)
        handle.writeframes(pcm.tobytes())
    return os.fspath(path)


def _num_frames(num_samples: int) -> int:
    # torch.stft(center=True): one frame per hop plus one.
    return num_samples // HOP_LENGTH + 1


def _num_tokens(num_samples: int) -> int:
    return math.ceil(_num_frames(num_samples) / SUBSAMPLING_FACTOR)


def _slaney_mel_filterbank() -> np.ndarray:
    """librosa.filters.mel(sr, n_fft, n_mels, fmin=0, fmax=sr/2, norm="slaney") without librosa."""

    def hz_to_mel(hz):
        hz = np.asarray(hz, dtype=np.float64)
        mel = hz / (200.0 / 3)
        log_region = hz >= 1000.0
        mel[log_region] = 15.0 + np.log(hz[log_region] / 1000.0) / (np.log(6.4) / 27.0)
        return mel

    def mel_to_hz(mel):
        mel = np.asarray(mel, dtype=np.float64)
        hz = mel * (200.0 / 3)
        log_region = mel >= 15.0
        hz[log_region] = 1000.0 * np.exp((np.log(6.4) / 27.0) * (mel[log_region] - 15.0))
        return hz

    fft_freqs = np.linspace(0, SAMPLE_RATE / 2, FFT_SIZE // 2 + 1)
    mel_points = mel_to_hz(np.linspace(hz_to_mel([0.0])[0], hz_to_mel([SAMPLE_RATE / 2])[0], NUM_MELS + 2))
    fdiff = np.diff(mel_points)
    ramps = mel_points[:, None] - fft_freqs[None, :]
    weights = np.maximum(0, np.minimum(-ramps[:-2] / fdiff[:-1, None], ramps[2:] / fdiff[1:, None]))
    weights *= (2.0 / (mel_points[2 : NUM_MELS + 2] - mel_points[:NUM_MELS]))[:, None]
    return weights.astype(np.float32)


def _reference_mel(
    samples: np.ndarray, preemph: float = 0.97, log_eps: float = LOG_EPS, norm_eps: float = NORM_EPS
) -> np.ndarray:
    """NeMo's AudioToMelSpectrogramPreprocessor in eval mode, as liquid-audio ships it, in numpy.

    Pre-emphasis, constant center padding, symmetric Hann window, power spectrum, Slaney mel filter
    bank, log with the 2^-24 guard, then per-feature normalization over the num_samples // hop
    frames get_seq_len counts as valid, with the frames past that zeroed.
    """
    preemphasized = np.concatenate([samples[:1], samples[1:] - preemph * samples[:-1]])
    padded = np.pad(preemphasized, FFT_SIZE // 2)
    num_frames = _num_frames(len(samples))
    window = np.zeros(FFT_SIZE, np.float64)
    window[(FFT_SIZE - WIN_LENGTH) // 2 :][:WIN_LENGTH] = 0.5 * (
        1 - np.cos(2 * np.pi * np.arange(WIN_LENGTH) / (WIN_LENGTH - 1))
    )
    frames = np.stack([padded[t * HOP_LENGTH : t * HOP_LENGTH + FFT_SIZE] * window for t in range(num_frames)])
    power = np.abs(np.fft.rfft(frames, axis=1)) ** 2
    log_mel = np.log(power @ _slaney_mel_filterbank().T.astype(np.float64) + log_eps)

    valid = len(samples) // HOP_LENGTH
    mean = log_mel[:valid].mean(axis=0)
    std = np.sqrt(((log_mel[:valid] - mean) ** 2).sum(axis=0) / (valid - 1)) + norm_eps
    normalized = (log_mel - mean) / std
    normalized[valid:] = 0.0
    return normalized.astype(np.float32)


def _reference_resample(samples: np.ndarray, source_rate: int, target_rate: int = SAMPLE_RATE) -> np.ndarray:
    """torchaudio.functional.resample with its defaults, which liquid-audio's ChatState.add_audio uses.

    A Hann-windowed sinc with lowpass_filter_width 6 and rolloff 0.99: one kernel per output phase,
    built in float64 and applied in float32, strided over the zero-padded input.
    """
    if source_rate == target_rate:
        return samples
    divisor = math.gcd(source_rate, target_rate)
    orig, new = source_rate // divisor, target_rate // divisor
    base_freq = min(orig, new) * 0.99
    width = math.ceil(6 * orig / base_freq)
    idx = np.arange(-width, width + orig, dtype=np.float64) / orig
    t = (np.arange(0, -new, -1, dtype=np.float64)[:, None] / new + idx[None, :]) * base_freq
    t = t.clip(-6, 6)
    window = np.cos(t * np.pi / 6 / 2) ** 2
    t *= np.pi
    kernels = (np.where(t == 0, 1.0, np.sin(t) / np.where(t == 0, 1.0, t)) * window * base_freq / orig).astype(
        np.float32
    )

    padded = np.pad(samples.astype(np.float32), (width, width + orig))
    steps = len(samples) // orig + 1
    frames = np.lib.stride_tricks.sliding_window_view(padded, 2 * width + orig)[::orig][:steps]
    return (frames @ kernels.T).reshape(-1)[: math.ceil(new * len(samples) / orig)]


def _process(model_path: str, prompt: str, audios):
    model = og.Model(model_path)
    inputs = model.create_multimodal_processor()(prompt, audios=audios)
    return model, inputs


def _placeholder_runs(input_ids: np.ndarray) -> list[int]:
    """Lengths of the consecutive AUDIO_TOKEN_ID runs, in order."""
    runs = []
    run = 0
    for token in input_ids:
        if token == AUDIO_TOKEN_ID:
            run += 1
        elif run:
            runs.append(run)
            run = 0
    if run:
        runs.append(run)
    return runs


def test_lfm2_audio_processor_single_clip(test_data_path, tmp_path):
    samples = _synthetic_signal(1.3)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    prompt = f"<|startoftext|><|im_start|>user\n{AUDIO_MARKER}<|im_end|>\n<|im_start|>assistant\n"
    model, inputs = _process(_model_path(test_data_path), prompt, og.Audios.open(clip))
    tokenizer = og.Tokenizer(model)

    # Same token stream as liquid-audio's ChatState: the text on either side of the clip is tokenized
    # on its own and one placeholder per encoder frame sits between.
    num_frames = _num_frames(len(samples))
    expected_ids = (
        tokenizer.encode("<|startoftext|><|im_start|>user\n").tolist()
        + [AUDIO_TOKEN_ID] * _num_tokens(len(samples))
        + tokenizer.encode("<|im_end|>\n<|im_start|>assistant\n").tolist()
    )
    input_ids = inputs["input_ids"].as_numpy()
    assert input_ids.shape == (1, len(expected_ids))
    assert input_ids[0].tolist() == expected_ids

    mel = inputs["audio_embeds"].as_numpy()
    assert mel.shape == (1, num_frames, NUM_MELS)
    assert mel.dtype == np.float32
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [num_frames])
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [_num_tokens(len(samples))])


def test_lfm2_audio_processor_text_only(test_data_path):
    _, inputs = _process(_model_path(test_data_path), "<|startoftext|>Just text.", None)
    assert AUDIO_TOKEN_ID not in inputs["input_ids"].as_numpy()
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [0])
    with pytest.raises(RuntimeError, match="audio_embeds"):
        _ = inputs["audio_embeds"]


def test_lfm2_audio_processor_two_clips_of_different_lengths(test_data_path, tmp_path):
    short = _synthetic_signal(0.5, seed=1)
    long = _synthetic_signal(1.7, seed=2)
    clips = [_write_wav(tmp_path / "short.wav", short), _write_wav(tmp_path / "long.wav", long)]
    prompt = f"First {AUDIO_MARKER} then {AUDIO_MARKER} done"
    _, inputs = _process(_model_path(test_data_path), prompt, og.Audios.open(*clips))

    # Clips are staged as one zero-padded tensor, each with its real length, in prompt order; the
    # placeholders follow the same order. The encoder itself runs once per clip on those lengths.
    assert _placeholder_runs(inputs["input_ids"].as_numpy()[0]) == [_num_tokens(len(short)), _num_tokens(len(long))]
    mel = inputs["audio_embeds"].as_numpy()
    assert mel.shape == (2, _num_frames(len(long)), NUM_MELS)
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [_num_frames(len(short)), _num_frames(len(long))])
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [_num_tokens(len(short)), _num_tokens(len(long))])
    assert np.all(mel[0, _num_frames(len(short)) :] == 0)
    np.testing.assert_allclose(mel[0, : _num_frames(len(short))], _reference_mel(short), atol=2e-3)
    np.testing.assert_allclose(mel[1], _reference_mel(long), atol=2e-3)


@pytest.mark.parametrize(
    "prompt,num_clips,expected",
    [
        ("No marker here", 1, "contains 0 <|audio|> markers but 1 audio clips"),
        (f"{AUDIO_MARKER} twice {AUDIO_MARKER}", 1, "contains 2 <|audio|> markers but 1 audio clips"),
        (f"marker without a clip {AUDIO_MARKER}", 0, "contains 1 <|audio|> markers but 0 audio clips"),
    ],
)
def test_lfm2_audio_rejects_marker_count_mismatch(test_data_path, tmp_path, prompt, num_clips, expected):
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(0.4, seed=i)) for i in range(num_clips)]
    audios = og.Audios.open(*clips) if clips else None
    with pytest.raises(RuntimeError, match=expected):
        _process(_model_path(test_data_path), prompt, audios)


def test_lfm2_audio_open_bytes_matches_open(test_data_path, tmp_path):
    clip = Path(_write_wav(tmp_path / "clip.wav", _synthetic_signal(0.9, seed=7)))
    model = og.Model(_model_path(test_data_path))
    processor = model.create_multimodal_processor()

    from_path = processor(AUDIO_MARKER, audios=og.Audios.open(os.fspath(clip)))
    from_bytes = processor(AUDIO_MARKER, audios=og.Audios.open_bytes(clip.read_bytes()))

    np.testing.assert_array_equal(from_bytes["input_ids"].as_numpy(), from_path["input_ids"].as_numpy())
    np.testing.assert_array_equal(from_bytes["audio_embeds"].as_numpy(), from_path["audio_embeds"].as_numpy())
    np.testing.assert_array_equal(from_bytes["audio_sizes"].as_numpy(), from_path["audio_sizes"].as_numpy())


def _signal_at(source_rate: int, seconds: float, seed: int) -> np.ndarray:
    """`_synthetic_signal` stretched to another rate, quantized to 16-bit like the WAV that carries it."""
    base = _synthetic_signal(seconds, seed=seed)
    stretched = np.interp(np.linspace(0, 1, int(seconds * source_rate)), np.linspace(0, 1, base.size), base)
    return (np.round(stretched * 32768.0).clip(-32768, 32767) / 32768.0).astype(np.float32)


@pytest.mark.parametrize("source_rate", [8000, 22050, 24000, 44100, 48000])
def test_lfm2_audio_resamples_the_way_the_reference_does(test_data_path, tmp_path, source_rate):
    # The clip is decoded at its own rate and brought to the encoder's 16 kHz with torchaudio's
    # resampler, upwards as well as downwards, as ChatState.add_audio does. The decoder's own
    # resampler is a different filter: near enough to transcribe, far enough to change a token.
    samples = _signal_at(source_rate, 0.75, seed=8)
    clip = _write_wav(tmp_path / "clip.wav", samples, sample_rate=source_rate)

    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))

    resampled = _reference_resample(samples, source_rate)
    assert len(resampled) == math.ceil(len(samples) * SAMPLE_RATE / source_rate)
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [_num_frames(len(resampled))])
    np.testing.assert_array_equal(inputs["audio_sizes"].as_numpy(), [_num_tokens(len(resampled))])
    np.testing.assert_allclose(inputs["audio_embeds"].as_numpy()[0], _reference_mel(resampled), atol=2e-3)


@pytest.mark.parametrize("source_rate", [8000, 44100])
def test_lfm2_audio_reference_resampler_is_torchaudio(source_rate):
    """The numpy resampler above against the real one, when torchaudio is installed."""
    torch = pytest.importorskip("torch")
    torchaudio = pytest.importorskip("torchaudio")
    samples = _signal_at(source_rate, 0.5, seed=14)

    expected = torchaudio.functional.resample(torch.from_numpy(samples)[None], source_rate, SAMPLE_RATE)[0].numpy()

    # Float32 sums taken in a different order.
    np.testing.assert_allclose(_reference_resample(samples, source_rate), expected, atol=1e-5)


@pytest.mark.parametrize(
    "field,value",
    [("hop_length", 320), ("win_length", 320), ("fft_size", 1024), ("num_mels", 64), ("sample_rate", 8000)],
)
def test_lfm2_audio_honors_the_mel_config_overrides(test_data_path, tmp_path, field, value):
    # The front end defaults to the published checkpoints' settings, and genai_config.json can
    # override each one; a fine-tune that changed them would otherwise be silently mis-framed.
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({field: value}))
    samples = _synthetic_signal(1.0, seed=9)
    clip = _write_wav(tmp_path / "clip.wav", samples)

    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()

    expected_mels = value if field == "num_mels" else NUM_MELS
    expected_hop = value if field == "hop_length" else HOP_LENGTH
    # A different sample rate resamples the clip instead of changing the framing arithmetic.
    expected_samples = len(samples) * value // SAMPLE_RATE if field == "sample_rate" else len(samples)
    expected_frames = expected_samples // expected_hop + 1

    assert mel.shape[2] == expected_mels
    assert abs(mel.shape[1] - expected_frames) <= 1, f"{mel.shape[1]} frames, expected about {expected_frames}"
    np.testing.assert_array_equal(inputs["audio_lengths"].as_numpy(), [mel.shape[1]])


@pytest.mark.parametrize(
    "field,value",
    [("preemph", 0.5), ("log_eps", 1e-4), ("norm_eps", 0.5)],
)
def test_lfm2_audio_honors_the_mel_value_overrides(test_data_path, tmp_path, field, value):
    # These three change the numbers rather than the shape, so a default silently ignoring the
    # override would look perfectly healthy. Check them against the same arithmetic done here.
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({field: value}))
    samples = _synthetic_signal(1.0, seed=12)
    clip = _write_wav(tmp_path / "clip.wav", samples)

    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()[0]

    np.testing.assert_allclose(mel, _reference_mel(samples, **{field: value}), atol=2e-3)
    # And it is genuinely a different front end from the default one.
    assert not np.allclose(mel, _reference_mel(samples), atol=2e-3)


def test_lfm2_audio_subsampling_factor_override_changes_the_placeholder_count(test_data_path, tmp_path):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({"subsampling_factor": 4}))
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(1.0, seed=10))

    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))

    num_frames = int(inputs["audio_lengths"].as_numpy()[0])
    assert int(inputs["audio_sizes"].as_numpy()[0]) == math.ceil(num_frames / 4)
    assert _placeholder_runs(inputs["input_ids"].as_numpy()[0]) == [math.ceil(num_frames / 4)]


def test_lfm2_audio_rejects_a_clip_too_short_to_normalize(test_data_path, tmp_path):
    # Per-feature normalization needs two valid frames (num_samples // hop >= 2).
    clip = _write_wav(tmp_path / "blip.wav", _synthetic_signal(0.015))
    with pytest.raises(RuntimeError, match="too short"):
        _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))


def test_lfm2_audio_single_prompt_list_matches_the_string_form(test_data_path, tmp_path):
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.6))
    model = og.Model(_model_path(test_data_path))
    processor = model.create_multimodal_processor()
    prompt = f"Transcribe {AUDIO_MARKER}"
    from_string = processor(prompt, audios=og.Audios.open(clip))
    from_list = processor([prompt], audios=og.Audios.open(clip))
    np.testing.assert_array_equal(from_list["input_ids"].as_numpy(), from_string["input_ids"].as_numpy())
    np.testing.assert_array_equal(from_list["audio_embeds"].as_numpy(), from_string["audio_embeds"].as_numpy())


def test_lfm2_audio_rejects_batched_prompts(test_data_path):
    model = og.Model(_model_path(test_data_path))
    with pytest.raises(RuntimeError, match="batched prompts are not supported"):
        model.create_multimodal_processor()(["one", "two"], audios=None)


def test_lfm2_audio_mel_matches_reference(test_data_path, tmp_path):
    samples = _synthetic_signal(2.0, seed=3)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()[0]

    reference = _reference_mel(samples)
    assert mel.shape == reference.shape
    np.testing.assert_allclose(mel, reference, atol=2e-3)
    # NeMo counts one frame fewer than the STFT produces; that last frame is zeroed but still fed.
    assert np.all(mel[-1] == 0)
    assert np.any(mel[-2] != 0)


def test_lfm2_audio_more_than_two_channels_is_not_downmixed(test_data_path, tmp_path):
    # The decoder downmixes one and two channels correctly, but deinterleaves anything wider as
    # though it were stereo, so a six channel clip arrives three times too long and garbled. Nothing
    # in the decoder's API reports the channel count, so this cannot be caught here; the tutorial
    # says to downmix first. This pins the behaviour so a fix upstream shows up as a failure here.
    samples = _synthetic_signal(0.6, seed=13)
    frames = {}
    for channels in (1, 2, 6):
        clip = _write_wav(tmp_path / f"c{channels}.wav", samples, channels=channels)
        _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))
        frames[channels] = int(inputs["audio_lengths"].as_numpy()[0])

    assert frames[2] == frames[1], "two channels are downmixed, so the clip keeps its length"
    # Compare the hops rather than the frames: every clip gets one extra frame from the centre
    # padding, so only `frames - 1` scales with the length.
    assert frames[6] - 1 == (frames[1] - 1) * 3, (
        f"six channels still arrive as {frames[6]} frames against {frames[1]}; if these now match, "
        "the decoder has learned to downmix and the tutorial's warning can go"
    )


def test_lfm2_audio_downmixes_stereo_to_mono(test_data_path, tmp_path):
    samples = _synthetic_signal(0.8, seed=4)
    mono = _write_wav(tmp_path / "mono.wav", samples)
    stereo = _write_wav(tmp_path / "stereo.wav", samples, channels=2)
    model_path = _model_path(test_data_path)
    _, from_mono = _process(model_path, AUDIO_MARKER, og.Audios.open(mono))
    _, from_stereo = _process(model_path, AUDIO_MARKER, og.Audios.open(stereo))
    np.testing.assert_allclose(from_stereo["audio_embeds"].as_numpy(), from_mono["audio_embeds"].as_numpy(), atol=1e-4)


def test_lfm2_audio_mel_matches_liquid_audio(test_data_path, tmp_path):
    """The reference implementation itself, when the liquid-audio package is installed."""
    torch = pytest.importorskip("torch")
    processor_module = pytest.importorskip("liquid_audio.model.conformer.processor")
    reference_processor = processor_module.AudioToMelSpectrogramPreprocessor(**PREPROCESSOR_CONFIG).eval()

    samples = _synthetic_signal(1.5, seed=5)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(_model_path(test_data_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()[0]

    with torch.no_grad():
        wave_tensor = torch.from_numpy(samples)[None, :]
        reference, _ = reference_processor(wave_tensor, torch.tensor([wave_tensor.shape[1]]))
    np.testing.assert_allclose(mel, reference[0].T.numpy(), atol=2e-3)


def test_lfm2_audio_casts_mel_to_the_speech_input_type(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_path = _copy_model(test_data_path, tmp_path)
    speech_path = model_path / "dummy_speech.onnx"
    speech = onnx.load(speech_path)
    # Take mel_spectrogram as float16 and cast it back to float32 for the rest of the graph.
    speech.graph.input[0].type.tensor_type.elem_type = onnx.TensorProto.FLOAT16
    for node in speech.graph.node:
        node.input[:] = ["mel_spectrogram_fp16" if name == "mel_spectrogram" else name for name in node.input]
    speech.graph.node.insert(
        0, onnx.helper.make_node("Cast", ["mel_spectrogram"], ["mel_spectrogram_fp16"], to=onnx.TensorProto.FLOAT)
    )
    onnx.save(speech, speech_path)

    samples = _synthetic_signal(0.7, seed=6)
    clip = _write_wav(tmp_path / "clip.wav", samples)
    _, inputs = _process(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip))
    mel = inputs["audio_embeds"].as_numpy()
    assert mel.dtype == np.float16
    np.testing.assert_allclose(mel[0].astype(np.float32), _reference_mel(samples), atol=2e-2)

    # And the fp16 features still flow through generation.
    generator, _ = _generate(os.fspath(model_path), AUDIO_MARKER, og.Audios.open(clip), num_tokens=2)
    assert len(generator.get_sequence(0)) == mel.shape[1] // SUBSAMPLING_FACTOR + 1 + 2


@pytest.mark.parametrize("field", ["audio_embeds", "audio_lengths"])
def test_lfm2_audio_rejects_speech_input_name_missing_from_the_graph(test_data_path, tmp_path, field):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(
        model_path / "genai_config.json", lambda config: config["model"]["speech"]["inputs"].update({field: "nope"})
    )
    with pytest.raises(RuntimeError, match=f'no input named "nope".*model.speech.inputs.{field}'):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def test_lfm2_audio_rejects_non_int64_lengths(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_path = _copy_model(test_data_path, tmp_path)
    speech_path = model_path / "dummy_speech.onnx"
    speech = onnx.load(speech_path)
    # Take mel_lengths as int32 and widen it for the rest of the graph.
    speech.graph.input[1].type.tensor_type.elem_type = onnx.TensorProto.INT32
    for node in speech.graph.node:
        node.input[:] = ["mel_lengths_i64" if name == "mel_lengths" else name for name in node.input]
    speech.graph.node.insert(
        0, onnx.helper.make_node("Cast", ["mel_lengths"], ["mel_lengths_i64"], to=onnx.TensorProto.INT64)
    )
    onnx.save(speech, speech_path)
    with pytest.raises(RuntimeError, match='"mel_lengths" must be int64, got int32'):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def test_lfm2_audio_requires_audio_token_id(test_data_path, tmp_path):
    model_path = _copy_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].pop("audio_token_id"))
    with pytest.raises(RuntimeError, match="audio_token_id must be set"):
        og.Model(os.fspath(model_path)).create_multimodal_processor()


def _generate(model_path: str, prompt: str, audios, num_tokens: int, chunk_size: int | None = None):
    model = og.Model(model_path)
    processor = model.create_multimodal_processor()
    params = og.GeneratorParams(model)
    options = {"do_sample": False, "max_length": 4096}
    if chunk_size is not None:
        options["chunk_size"] = chunk_size
    params.set_search_options(**options)

    inputs = processor(prompt, audios=audios)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    for _ in range(num_tokens):
        generator.generate_next_token()
    return generator, inputs


def _reference_generation(model_path: str, inputs, num_tokens: int) -> np.ndarray:
    """Greedy generation replayed with plain ONNX Runtime.

    Runs the speech model once per clip on that clip's own frames — the padding never reaches the
    encoder, which is what the runtime does and what the published encoder export requires — then
    scatters the concatenated features through the embedding model, and finally one decoder run per
    token carrying the KV cache and conv state by hand.
    """
    ort = pytest.importorskip("onnxruntime")
    config = json.loads((Path(model_path) / "genai_config.json").read_text())["model"]
    decoder_config = config["decoder"]
    speech = ort.InferenceSession(os.path.join(model_path, config["speech"]["filename"]))
    embedding = ort.InferenceSession(os.path.join(model_path, config["embedding"]["filename"]))
    decoder = ort.InferenceSession(os.path.join(model_path, decoder_config["filename"]))
    output_names = [output.name for output in decoder.get_outputs()]
    hidden_size = decoder_config["hidden_size"]

    input_ids = inputs["input_ids"].as_numpy()[0]
    tokens_per_clip = inputs["audio_sizes"].as_numpy()
    if tokens_per_clip.sum() > 0:
        mel = inputs["audio_embeds"].as_numpy()
        frames_per_clip = inputs["audio_lengths"].as_numpy()
        per_clip = [
            speech.run(None, {"mel_spectrogram": mel[i : i + 1, :frames], "mel_lengths": frames_per_clip[i : i + 1]})[
                0
            ][0]
            for i, frames in enumerate(frames_per_clip)
        ]
        audio_features = np.concatenate(
            [features[:count] for features, count in zip(per_clip, tokens_per_clip, strict=True)]
        )
    else:
        audio_features = np.zeros((0, hidden_size), np.float32)

    state = {}
    for layer, layer_type in enumerate(decoder_config["layer_types"]):
        if layer_type == "conv":
            state[f"past.{layer}.conv"] = np.zeros((1, hidden_size, decoder_config["conv_cache_size"]), np.float32)
        else:
            for kind in ("key", "value"):
                state[f"past_key_values.{layer}.{kind}"] = np.zeros(
                    (1, decoder_config["num_key_value_heads"], 0, decoder_config["head_size"]), np.float32
                )

    sequence = [int(token) for token in input_ids]
    step_ids = sequence
    for _ in range(num_tokens):
        embeds = embedding.run(
            None, {"input_ids": np.array([step_ids], dtype=np.int64), "audio_features": audio_features}
        )[0]
        feeds = {"inputs_embeds": embeds, "attention_mask": np.ones((1, len(sequence)), np.int64), **state}
        outputs = dict(zip(output_names, decoder.run(None, feeds), strict=True))
        for name in state:
            state[name] = outputs[name.replace("past_key_values.", "present.").replace("past.", "present.")]
        next_token = int(outputs["logits"][0, -1].argmax())
        sequence.append(next_token)
        step_ids = [next_token]
        audio_features = np.zeros((0, hidden_size), np.float32)
    return np.array(sequence, dtype=np.int32)


@pytest.mark.parametrize(
    "num_clips,chunk_size",
    [(0, None), (0, 3), (1, None), (1, 3), (1, 10), (2, None), (2, 5)],
    ids=["text", "text-chunk3", "audio", "audio-chunk3", "audio-chunk10", "two-clips", "two-clips-chunk5"],
)
def test_lfm2_audio_generation_matches_onnxruntime_reference(test_data_path, tmp_path, num_clips, chunk_size):
    # The decoder's logits read the conv state over the last few embeddings, so the prompt ends with
    # the audio: the first generated tokens depend on the scattered features, and the runtime only
    # matches the hand-carried reference if it passes both the features and the conv state along,
    # including across prefill chunk boundaries. The clips run longest first, so the last one is the
    # one the mel batch pads: feeding the encoder that padding instead of the clip's own frames
    # changes its final feature, and with it the first token generated.
    model_path = _model_path(test_data_path)
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.7 - 0.7 * i, seed=10 + i)) for i in range(num_clips)]
    prompt = "<|startoftext|>Transcribe the following. " + " and ".join([AUDIO_MARKER] * num_clips)
    num_tokens = 6

    generator, inputs = _generate(model_path, prompt, og.Audios.open(*clips) if clips else None, num_tokens, chunk_size)
    input_ids = inputs["input_ids"].as_numpy()[0]
    assert chunk_size is None or len(input_ids) > chunk_size, "the prompt must span several chunks"

    np.testing.assert_array_equal(generator.get_sequence(0), _reference_generation(model_path, inputs, num_tokens))


def test_lfm2_audio_generation_depends_on_the_audio(test_data_path, tmp_path):
    model_path = _model_path(test_data_path)
    outputs = []
    for seed in (20, 21):
        clip = _write_wav(tmp_path / f"{seed}.wav", _synthetic_signal(0.5, seed=seed))
        generator, inputs = _generate(model_path, f"<|startoftext|>{AUDIO_MARKER}", og.Audios.open(clip), num_tokens=4)
        outputs.append(generator.get_sequence(0)[len(inputs["input_ids"].as_numpy()[0]) :].tolist())
    assert outputs[0] != outputs[1], "two different clips must not decode to the same tokens"


def test_lfm2_audio_features_follow_the_clip_order(test_data_path, tmp_path):
    # Two clips of the same length, so a swapped concatenation would still have the right shape.
    model_path = _model_path(test_data_path)
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.0, seed=30 + i)) for i in range(2)]
    prompt = "<|startoftext|>Compare {} and {}"

    outputs = []
    for order in (clips, clips[::-1]):
        generator, inputs = _generate(
            model_path, prompt.format(AUDIO_MARKER, AUDIO_MARKER), og.Audios.open(*order), num_tokens=4
        )
        start = len(inputs["input_ids"].as_numpy()[0])
        outputs.append(generator.get_sequence(0)[start:].tolist())
    assert outputs[0] != outputs[1], "swapping the clips must change what the decoder sees"


def _generate_with_eos(model_path, clip, eos, num_tokens):
    """Greedy generation from a copied model directory, stopping on the token ids in `eos`."""
    _edit_json(model_path / "genai_config.json", lambda config: config["model"].update({"eos_token_id": eos}))
    model = og.Model(os.fspath(model_path))
    processor = model.create_multimodal_processor()
    inputs = processor(AUDIO_MARKER, audios=og.Audios.open(clip))
    prompt_length = inputs["input_ids"].as_numpy().shape[1]
    params = og.GeneratorParams(model)
    params.set_search_options(do_sample=False, max_length=prompt_length + num_tokens)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    generated = []
    while not generator.is_done():
        generator.generate_next_token()
        generated.append(int(generator.get_next_tokens()[0]))
    return generated


def test_lfm2_audio_generation_stops_when_the_model_starts_speaking(test_data_path, tmp_path):
    # Everything the model emits after <|audio_start|> is audio codes for a depthformer this runtime
    # does not have, so the builder puts that token in eos_token_id and generation has to end on it.
    # The fixture decoder never emits 128 on its own, so this pins the mechanism on a token it does
    # emit: whichever id is named as the audio stop, the run ends at its first occurrence.
    model_path = _copy_model(test_data_path, tmp_path)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=40))

    unrestricted = _generate_with_eos(model_path, clip, [7], num_tokens=40)
    assert len(unrestricted) == 40, "the fixture should run to max_length without a stop token"

    stop_token = unrestricted[5]
    first = unrestricted.index(stop_token)

    stopped = _generate_with_eos(model_path, clip, [stop_token], num_tokens=40)

    assert stopped == unrestricted[: first + 1], "generation must end at the stop token, with nothing after it"


def test_lfm2_audio_modality_stops_leave_normal_stopping_alone(test_data_path, tmp_path):
    # Adding the two modality-switch tokens alongside <|im_end|> must not change a run that stays in
    # text the whole way.
    model_path = _copy_model(test_data_path, tmp_path)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=41))
    switches = [AUDIO_START_TOKEN_ID, TEXT_END_TOKEN_ID]

    without = _generate_with_eos(model_path, clip, [7], num_tokens=25)
    with_switch_stops = _generate_with_eos(model_path, clip, [7, *switches], num_tokens=25)

    assert not set(switches) & set(without), "the fixture is not expected to emit the switch tokens"
    assert with_switch_stops == without


def test_lfm2_audio_fixture_config_is_what_the_builder_writes(test_data_path):
    # The tiny model stands in for a built one; its stop tokens have to match what the builder emits
    # for these checkpoints, or the tests above would be exercising a different contract.
    config = json.loads((Path(_model_path(test_data_path)) / "genai_config.json").read_text())
    assert config["model"]["type"] == "lfm2_audio"
    assert config["model"]["audio_token_id"] == AUDIO_TOKEN_ID
    assert config["model"]["eos_token_id"] == [7, AUDIO_START_TOKEN_ID, TEXT_END_TOKEN_ID]


# Speech output. The fixture's depthformer and audio embedding have the contract of LiquidAI's exports,
# and its decoder has the hidden_states output they read; model.audio_output switches them on.
NUM_CODEBOOKS = 8
CODEBOOK_SIZE = 2049
INTERLEAVED_N_TEXT = 6
INTERLEAVED_N_AUDIO = 12


def _speech_model(test_data_path, tmp_path, **audio_output) -> Path:
    model_path = _copy_model(test_data_path, tmp_path)

    def edit(config):
        # The modality-switch tokens must not be stop tokens once there is speech to switch to.
        config["model"]["eos_token_id"] = 7
        config["model"]["audio_output"] = {
            "depthformer": {"filename": "dummy_depthformer.onnx"},
            "embedding": {"filename": "dummy_audio_embedding.onnx"},
            **audio_output,
        }

    _edit_json(model_path / "genai_config.json", edit)
    return model_path


def _generate_speech(model_path, prompt, audios, num_items, **search):
    model = og.Model(os.fspath(model_path))
    inputs = model.create_multimodal_processor()(prompt, audios=audios)
    prompt_length = inputs["input_ids"].as_numpy().shape[1]
    params = og.GeneratorParams(model)
    params.set_search_options(do_sample=False, max_length=prompt_length + num_items, **search)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    while not generator.is_done():
        generator.generate_next_token()
    return inputs, generator.get_sequence(0)[prompt_length:].tolist(), generator.get_output("audio_codes")


def _reference_speech(model_path, inputs, num_items, interleaved, audio_start=128, codebook_size=CODEBOOK_SIZE):
    """liquid-audio's generate_sequential / generate_interleaved over the fixture, audio taken greedily.

    Returns the generated sequence, with AUDIO_TOKEN_ID standing for each audio frame as the runtime
    records it, and the frames themselves without the end-of-audio ones.
    """
    ort = pytest.importorskip("onnxruntime")
    config = json.loads((Path(model_path) / "genai_config.json").read_text())["model"]
    decoder_config = config["decoder"]
    session = lambda name: ort.InferenceSession(os.path.join(model_path, name))  # noqa: E731
    speech, embedding, decoder = (session(config[k]["filename"]) for k in ("speech", "embedding", "decoder"))
    depthformer, audio_embedding = session("dummy_depthformer.onnx"), session("dummy_audio_embedding.onnx")
    hidden_size = decoder_config["hidden_size"]
    no_features = np.zeros((0, hidden_size), np.float32)

    features = no_features
    if inputs["audio_sizes"].as_numpy().sum() > 0:
        mel, frames = inputs["audio_embeds"].as_numpy(), inputs["audio_lengths"].as_numpy()
        features = np.concatenate(
            [
                speech.run(None, {"mel_spectrogram": mel[i : i + 1, :n], "mel_lengths": frames[i : i + 1]})[0][0]
                for i, n in enumerate(frames)
            ]
        )
    embeds = embedding.run(
        None, {"input_ids": inputs["input_ids"].as_numpy().astype(np.int64), "audio_features": features}
    )[0]

    state = {}
    for layer, layer_type in enumerate(decoder_config["layer_types"]):
        if layer_type == "conv":
            state[f"past.{layer}.conv"] = np.zeros((1, hidden_size, decoder_config["conv_cache_size"]), np.float32)
        else:
            for kind in ("key", "value"):
                state[f"past_key_values.{layer}.{kind}"] = np.zeros(
                    (1, decoder_config["num_key_value_heads"], 0, decoder_config["head_size"]), np.float32
                )
    output_names = [output.name for output in decoder.get_outputs()]

    def sample_frame(hidden):
        keys = np.zeros((1, 1, 1, 0, 16), np.float32)
        values, slices, previous, frame = keys.copy(), np.zeros((1, NUM_CODEBOOKS, 16), np.float32), 0, []
        for step in range(NUM_CODEBOOKS):
            logits, new_slices, keys, values = depthformer.run(
                ["logits", "depth_slices", "new_keys", "new_values"],
                {
                    "hidden_states": hidden[None],
                    "depth_slices_in": slices,
                    "step_idx": np.array(step, np.int64),
                    "prev_token": np.array([previous], np.int64),
                    "past_keys": keys,
                    "past_values": values,
                    "seqlens_k": np.array([step], np.int32),
                    "total_seq_len": np.array(step + 1, np.int32),
                },
            )
            slices = new_slices if step == 0 else slices
            previous = int(logits[0, :codebook_size].argmax())
            frame.append(previous)
        return np.array(frame, np.int64)

    sequence, frames, total = [], [], 0
    in_audio, left, text_done = False, INTERLEAVED_N_TEXT, False
    for _ in range(num_items):
        left -= 1
        total += embeds.shape[1]
        feeds = {"inputs_embeds": embeds, "attention_mask": np.ones((1, total), np.int64), **state}
        outputs = dict(zip(output_names, decoder.run(None, feeds), strict=True))
        for name in state:
            state[name] = outputs[name.replace("past_key_values.", "present.").replace("past.", "present.")]

        if not in_audio:
            token = int(outputs["logits"][0, -1].argmax())
            sequence.append(token)
            if token == 7:
                break
            if interleaved:
                text_done = text_done or token == 130
                if left == 0 or text_done:
                    in_audio, left = True, INTERLEAVED_N_AUDIO
            elif token == audio_start:
                in_audio = True
            embeds = embedding.run(None, {"input_ids": np.array([[token]], np.int64), "audio_features": no_features})[0]
        else:
            frame = sample_frame(outputs["hidden_states"][0, -1])
            if interleaved and left == 0 and not text_done:
                in_audio, left = False, INTERLEAVED_N_TEXT
            if frame[0] == codebook_size - 1:
                frame[:] = codebook_size - 1
                in_audio = False
            else:
                frames.append(frame.copy())
            sequence.append(AUDIO_TOKEN_ID)
            rows = (frame + np.arange(NUM_CODEBOOKS) * codebook_size)[None]
            embeds = audio_embedding.run(None, {"audio_codes": rows})[0].sum(axis=1, keepdims=True)
    return sequence, np.array(frames, np.int64).reshape(-1, NUM_CODEBOOKS)


@pytest.mark.parametrize("num_clips", [0, 1], ids=["typed", "spoken"])
def test_lfm2_audio_interleaved_speech_matches_reference(test_data_path, tmp_path, num_clips):
    # Six text tokens, twelve audio frames, and round again: each frame is eight codes from the
    # depthformer, and its embedding rather than a token's is what the decoder reads next. The
    # sequence keeps one placeholder per frame, and the codes come out on their own.
    model_path = _speech_model(test_data_path, tmp_path)
    clips = [_write_wav(tmp_path / "question.wav", _synthetic_signal(0.9, seed=70))] * num_clips
    prompt = "<|startoftext|>Answer aloud. " + AUDIO_MARKER * num_clips

    inputs, sequence, codes = _generate_speech(
        model_path, prompt, og.Audios.open(*clips) if clips else None, 45, audio_interleaved=True, audio_top_k=1
    )
    expected_sequence, expected_codes = _reference_speech(os.fspath(model_path), inputs, 45, interleaved=True)

    layout = "".join("A" if token == AUDIO_TOKEN_ID else "T" for token in sequence)
    assert layout.startswith("T" * INTERLEAVED_N_TEXT + "A" * INTERLEAVED_N_AUDIO + "T" * INTERLEAVED_N_TEXT)
    assert sequence == expected_sequence
    np.testing.assert_array_equal(codes, expected_codes)
    assert codes.shape == (layout.count("A"), NUM_CODEBOOKS)


def _text_stream(test_data_path, tmp_path, num_tokens):
    """What the fixture writes when nothing turns it to speech."""
    clip = _write_wav(tmp_path / "probe.wav", _synthetic_signal(0.5, seed=71))
    return _generate_with_eos(_copy_model(test_data_path, tmp_path / "probe"), clip, [7], num_tokens)


def test_lfm2_audio_sequential_speech_starts_at_audio_start_and_ends_at_end_of_audio(test_data_path, tmp_path):
    # TTS and the like: text until <|audio_start|>, speech until the end-of-audio code, then text
    # again. The fixture emits neither on its own, so the start token is one it does write, and the
    # codebook is cut down to sixteen entries so that the last of them, end-of-audio, comes up.
    text = _text_stream(test_data_path, tmp_path, 12)
    audio_start = text[3]
    model_path = _speech_model(test_data_path, tmp_path, audio_start_token_id=audio_start, codebook_size=16)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=71))

    inputs, sequence, codes = _generate_speech(model_path, AUDIO_MARKER, og.Audios.open(clip), 60, audio_top_k=1)
    expected_sequence, expected_codes = _reference_speech(
        os.fspath(model_path), inputs, 60, interleaved=False, audio_start=audio_start, codebook_size=16
    )

    assert sequence[: text.index(audio_start) + 1] == text[: text.index(audio_start) + 1]
    assert sequence[text.index(audio_start) + 1] == AUDIO_TOKEN_ID, "speech starts right after <|audio_start|>"
    assert sequence == expected_sequence
    np.testing.assert_array_equal(codes, expected_codes)
    # End-of-audio frames hold a place in the sequence but are not speech.
    assert 0 < len(codes) < sequence.count(AUDIO_TOKEN_ID)
    assert codes[:, 0].max() < 15, "only the first codebook carries the end-of-audio code"
    after_speech = sequence[text.index(audio_start) + 1 :]
    assert any(token != AUDIO_TOKEN_ID for token in after_speech), "the turn goes back to text after end-of-audio"


def test_lfm2_audio_speech_output_leaves_a_text_answer_alone(test_data_path, tmp_path):
    text = _text_stream(test_data_path, tmp_path, 20)
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5, seed=71))

    _, sequence, codes = _generate_speech(
        _speech_model(test_data_path, tmp_path), AUDIO_MARKER, og.Audios.open(clip), 20
    )

    assert sequence == text
    assert codes.shape == (0, NUM_CODEBOOKS)


def test_lfm2_audio_speech_sampling_follows_the_seed(test_data_path, tmp_path):
    model_path = _speech_model(test_data_path, tmp_path)
    # The fixture's logits are far apart, so it takes a high temperature for the four likeliest to share the odds.
    options = {"audio_interleaved": True, "audio_temperature": 100.0, "audio_top_k": 4}
    run = lambda **search: _generate_speech(model_path, "Say something.", None, 30, **options, **search)[2]  # noqa: E731

    first, again, other = run(random_seed=3), run(random_seed=3), run(random_seed=4)
    greedy = _generate_speech(model_path, "Say something.", None, 30, audio_interleaved=True, audio_top_k=1)[2]

    np.testing.assert_array_equal(first, again)
    assert not np.array_equal(first, other)
    assert not np.array_equal(first, greedy)
    # The first frame follows text only, so it is sampled from the same logits whatever the seed:
    # with top_k 4 every code in it has to be one of the four likeliest.
    assert first.shape == greedy.shape and first.min() >= 0 and first.max() < CODEBOOK_SIZE


@pytest.mark.parametrize(
    "edit,expected",
    [
        (lambda m: m.update({"eos_token_id": [7, 128]}), "eos_token_id holds 128.*Remove it"),
        (lambda m: m.update({"eos_token_id": [7, 130]}), "eos_token_id holds 130.*Remove it"),
        (lambda m: m["audio_output"].pop("embedding"), "needs both depthformer.filename and embedding.filename"),
        (lambda m: m["audio_output"].update({"num_codebooks": 4}), "expected inputs for 4 codebooks"),
    ],
    ids=["audio-start-is-a-stop-token", "text-end-is-a-stop-token", "one-graph-missing", "codebook-count"],
)
def test_lfm2_audio_rejects_a_speech_output_config_that_cannot_work(test_data_path, tmp_path, edit, expected):
    model_path = _speech_model(test_data_path, tmp_path)
    _edit_json(model_path / "genai_config.json", lambda config: edit(config["model"]))

    with pytest.raises(RuntimeError, match=expected):
        model = og.Model(os.fspath(model_path))
        og.Generator(model, og.GeneratorParams(model))


def test_lfm2_audio_speech_output_needs_the_decoder_hidden_states(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_path = _speech_model(test_data_path, tmp_path)
    decoder_path = model_path / "dummy_text.onnx"
    decoder = onnx.load(decoder_path)
    del decoder.graph.output[[output.name for output in decoder.graph.output].index("hidden_states")]
    onnx.save(decoder, decoder_path)

    with pytest.raises(RuntimeError, match="include_hidden_states=true"):
        _generate_speech(model_path, "Say something.", None, 12, audio_interleaved=True)


def _two_clip_inputs(model_path, tmp_path):
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.5 - 0.5 * i, seed=50 + i)) for i in range(2)]
    model = og.Model(os.fspath(model_path))
    inputs = model.create_multimodal_processor()(f"{AUDIO_MARKER} and {AUDIO_MARKER}", audios=og.Audios.open(*clips))
    return model, inputs


def _set_inputs(model, inputs):
    params = og.GeneratorParams(model)
    params.set_search_options(do_sample=False, max_length=4096)
    og.Generator(model, params).set_inputs(inputs)


@pytest.mark.parametrize(
    "corrupt,expected",
    [
        (lambda i, lengths: i.__setitem__("audio_embeds", np.zeros((2, 5), np.float32)), "expected a 3D"),
        (
            lambda i, lengths: i.__setitem__("audio_embeds", np.zeros((3, 20, NUM_MELS), np.float32)),
            "holds 3 clips but audio_sizes has 2 entries",
        ),
        (lambda i, lengths: i.__setitem__("audio_lengths", np.array([8], np.int64)), "mel_lengths has 1 entries"),
        # Past the end of the staged tensor: the clip's frames would be copied out of bounds.
        (
            lambda i, lengths: i.__setitem__("audio_lengths", np.array([lengths[0], 10**6], np.int64)),
            r"clip 1 reports 1000000 mel frames, outside the 1\.\.",
        ),
        (
            lambda i, lengths: i.__setitem__("audio_lengths", np.array([lengths[0], 0], np.int64)),
            r"clip 1 reports 0 mel frames, outside the 1\.\.",
        ),
    ],
    ids=["mel-rank", "clip-count", "lengths-count", "frames-past-the-end", "frames-zero"],
)
def test_lfm2_audio_rejects_inconsistent_speech_inputs(test_data_path, tmp_path, corrupt, expected):
    # The tensors the processor hands back can be replaced before they reach the generator, so the
    # speech state checks that they still agree with one another. Without these the mismatch would
    # surface as a confusing shape error from inside the encoder, or as an out-of-bounds read.
    model, inputs = _two_clip_inputs(_model_path(test_data_path), tmp_path)
    corrupt(inputs, inputs["audio_lengths"].as_numpy().copy())

    with pytest.raises(RuntimeError, match=expected):
        _set_inputs(model, inputs)


@pytest.mark.parametrize("num_clips", [0, 1, 2], ids=["text", "one-clip", "two-clips"])
def test_lfm2_audio_rejects_beam_search(test_data_path, tmp_path, num_clips):
    # Without the check a single clip fails with a shape mismatch from inside the encoder.
    clips = [_write_wav(tmp_path / f"{i}.wav", _synthetic_signal(1.5 - 0.5 * i, seed=60 + i)) for i in range(num_clips)]
    model = og.Model(_model_path(test_data_path))
    prompt = "Hi " + " and ".join([AUDIO_MARKER] * num_clips)
    inputs = model.create_multimodal_processor()(prompt, audios=og.Audios.open(*clips) if clips else None)
    params = og.GeneratorParams(model)
    params.set_search_options(do_sample=False, max_length=4096, num_beams=2)

    with pytest.raises(RuntimeError, match="beam search is not supported for lfm2_audio; got num_beams 2"):
        og.Generator(model, params).set_inputs(inputs)


def test_lfm2_audio_rejects_rewind(test_data_path, tmp_path):
    clip = _write_wav(tmp_path / "clip.wav", _synthetic_signal(0.5))
    generator, _ = _generate(_model_path(test_data_path), f"{AUDIO_MARKER}Hi", og.Audios.open(clip), num_tokens=1)
    sequence = generator.get_sequence(0).copy()

    # The conv state cannot be rewound; the generator must refuse before touching the sequence.
    with pytest.raises(RuntimeError, match="RewindTo is currently not supported for lfm2_audio"):
        generator.rewind_to(0)
    np.testing.assert_array_equal(generator.get_sequence(0), sequence)
