# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License

"""
Unit tests for the Gemma4 "unified" (encoder-free, gemma-4-12B) multimodal model.

Unlike the standard gemma4 model, the unified variant consumes raw 48px merged
pixel patches (``pixel_values`` last dim = 6912) and raw 640-sample waveform
frames (``audio_embeds`` last dim = 640) directly, and its ``model.type`` is
``gemma4_unified``. These tests exercise the ``unified_`` branch of
``Gemma4MultiModalProcessor``: processor creation, and that the produced
pixel_values / audio_embeds / audio_sizes follow the unified contract.

The dummy model fixtures live in ``test/models/gemma4_unified`` (generated by
``test/python/create/create_dummy_gemma4_unified_models.py``).

Usage:
    pytest test_gemma4_unified_models.py --test_models=/path/to/models
"""

import logging
import os
from pathlib import Path

import numpy as np
import onnxruntime_genai as og
import pytest

logging.basicConfig(format="%(asctime)s %(name)s [%(levelname)s] - %(message)s", level=logging.DEBUG)
log = logging.getLogger("gemma4-unified-tests")

GEMMA4_UNIFIED_MODEL_NAME = "gemma4_unified"

# Encoder-free unified contract.
_UNIFIED_PIXEL_DIM = 48 * 48 * 3  # 6912
_UNIFIED_AUDIO_DIM = 640


def _get_model_path(test_data_path):
    """Return the gemma4_unified model path, skipping if it doesn't exist."""
    model_path = os.path.join(test_data_path, GEMMA4_UNIFIED_MODEL_NAME)
    if not os.path.exists(model_path):
        pytest.skip(f"gemma4_unified test model not found at {model_path}")
    return model_path


def _load_model_and_processor(test_data_path):
    model_path = _get_model_path(test_data_path)
    model = og.Model(model_path)
    return model, model.create_multimodal_processor()


def _to_numpy(tensor):
    if hasattr(tensor, "as_numpy"):
        return tensor.as_numpy()
    if hasattr(tensor, "numpy"):
        return tensor.numpy()
    return np.array(tensor)


def test_gemma4_unified_model_load(test_data_path):
    """The gemma4_unified model (model.type == 'gemma4_unified') loads."""
    model_path = _get_model_path(test_data_path)
    model = og.Model(model_path)
    assert model is not None


def test_gemma4_unified_processor_creation(test_data_path):
    """create_multimodal_processor() succeeds for the gemma4_unified type.

    This exercises the processor-factory registration and the unified image /
    audio ort-extensions configs (Gemma4ImageTransform at patch_size=48 and
    Gemma4UnifiedAudioFrames).
    """
    _, processor = _load_model_and_processor(test_data_path)
    assert processor is not None


def test_gemma4_unified_text_only(test_data_path):
    """Text-only processing (no images/audio)."""
    _, processor = _load_model_and_processor(test_data_path)
    inputs = processor("What is the capital of France?", images=None)
    assert inputs is not None
    assert "input_ids" in inputs
    ids = _to_numpy(inputs["input_ids"])
    assert len(ids.shape) == 2 and ids.shape[0] == 1


@pytest.mark.parametrize("relative_image_path", [Path("images") / "australia.jpg"])
def test_gemma4_unified_vision_contract(test_data_path, relative_image_path):
    """Unified vision preprocessing produces 6912-dim merged patches (no trim)."""
    _, processor = _load_model_and_processor(test_data_path)

    image_path = os.fspath(Path(test_data_path) / relative_image_path)
    if not os.path.exists(image_path):
        pytest.skip(f"Test image not found at {image_path}")
    images = og.Images.open(image_path)

    inputs = processor("<|image|>Describe this image", images=images)
    assert inputs is not None
    assert "pixel_values" in inputs
    assert "pixel_position_ids" in inputs

    pixel_values = _to_numpy(inputs["pixel_values"])
    assert pixel_values.shape[-1] == _UNIFIED_PIXEL_DIM, (
        f"unified pixel_values feature dim should be {_UNIFIED_PIXEL_DIM}, got {pixel_values.shape[-1]}"
    )
    # Unified feeds the full padded patch grid (no trim); the graph strips
    # padding via position_ids. pixel_position_ids rows must match pixel_values.
    pos = _to_numpy(inputs["pixel_position_ids"])
    assert pos.shape[-2] == pixel_values.shape[-2], (
        f"position_ids ({pos.shape}) and pixel_values ({pixel_values.shape}) patch counts must match"
    )
    assert pos.shape[-1] == 2


@pytest.mark.parametrize("relative_audio_path", [Path("audios") / "jfk.flac"])
def test_gemma4_unified_audio_contract(test_data_path, relative_audio_path):
    """Unified audio preprocessing produces raw 640-sample frames; audio_sizes = frame count."""
    _, processor = _load_model_and_processor(test_data_path)

    audio_path = os.fspath(Path(test_data_path) / relative_audio_path)
    if not os.path.exists(audio_path):
        pytest.skip(f"Test audio file not found at {audio_path}")

    audios = og.Audios.open(audio_path)
    inputs = processor("<|audio|>Transcribe this audio", audios=audios)
    assert inputs is not None
    assert "audio_embeds" in inputs
    assert "audio_sizes" in inputs

    audio_embeds = _to_numpy(inputs["audio_embeds"])
    assert audio_embeds.shape[-1] == _UNIFIED_AUDIO_DIM, (
        f"unified audio_embeds feature dim should be {_UNIFIED_AUDIO_DIM}, got {audio_embeds.shape[-1]}"
    )
    assert audio_embeds.dtype == np.float32

    # Unified: each 640-sample frame is exactly one audio token, so audio_sizes
    # equals the number of frames (no stride-2 subsampling).
    num_frames = audio_embeds.shape[-2]
    audio_sizes = _to_numpy(inputs["audio_sizes"])
    assert audio_sizes[0] == num_frames, (
        f"unified audio_sizes should equal frame count {num_frames}, got {audio_sizes[0]}"
    )
