# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License

"""
Tests for the LFM2-VL pipeline against the tiny models in test/models/lfm2-vl.

The models are generated by test/python/create/create_dummy_lfm2_vl_models.py. The vision model
emits one feature per <image> placeholder, and the decoder's logits depend on the conv state, so
generation only succeeds, and only matches between runs, when the processor, the vision/embedding
hand-off and the conv state cache agree.

Run with:
    python -m pytest test/python/models/test_lfm2_vl_models.py --test_models test/models
"""

from __future__ import annotations

import io
import json
import math
import os
import shutil
import struct
import zlib
from pathlib import Path

import numpy as np
import onnxruntime_genai as og
import pytest

IMAGE_TOKEN = "<image>"
IMAGE_START_TOKEN = "<|image_start|>"
IMAGE_END_TOKEN = "<|image_end|>"
ENCODER_PATCH_SIZE = 16
DOWNSAMPLE_FACTOR = 2
PATCH_DIM = ENCODER_PATCH_SIZE * ENCODER_PATCH_SIZE * 3
MAX_NUM_PATCHES = 1024
MIN_PIXELS = 65536
MAX_PIXELS = 262144
# One 8-bit level after rescale by 1/255 and normalize with mean/std 0.5.
ONE_PIXEL_LEVEL = 2.0 / 255.0


def _model_path(test_data_path) -> str:
    path = Path(test_data_path) / "lfm2-vl"
    if not (path / "genai_config.json").exists():
        pytest.skip(f"LFM2-VL test model not found at {path}")
    return os.fspath(path)


def _image_path(test_data_path, name) -> str:
    # Absolute paths: og.Images.open keeps pointers to the path strings, which short relative
    # paths do not survive when several images are opened at once.
    path = (Path(test_data_path).parent / "images" / name).resolve()
    if not path.exists():
        pytest.skip(f"Test image not found at {path}")
    return os.fspath(path)


def _copy_model(test_data_path, tmp_path) -> Path:
    destination = tmp_path / "lfm2-vl"
    shutil.copytree(_model_path(test_data_path), destination)
    return destination


def _edit_json(path: Path, edit):
    config = json.loads(path.read_text())
    edit(config)
    path.write_text(json.dumps(config))


def _png(width: int, height: int, color_type: int, pixel: bytes) -> bytes:
    """Encodes a solid-color 8-bit PNG (color type 0 gray, 2 RGB, 4 gray+alpha, 6 RGBA)."""

    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", width, height, 8, color_type, 0, 0, 0)
    rows = b"".join(b"\x00" + pixel * width for _ in range(height))
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(rows)) + chunk(b"IEND", b"")


def _tokens_for_grid(rows: int, cols: int) -> int:
    return math.ceil(rows / DOWNSAMPLE_FACTOR) * math.ceil(cols / DOWNSAMPLE_FACTOR)


def _process(model_path: str, prompt: str, images):
    model = og.Model(model_path)
    inputs = model.create_multimodal_processor()(prompt, images=images)
    return model, inputs


def _image_runs(input_ids: np.ndarray, tokenizer) -> list[int]:
    """Lengths of the <image> runs between each <|image_start|> / <|image_end|> pair, in order."""
    image_id = tokenizer.to_token_id(IMAGE_TOKEN)
    start_id = tokenizer.to_token_id(IMAGE_START_TOKEN)
    end_id = tokenizer.to_token_id(IMAGE_END_TOKEN)
    starts = np.flatnonzero(input_ids == start_id)
    ends = np.flatnonzero(input_ids == end_id)
    assert len(starts) == len(ends)
    runs = []
    for start, end in zip(starts, ends, strict=True):
        run = input_ids[start + 1 : end]
        assert np.all(run == image_id), "only <image> tokens may sit between the start and end markers"
        runs.append(len(run))
    return runs


def _generate(model_path: str, prompt: str, images, num_tokens: int, chunk_size: int | None = None):
    model = og.Model(model_path)
    processor = model.create_multimodal_processor()
    params = og.GeneratorParams(model)
    options = {"do_sample": False, "max_length": 2048}
    if chunk_size is not None:
        options["chunk_size"] = chunk_size
    params.set_search_options(**options)

    inputs = processor(prompt, images=images)
    generator = og.Generator(model, params)
    generator.set_inputs(inputs)
    for _ in range(num_tokens):
        generator.generate_next_token()
    return generator, inputs


def test_lfm2_vl_processor_single_image(test_data_path):
    model, inputs = _process(
        _model_path(test_data_path),
        "<image>Describe this image.",
        og.Images.open(_image_path(test_data_path, "australia.jpg")),
    )
    tokenizer = og.Tokenizer(model)

    pixel_values = inputs["pixel_values"].as_numpy()
    mask = inputs["image_attention_mask"].as_numpy()
    rows, cols = inputs["image_sizes"].as_numpy()[0].tolist()
    input_ids = inputs["input_ids"].as_numpy()[0]
    num_patches = rows * cols
    tokens = _tokens_for_grid(rows, cols)

    # Smart resize lands between min_image_tokens and max_image_tokens worth of pixels.
    assert MIN_PIXELS <= num_patches * ENCODER_PATCH_SIZE**2 <= MAX_PIXELS
    assert pixel_values.shape == (1, MAX_NUM_PATCHES, PATCH_DIM)
    assert mask.shape == (1, MAX_NUM_PATCHES)
    assert mask[0, :num_patches].all() and not mask[0, num_patches:].any()
    assert not pixel_values[0, num_patches:].any(), "padding patches must be zero"

    assert inputs["num_image_tokens"].as_numpy().tolist() == [tokens]
    assert _image_runs(input_ids, tokenizer) == [tokens]
    assert np.count_nonzero(input_ids == tokenizer.to_token_id(IMAGE_TOKEN)) == tokens


def test_lfm2_vl_processor_text_only(test_data_path):
    model, inputs = _process(_model_path(test_data_path), "Describe this image.", None)
    tokenizer = og.Tokenizer(model)

    assert "pixel_values" not in inputs
    assert inputs["num_image_tokens"].as_numpy().tolist() == [0]
    np.testing.assert_array_equal(inputs["input_ids"].as_numpy()[0], tokenizer.encode("Describe this image."))


def test_lfm2_vl_processor_two_images_of_different_sizes(test_data_path):
    image_paths = [_image_path(test_data_path, "cars.jpg"), _image_path(test_data_path, "sheet.png")]
    model, inputs = _process(_model_path(test_data_path), "<image><image>Compare these.", og.Images.open(*image_paths))
    tokenizer = og.Tokenizer(model)

    pixel_values = inputs["pixel_values"].as_numpy()
    mask = inputs["image_attention_mask"].as_numpy()
    spatial_shapes = inputs["image_sizes"].as_numpy().tolist()

    assert pixel_values.shape == (2, MAX_NUM_PATCHES, PATCH_DIM)
    assert spatial_shapes[0] != spatial_shapes[1], "the images must resize to different grids"
    assert mask.sum(axis=1).tolist() == [rows * cols for rows, cols in spatial_shapes]

    expected_tokens = [_tokens_for_grid(rows, cols) for rows, cols in spatial_shapes]
    assert _image_runs(inputs["input_ids"].as_numpy()[0], tokenizer) == expected_tokens
    assert inputs["num_image_tokens"].as_numpy().tolist() == [sum(expected_tokens)]


def test_lfm2_vl_processor_open_bytes_matches_open(test_data_path):
    model_path = _model_path(test_data_path)
    image_path = _image_path(test_data_path, "landscape.jpg")

    _, from_path = _process(model_path, "<image>x", og.Images.open(image_path))
    _, from_bytes = _process(model_path, "<image>x", og.Images.open_bytes(Path(image_path).read_bytes()))

    for name in ("input_ids", "pixel_values", "image_attention_mask", "image_sizes", "num_image_tokens"):
        np.testing.assert_array_equal(from_bytes[name].as_numpy(), from_path[name].as_numpy())


@pytest.mark.parametrize(
    "color_type,pixel,expected",
    [
        (2, b"\xff\x00\x00", [1.0, -1.0, -1.0]),  # RGB red
        (6, b"\xff\x00\x00\xff", [1.0, -1.0, -1.0]),  # RGBA red, alpha dropped
        (0, b"\x80", [1.0 / 255.0] * 3),  # gray 128
        (4, b"\x80\xff", [1.0 / 255.0] * 3),  # gray 128 + alpha
    ],
    ids=["rgb", "rgba", "gray", "gray_alpha"],
)
def test_lfm2_vl_processor_emits_rgb_patches(test_data_path, color_type, pixel, expected):
    # Patches are [y][x][channel]; red must land in channel 0 (a BGR swap would put it in channel 2)
    # and every PNG color type must come out as three channels.
    _, inputs = _process(_model_path(test_data_path), "<image>x", og.Images.open_bytes(_png(64, 64, color_type, pixel)))

    num_patches = int(inputs["image_attention_mask"].as_numpy().sum())
    patches = inputs["pixel_values"].as_numpy()[0, :num_patches].reshape(num_patches, -1, 3)

    np.testing.assert_allclose(patches, np.broadcast_to(np.float32(expected), patches.shape), atol=1e-3)


@pytest.mark.parametrize(
    "prompt,image_names,expected",
    [
        ("Describe <image>.", ["cars.jpg", "sheet.png"], "contains 1 <image> tokens but 2 images were provided"),
        ("<image><image>x", ["cars.jpg"], "contains 2 <image> tokens but 1 images were provided"),
        ("<image>Describe.", [], "contains 1 <image> tokens but 0 images were provided"),
    ],
    ids=["fewer-markers-than-images", "more-markers-than-images", "marker-without-images"],
)
def test_lfm2_vl_rejects_image_token_count_mismatch(test_data_path, prompt, image_names, expected):
    # Lfm2VlProcessor.validate_inputs rejects every mismatch. Prepending the unreferenced images would
    # put a differently sized image's features under the referenced marker, and a marker without an
    # image would reach the embedding model as a literal token with no feature to scatter into it.
    images = og.Images.open(*[_image_path(test_data_path, name) for name in image_names]) if image_names else None
    with pytest.raises(RuntimeError, match=expected):
        _process(_model_path(test_data_path), prompt, images)


def test_lfm2_vl_single_prompt_list_matches_the_string_form(test_data_path):
    # The list overload fills payload.prompts and leaves payload.prompt empty; a one-entry list must
    # not come back as an empty prompt.
    model_path = _model_path(test_data_path)
    images = og.Images.open(_image_path(test_data_path, "cars.jpg"))
    _, from_string = _process(model_path, "<image>Describe this image.", images)
    _, from_list = _process(model_path, ["<image>Describe this image."], images)
    _, text_only = _process(model_path, ["Describe this image."], None)

    np.testing.assert_array_equal(from_list["input_ids"].as_numpy(), from_string["input_ids"].as_numpy())
    assert text_only["input_ids"].as_numpy().shape[1] > 0


def test_lfm2_vl_empty_prompt_list_keeps_string_behavior(test_data_path):
    model_path = _model_path(test_data_path)
    _, from_string = _process(model_path, "", None)
    _, from_list = _process(model_path, [], None)
    for name in ("input_ids", "num_image_tokens"):
        np.testing.assert_array_equal(from_list[name].as_numpy(), from_string[name].as_numpy())
    images = og.Images.open(_image_path(test_data_path, "cars.jpg"))
    for prompt in ("", []):
        with pytest.raises(RuntimeError, match="contains 0 <image> tokens but 1 images were provided"):
            _process(model_path, prompt, images)


def test_lfm2_vl_rejects_batched_prompts(test_data_path):
    with pytest.raises(RuntimeError, match="batched prompts are not supported; got 2 prompts"):
        _process(_model_path(test_data_path), ["Describe.", "Describe."], None)


def test_lfm2_vl_casts_pixel_values_to_the_vision_input_type(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_dir = _copy_model(test_data_path, tmp_path)
    vision = onnx.load(os.fspath(model_dir / "dummy_vision.onnx"))
    next(i for i in vision.graph.input if i.name == "pixel_values").type.tensor_type.elem_type = onnx.TensorProto.FLOAT16
    onnx.save(vision, os.fspath(model_dir / "dummy_vision.onnx"))

    images = og.Images.open(_image_path(test_data_path, "cars.jpg"))
    _, reference = _process(_model_path(test_data_path), "<image>x", images)
    _, inputs = _process(os.fspath(model_dir), "<image>x", images)

    pixel_values = inputs["pixel_values"].as_numpy()
    assert pixel_values.dtype == np.float16
    np.testing.assert_allclose(pixel_values.astype(np.float32), reference["pixel_values"].as_numpy(), rtol=0, atol=1e-3)
    # The vision session must accept the cast tensor, not just the processor emit it.
    generator, _ = _generate(os.fspath(model_dir), "<image>x", images, num_tokens=1)
    assert generator.get_sequence(0).shape[0] > 0


@pytest.mark.parametrize("field", ["pixel_values", "attention_mask", "image_sizes"])
def test_lfm2_vl_rejects_vision_input_name_missing_from_the_graph(test_data_path, tmp_path, field):
    model_dir = _copy_model(test_data_path, tmp_path)
    _edit_json(model_dir / "genai_config.json", lambda c: c["model"]["vision"]["inputs"].__setitem__(field, "renamed"))

    model = og.Model(os.fspath(model_dir))
    with pytest.raises(RuntimeError, match=rf'no input named "renamed"\. Point model\.vision\.inputs\.{field}'):
        model.create_multimodal_processor()


def test_lfm2_vl_rejects_non_int64_attention_mask(test_data_path, tmp_path):
    onnx = pytest.importorskip("onnx")
    model_dir = _copy_model(test_data_path, tmp_path)
    vision = onnx.load(os.fspath(model_dir / "dummy_vision.onnx"))
    next(
        i for i in vision.graph.input if i.name == "pixel_attention_mask"
    ).type.tensor_type.elem_type = onnx.TensorProto.INT32
    onnx.save(vision, os.fspath(model_dir / "dummy_vision.onnx"))

    model = og.Model(os.fspath(model_dir))
    with pytest.raises(RuntimeError, match='"pixel_attention_mask" must be int64, got int32'):
        model.create_multimodal_processor()


def test_lfm2_vl_max_num_patches_zero_pads_to_the_longest_image(test_data_path, tmp_path):
    model_dir = _copy_model(test_data_path, tmp_path)
    _edit_json(model_dir / "genai_config.json", lambda c: c["model"]["vision"].__setitem__("max_num_patches", 0))

    image_paths = [_image_path(test_data_path, "cars.jpg"), _image_path(test_data_path, "sheet.png")]
    _, inputs = _process(os.fspath(model_dir), "<image><image>x", og.Images.open(*image_paths))

    patch_counts = inputs["image_attention_mask"].as_numpy().sum(axis=1).tolist()
    assert inputs["pixel_values"].as_numpy().shape == (2, max(patch_counts), PATCH_DIM)


def test_lfm2_vl_rejects_image_larger_than_max_num_patches(test_data_path, tmp_path):
    model_dir = _copy_model(test_data_path, tmp_path)
    _edit_json(model_dir / "genai_config.json", lambda c: c["model"]["vision"].__setitem__("max_num_patches", 64))

    with pytest.raises(RuntimeError, match=r"more than the 64 allowed by model\.vision\.max_num_patches"):
        _process(os.fspath(model_dir), "<image>x", og.Images.open(_image_path(test_data_path, "cars.jpg")))


# Bicubic rounds a handful of pixels one level further than bilinear.
@pytest.mark.parametrize("interpolation,resample,max_levels", [("LINEAR", 2, 1), ("CUBIC", 3, 2)])
@pytest.mark.parametrize("image_name", ["cars.jpg", "10809054.jpg"])
def test_lfm2_vl_pixels_match_hugging_face(test_data_path, tmp_path, interpolation, resample, max_levels, image_name):
    transformers = pytest.importorskip("transformers")
    pytest.importorskip("torchvision")
    image_module = pytest.importorskip("PIL.Image")
    processor_class = getattr(transformers, "Lfm2VlImageProcessor", None)
    if processor_class is None:
        pytest.skip("transformers has no Lfm2VlImageProcessor")

    model_dir = _copy_model(test_data_path, tmp_path)

    def set_interpolation(config):
        for transform in config["processor"]["transforms"]:
            if transform["operation"]["type"] == "Resize":
                transform["operation"]["attrs"]["interpolation"] = interpolation

    _edit_json(model_dir / "processor_config.json", set_interpolation)

    # Decode once with PIL and hand both processors the same RGB pixels. JPEG decoders legitimately
    # differ by tens of levels on edges, which would hide a real resize or normalization difference.
    image = image_module.open(_image_path(test_data_path, image_name)).convert("RGB")
    png = io.BytesIO()
    image.save(png, format="PNG")

    _, inputs = _process(os.fspath(model_dir), "<image>x", og.Images.open_bytes(png.getvalue()))
    reference = processor_class(do_image_splitting=False, resample=resample)(images=[[image]], return_tensors="np")

    np.testing.assert_array_equal(inputs["image_sizes"].as_numpy(), reference["spatial_shapes"])
    np.testing.assert_array_equal(inputs["image_attention_mask"].as_numpy(), reference["pixel_attention_mask"])
    num_patches = int(reference["pixel_attention_mask"].sum())
    np.testing.assert_allclose(
        inputs["pixel_values"].as_numpy()[0, :num_patches],
        reference["pixel_values"][0, :num_patches],
        rtol=0,
        atol=ONE_PIXEL_LEVEL * max_levels * 1.01,
    )


def _reference_generation(model_path: str, input_ids: np.ndarray, num_tokens: int) -> np.ndarray:
    """Greedy generation replayed with plain ONNX Runtime.

    One prefill run, then one run per token, carrying the KV cache and conv state by hand. The stub
    embedding and decoder ignore the image features, so the prompt token ids are all it needs.
    """
    ort = pytest.importorskip("onnxruntime")
    config = json.loads((Path(model_path) / "genai_config.json").read_text())["model"]
    decoder_config = config["decoder"]
    embedding = ort.InferenceSession(os.path.join(model_path, config["embedding"]["filename"]))
    decoder = ort.InferenceSession(os.path.join(model_path, decoder_config["filename"]))
    output_names = [output.name for output in decoder.get_outputs()]

    hidden_size = decoder_config["hidden_size"]
    state = {}
    for layer, layer_type in enumerate(decoder_config["layer_types"]):
        if layer_type == "conv":
            state[f"past.{layer}.conv"] = np.zeros((1, hidden_size, decoder_config["conv_cache_size"]), np.float32)
        else:
            for kind in ("key", "value"):
                state[f"past_key_values.{layer}.{kind}"] = np.zeros(
                    (1, decoder_config["num_key_value_heads"], 0, decoder_config["head_size"]), np.float32
                )

    sequence = [int(token) for token in input_ids]
    step_ids = sequence
    for _ in range(num_tokens):
        embeds = embedding.run(
            None,
            {
                "input_ids": np.array([step_ids], dtype=np.int64),
                "image_features": np.zeros((0, hidden_size), np.float32),
            },
        )[0]
        feeds = {"inputs_embeds": embeds, "attention_mask": np.ones((1, len(sequence)), np.int64), **state}
        outputs = dict(zip(output_names, decoder.run(None, feeds), strict=True))
        for name in state:
            state[name] = outputs[name.replace("past_key_values.", "present.").replace("past.", "present.")]
        next_token = int(outputs["logits"][0, -1].argmax())
        sequence.append(next_token)
        step_ids = [next_token]
    return np.array(sequence, dtype=np.int32)


@pytest.mark.parametrize(
    "with_image,chunk_size",
    [(False, None), (False, 3), (True, None), (True, 3), (True, 64)],
    ids=["text", "text-chunk3", "image", "image-chunk3", "image-chunk64"],
)
def test_lfm2_vl_generation_matches_onnxruntime_reference(test_data_path, with_image, chunk_size):
    # The decoder's logits read the conv state, so the runtime only matches the hand-carried
    # reference if it passes that state between runs, including across prefill chunk boundaries.
    model_path = _model_path(test_data_path)
    images = og.Images.open(_image_path(test_data_path, "cars.jpg")) if with_image else None
    prompt = "<image>Describe this image." if with_image else "Describe this image in detail please."
    num_tokens = 6

    generator, inputs = _generate(model_path, prompt, images, num_tokens, chunk_size=chunk_size)
    input_ids = inputs["input_ids"].as_numpy()[0]
    assert chunk_size is None or len(input_ids) > chunk_size, "the prompt must span several chunks"

    np.testing.assert_array_equal(generator.get_sequence(0), _reference_generation(model_path, input_ids, num_tokens))


def test_lfm2_vl_rejects_rewind(test_data_path):
    generator, _ = _generate(
        _model_path(test_data_path), "<image>Hi", og.Images.open(_image_path(test_data_path, "cars.jpg")), num_tokens=1
    )
    sequence = generator.get_sequence(0).copy()

    # The conv state cannot be rewound; the generator must refuse before touching the sequence.
    with pytest.raises(RuntimeError, match="RewindTo is currently not supported for lfm2_vl"):
        generator.rewind_to(0)
    np.testing.assert_array_equal(generator.get_sequence(0), sequence)
