"""

        Ort Generators library
        ----------------------

        .. currentmodule:: cmake_example

        .. autosummary::
           :toctree: _generate


"""
from __future__ import annotations
import numpy
import typing
__all__: list[str] = ['Adapters', 'Audios', 'Config', 'Engine', 'Generator', 'GeneratorParams', 'Images', 'Model', 'MultiModalProcessor', 'NamedTensors', 'Request', 'StreamingProcessor', 'Tensor', 'TokenMetadataCoreConfig', 'TokenMetadataInput', 'Tokenizer', 'TokenizerStream', 'get_current_gpu_device_id', 'is_cuda_available', 'is_dml_available', 'is_openvino_available', 'is_qnn_available', 'is_rocm_available', 'is_webgpu_available', 'register_execution_provider_library', 'set_current_gpu_device_id', 'set_log_callback', 'set_log_options', 'unregister_execution_provider_library']
class Adapters:
    def __init__(self, arg0: Model) -> None:
        ...
    def load(self, arg0: str, arg1: str) -> None:
        ...
    def unload(self, arg0: str) -> None:
        ...
class Audios:
    @staticmethod
    def open(*args) -> Audios:
        ...
    @staticmethod
    def open_bytes(*args) -> Audios:
        ...
class Config:
    def __init__(self, arg0: str) -> None:
        ...
    def add_model_data(self, arg0: str, arg1: typing.Any) -> None:
        ...
    def append_provider(self, arg0: str) -> None:
        ...
    def clear_decoder_provider_options_hardware_device_id(self, arg0: str) -> None:
        ...
    def clear_decoder_provider_options_hardware_device_type(self, arg0: str) -> None:
        ...
    def clear_decoder_provider_options_hardware_vendor_id(self, arg0: str) -> None:
        ...
    def clear_providers(self) -> None:
        ...
    def overlay(self, arg0: str) -> None:
        ...
    def remove_model_data(self, arg0: str) -> None:
        ...
    def set_decoder_provider_options_hardware_device_id(self, arg0: str, arg1: int) -> None:
        ...
    def set_decoder_provider_options_hardware_device_type(self, arg0: str, arg1: str) -> None:
        ...
    def set_decoder_provider_options_hardware_vendor_id(self, arg0: str, arg1: int) -> None:
        ...
    def set_provider_option(self, arg0: str, arg1: str, arg2: str) -> None:
        ...
class Engine:
    def __init__(self, arg0: Model) -> None:
        ...
    def add_request(self, arg0: Request) -> None:
        ...
    def has_pending_requests(self) -> bool:
        ...
    def remove_request(self, arg0: Request) -> None:
        ...
    def step(self) -> Request:
        ...
class Generator:
    def __init__(self, arg0: Model, arg1: GeneratorParams) -> None:
        ...
    @typing.overload
    def append_tokens(self, arg0: numpy.ndarray[numpy.int32]) -> None:
        ...
    @typing.overload
    def append_tokens(self, arg0: Tensor) -> None:
        ...
    def generate_next_token(self) -> None:
        ...
    def get_input(self, arg0: str) -> numpy.ndarray:
        ...
    def get_logits(self) -> numpy.ndarray[numpy.float32]:
        ...
    def get_next_tokens(self) -> numpy.ndarray[numpy.int32]:
        ...
    def get_next_tokens_with_metadata(self) -> list[TokenMetadataInput]:
        ...
    def get_output(self, arg0: str) -> numpy.ndarray:
        ...
    def get_sequence(self, arg0: int) -> numpy.ndarray[numpy.int32]:
        ...
    def is_done(self) -> bool:
        ...
    def rewind_to(self, arg0: int) -> None:
        ...
    def set_active_adapter(self, arg0: OgaAdapters, arg1: str) -> None:
        ...
    def set_inputs(self, arg0: NamedTensors) -> None:
        ...
    def set_logits(self, arg0: numpy.ndarray[numpy.float32]) -> None:
        ...
    def set_model_input(self, arg0: str, arg1: numpy.ndarray) -> None:
        ...
    def set_runtime_option(self, arg0: str, arg1: str) -> None:
        ...
    def token_count(self) -> int:
        ...
class GeneratorParams:
    def __init__(self, arg0: OgaModel) -> None:
        ...
    def get_search_options(self) -> dict:
        ...
    def set_guidance(self, type: str, data: str, enable_ff_tokens: bool = False) -> None:
        ...
    def set_search_options(self, **kwargs) -> None:
        ...
class Images:
    @staticmethod
    def open(*args) -> Images:
        ...
    @staticmethod
    def open_bytes(*args) -> Images:
        ...
class Model:
    @typing.overload
    def __init__(self, arg0: Config) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    def create_multimodal_processor(self) -> OgaMultiModalProcessor:
        ...
    def create_streaming_processor(self) -> OgaStreamingProcessor:
        """
        Create a StreamingProcessor for mel spectrogram extraction from raw audio.
        """
    @property
    def device_type(self) -> str:
        """
        The device type the model is running on
        """
    @property
    def type(self) -> str:
        ...
class MultiModalProcessor:
    def __call__(self, prompt: typing.Any = None, **kwargs) -> NamedTensors:
        ...
    def create_stream(self) -> TokenizerStream:
        ...
    def decode(self, arg0: numpy.ndarray[numpy.int32]) -> str:
        ...
class NamedTensors:
    def __contains__(self, arg0: str) -> bool:
        ...
    def __delitem__(self, arg0: str) -> None:
        ...
    def __getitem__(self, arg0: str) -> OgaTensor:
        ...
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __setitem__(self, arg0: str, arg1: numpy.ndarray) -> None:
        ...
    @typing.overload
    def __setitem__(self, arg0: str, arg1: OgaTensor) -> None:
        ...
    def keys(self) -> list[str]:
        ...
class Request:
    def __init__(self, arg0: GeneratorParams) -> None:
        ...
    def add_tokens(self, arg0: numpy.ndarray[numpy.int32]) -> None:
        ...
    def get_opaque_data(self) -> typing.Any:
        ...
    def get_unseen_token(self) -> int:
        ...
    def has_unseen_tokens(self) -> bool:
        ...
    def is_done(self) -> bool:
        ...
    def set_opaque_data(self, arg0: typing.Any) -> None:
        ...
class StreamingProcessor:
    def __init__(self, arg0: Model) -> None:
        """
        Create a StreamingProcessor for mel spectrogram extraction.
        The model must be of type 'nemotron_speech'.
        """
    def flush(self) -> typing.Any:
        """
        Flush remaining buffered audio (pads with silence). Returns NamedTensors or None.
        """
    def get_option(self, key: str) -> str:
        """
        Get a processor option value by key.
        """
    def process(self, audio_chunk: numpy.ndarray[numpy.float32]) -> typing.Any:
        """
        Feed raw PCM audio. Returns a NamedTensors if a full chunk is ready, or None if more audio is needed.
        """
    def set_option(self, key: str, value: str) -> None:
        """
        Set a processor option. Keys: 'use_vad', 'vad_threshold', 'silence_duration_ms', 'prefix_padding_ms'.
        """
class Tensor:
    def __init__(self, arg0: numpy.ndarray) -> None:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
    def data(self) -> capsule:
        ...
    def shape(self) -> list[int]:
        ...
    def type(self) -> OgaElementType:
        ...
class TokenMetadataCoreConfig:
    def __init__(self) -> None:
        ...
    def overlay(self, json: str) -> None:
        ...
class TokenMetadataInput:
    @property
    def token_id(self) -> int:
        ...
    @property
    def token_acoustic_frame_interval(self) -> tuple[int, int] | None:
        ...
class Tokenizer:
    def __init__(self, arg0: OgaModel) -> None:
        ...
    def apply_chat_template(self, messages: str, *, template_str: str = None, tools: str = None, add_generation_prompt: bool = True) -> str:
        ...
    def create_stream(self) -> TokenizerStream:
        ...
    def decode(self, arg0: numpy.ndarray[numpy.int32]) -> str:
        ...
    def decode_batch(self, arg0: Tensor) -> list[str]:
        ...
    def encode(self, arg0: str) -> numpy.ndarray[numpy.int32]:
        ...
    def encode_batch(self, arg0: list[str]) -> Tensor:
        ...
    def to_token_id(self, arg0: str) -> int:
        ...
    def update_options(self, **kwargs) -> None:
        ...
    @property
    def bos_token_id(self) -> int:
        ...
    @property
    def eos_token_ids(self) -> numpy.ndarray[numpy.int32]:
        ...
    @property
    def pad_token_id(self) -> int:
        ...
class TokenizerStream:
    def create_metadata_core_state_using_tokenizer_config(self) -> None:
        ...
    def create_metadata_core_state(self, config: TokenMetadataCoreConfig) -> None:
        ...
    def decode(self, arg0: int) -> str:
        ...
    def decode_with_metadata(self, token: TokenMetadataInput) -> dict:
        ...
    def finalize_metadata(self) -> dict:
        ...
    def reset(self) -> None:
        ...
def get_current_gpu_device_id() -> int:
    ...
def is_cuda_available() -> bool:
    ...
def is_dml_available() -> bool:
    ...
def is_openvino_available() -> bool:
    ...
def is_qnn_available() -> bool:
    ...
def is_rocm_available() -> bool:
    ...
def is_webgpu_available() -> bool:
    ...
def register_execution_provider_library(arg0: str, arg1: str) -> None:
    ...
def set_current_gpu_device_id(arg0: int) -> None:
    ...
def set_log_callback(arg0: typing.Callable | None) -> None:
    ...
def set_log_options(**kwargs) -> None:
    ...
def unregister_execution_provider_library(arg0: str) -> None:
    ...
_cleanup: typing.Any  # value = <capsule object "cleanup" at 0x719d5330a310>
