# syntax=docker/dockerfile:1.7

FROM onnxruntimebuildcache.azurecr.io/internal/azureml/onnxruntime/build/cpu_aarch64_almalinux8_gcc14:20251017.1

ADD scripts /tmp/scripts
RUN --mount=type=secret,id=pip_index_url,required=true \
    export PIP_INDEX_URL="$(cat /run/secrets/pip_index_url)" && \
    cd /tmp/scripts && \
    /tmp/scripts/install_centos.sh && \
    /tmp/scripts/install_deps.sh && \
    rm -rf /tmp/scripts
RUN yum update -y && yum install -y pkgconfig openssl-devel
ENV PATH="/usr/.cargo/bin:$PATH"
ENV RUSTUP_HOME="/usr/.rustup"
ENV CARGO_HOME="/usr/.cargo"
ARG BUILD_UID=1001
ARG BUILD_USER=onnxruntimedev
RUN adduser --uid $BUILD_UID $BUILD_USER
WORKDIR /home/$BUILD_USER
USER $BUILD_USER
