parameters:
- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.18.0'

- name: build_config
  displayName: 'Build Configuration'
  type: string
  default: 'Release'
  values:
  - 'Debug'
  - 'RelWithDebInfo'
  - 'Release'
  - 'MinSizeRel'

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

trigger: none
extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      policheck:
        enabled: true
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: '$(Build.SourcesDirectory)\.pipelines\policheck_exclusions.xml'
      tsa:
        enabled: true
        configFile: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
    # Update the pool with your team's 1ES hosted pool.
    pool:
      name: 'onnxruntime-Win-CPU-2022'  # Name of your hosted pool
      os: windows  # OS of the image. This value cannot be a variable. Allowed values: windows, linux, macOS
    stages:
    - template: stages/android-packaging-stage.yml
      parameters:
        ort_version: ${{ parameters.ort_version }}
        build_config: ${{ parameters.build_config }}
