parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_gpu
  displayName: 'Whether Windows GPU package is built.'
  type: boolean
  default: true

- name: enable_win_arm
  displayName: 'Whether Windows ARM package is built.'
  type: boolean
  default: false

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: false

- name: enable_linux_gpu
  displayName: 'Whether Linux GPU package is built.'
  type: boolean
  default: false

- name: enable_linux_arm
  displayName: 'Whether Linux ARM package is built.'
  type: boolean
  default: false

- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.17.0'

- name: cuda_version
  displayName: 'CUDA version'
  type: string
  default: '11.8'
  values:
  - '11.8'
  - '12.2'

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
  ${{ if eq(parameter.enable_win_cpu, true) }}:
  - template: stages/capi-win-packaging-job.yml
    parameters:
      arch: 'x64'
      ort_version: ${{ parameters.ort_version }}
      build_gpu: false

  ${{ if eq(parameter.enable_win_gpu, true) }}:
  - template: stages/capi-win-packaging-job.yml
    parameters:
      arch: 'x64'
      ort_version: ${{ parameters.ort_version }}
      build_gpu: true
      cuda_version: ${{ parameters.cuda_version }}

  ${{ if eq(parameter.enable_win_arm, true) }}:
  - template: stages/capi-win-packaging-job.yml
    parameters:
      arch: 'arm64'
      ort_version: ${{ parameters.ort_version }}
      build_gpu: false

