parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.17.3'

- name: ort_dml_version
  displayName: 'OnnxRuntime DirectML version'
  type: string
  default: '1.18.0-dev-20240423-0527-c07b8d545d'

- name: cuda_version
  displayName: 'CUDA version'
  type: string
  values:
  - '11.8'
  - '12.2'
  default: '11.8'

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
- template: stages/nuget-packaging-stage.yml
  parameters:
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_cuda: ${{ parameters.enable_win_cuda }}
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
    enable_win_dml: ${{ parameters.enable_win_dml }}
    ort_version: ${{ parameters.ort_version }}
    ort_dml_version: ${{ parameters.ort_dml_version }}
    cuda_version: ${{ parameters.cuda_version }}
