parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_gpu
  displayName: 'Whether Windows GPU package is built.'
  type: boolean
  default: true

- name: enable_win_arm
  displayName: 'Whether Windows ARM package is built.'
  type: boolean
  default: false

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: false

- name: enable_linux_gpu
  displayName: 'Whether Linux GPU package is built.'
  type: boolean
  default: false

- name: enable_linux_arm
  displayName: 'Whether Linux ARM package is built.'
  type: boolean
  default: false

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
- template: stages/nuget-packaging-stage.yml
  parameters:
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_gpu: ${{ parameters.enable_linux_gpu }}
    enable_linux_arm: ${{ parameters.enable_linux_arm }}
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_gpu: ${{ parameters.enable_win_gpu }}
    enable_win_arm: ${{ parameters.enable_win_arm }}
    ort_version: '1.17.0'
