parameters:
- name: enable_post_packaging_validation
  displayName: Whether Post Packaging validation is run
  type: boolean
  default: false
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

- name: enable_macos_cpu
  displayName: 'Whether MacOS CPU package is built.'
  type: boolean
  default: true

- name: enable_android
  displayName: 'Whether Android AAR package is built.'
  type: boolean
  default: true

- name: enable_apple_framework
  displayName: 'Whether Apple framework for iOS & MacCatalyst is built.'
  type: boolean
  default: false

- name: enable_win_qnn
  displayName: 'Whether QNN nuget package should be built.'
  type: boolean
  default: false

- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.20.1'

- name: ort_cuda_version
  displayName: 'OnnxRuntime GPU version'
  type: string
  default: '1.20.1'

- name: ort_dml_version
  displayName: 'OnnxRuntime DML version'
  type: string
  default: '1.20.1'

- name: cuda_version
  displayName: 'CUDA version'
  type: string
  values:
  - '11.8'
  - '12.2'
  default: '11.8'

- name: build_config
  displayName: 'Build Configuration'
  type: string
  default: 'release'
  values:
  - 'release'
  - 'relwithdebinfo'
  - 'debug'

- name: 'nuget_version_type'
  displayName: 'Nuget version - stable uses VERSION_INFO, dev appends date, build_id and commit-ish, e.g. 1.21.0-dev-20250205-1932-8f6ddf3bd5'
  type: string
  default: dev
  values:
  - dev
  - stable

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
- template: stages/capi-packaging-stage.yml
  parameters:
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_cuda: ${{ parameters.enable_win_cuda }}
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
    enable_win_dml: ${{ parameters.enable_win_dml }}
    enable_win_arm64: ${{ parameters.enable_win_arm64 }}
    enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
    enable_android: ${{ parameters.enable_android }}
    enable_apple_framework: ${{ parameters.enable_apple_framework }}
    ort_version: ${{ parameters.ort_version }}
    ort_cuda_version: ${{ parameters.ort_cuda_version }}
    ort_dml_version: ${{ parameters.ort_dml_version }}
    cuda_version: ${{ parameters.cuda_version }}
    build_config: ${{ parameters.build_config }}

- template: stages/nuget-packaging-stage.yml
  parameters:
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_cuda: ${{ parameters.enable_win_cuda }}
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
    enable_win_dml: ${{ parameters.enable_win_dml }}
    enable_win_arm64: ${{ parameters.enable_win_arm64 }}
    enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
    enable_android: ${{ parameters.enable_android }}
    enable_apple_framework: ${{ parameters.enable_apple_framework }}
    ort_version: ${{ parameters.ort_version }}
    ort_cuda_version: ${{ parameters.ort_cuda_version }}
    ort_dml_version: ${{ parameters.ort_dml_version }}
    build_config: ${{ parameters.build_config }}
    enable_win_qnn: ${{ parameters.enable_win_qnn }}
    nuget_version_type: ${{ parameters.nuget_version_type }}

- ${{ if eq(parameters.enable_post_packaging_validation, true) }}:
  - template: stages/nuget-validation-stage.yml
    parameters:
      enable_win_cpu: ${{ parameters.enable_win_cpu }}
      enable_win_cuda: ${{ parameters.enable_win_cuda }}
      enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
      enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
      enable_win_dml: ${{ parameters.enable_win_dml }}
      enable_win_arm64: ${{ parameters.enable_win_arm64 }}
      enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
      ort_version: ${{ parameters.ort_version }}
      ort_cuda_version: ${{ parameters.ort_cuda_version }}
      ort_dml_version: ${{ parameters.ort_dml_version }}
      cuda_version: ${{ parameters.cuda_version }}
      SpecificArtifact: false