parameters:
- name: enable_post_packaging_validation
  displayName: Whether Post Packaging validation is run
  type: boolean
  default: false

- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64_cpu
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_rocm
  displayName: 'Whether Linux ROCm package is built.'
  type: boolean
  default: false

- name: enable_macos_cpu
  displayName: 'Whether MacOS CPU package is built.'
  type: boolean
  default: true

- name: cuda_versions
  displayName: 'CUDA versions'
  type: string
  default: '11.8,12.2'

- name: build_config
  displayName: 'Build Configuration'
  type: string
  default: 'release'
  values:
  - 'release'
  - 'relwithdebinfo'
  - 'debug'

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

trigger: none
extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    # Update the pool with your team's 1ES hosted pool.
    pool:
      name: 'onnxruntime-Win-CPU-2022'  # Name of your hosted pool
      os: windows  # OS of the image. This value cannot be a variable. Allowed values: windows, linux, macOS
    sdl:
      policheck:
        enabled: true
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: '$(Build.SourcesDirectory)\.pipelines\policheck_exclusions.xml'
      tsa:
        enabled: true
        configFile: '$(Build.SourcesDirectory)\.config\tsaoptions.json'
    stages:
    - template: stages/py-packaging-stage.yml
      parameters:
        enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
        enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
        enable_linux_rocm: ${{ parameters.enable_linux_rocm }}
        enable_win_cpu: ${{ parameters.enable_win_cpu }}
        enable_win_cuda: ${{ parameters.enable_win_cuda }}
        enable_win_dml: ${{ parameters.enable_win_dml }}
        enable_win_arm64_cpu: ${{ parameters.enable_win_arm64_cpu }}
        enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
        cuda_versions: ${{ parameters.cuda_versions }}
        build_config: ${{ parameters.build_config }}
    - ${{ if eq(parameters.enable_post_packaging_validation, true) }}:
      - template: stages/py-validation-stage.yml
        parameters:
          enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
          enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
          enable_win_cpu: ${{ parameters.enable_win_cpu }}
          enable_win_cuda: ${{ parameters.enable_win_cuda }}
          enable_win_dml: ${{ parameters.enable_win_dml }}
          enable_win_arm64_cpu: ${{ parameters.enable_win_arm64_cpu }}
          enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
          cuda_versions: ${{ parameters.cuda_versions }}
          SpecificArtifact: false