parameters:
- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.17.3'

- name: cuda_version
  displayName: 'CUDA version'
  type: string
  default: '11.8'
  values:
  - '11.8'
  - '12.2'

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
- template: stages/py-packaging-stage.yml
  parameters:
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_cuda: ${{ parameters.enable_win_cuda }}
    ort_version: ${{ parameters.ort_version }}
    cuda_version: ${{ parameters.cuda_version }}
    
