parameters:
- name: enable_post_packaging_validation
  displayName: Whether Post Packaging validation is run
  type: boolean
  default: false

- name: enable_win_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_win_cuda
  displayName: 'Whether Windows CUDA package is built.'
  type: boolean
  default: true

- name: enable_win_dml
  displayName: 'Whether Windows DirectML package is built.'
  type: boolean
  default: true

- name: enable_win_arm64_cpu
  displayName: 'Whether Windows ARM64 package is built.'
  type: boolean
  default: true

- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_cuda
  displayName: 'Whether Linux CUDA package is built.'
  type: boolean
  default: true

- name: enable_linux_rocm
  displayName: 'Whether Linux ROCm package is built.'
  type: boolean
  default: true

- name: enable_macos_cpu
  displayName: 'Whether MacOS CPU package is built.'
  type: boolean
  default: true

- name: ort_version
  displayName: 'OnnxRuntime version'
  type: string
  default: '1.19.0-dev-20240805-1630-ee2fe87e2d'

- name: ort_cuda_118_version
  displayName: 'OnnxRuntime GPU version for CUDA 11.8'
  type: string
  default: '1.18.0-dev-20240426-0614-b842effa29'

- name: ort_cuda_122_version
  displayName: 'OnnxRuntime GPU version for CUDA 12.2'
  type: string
  default: '1.19.0-dev-20240805-0337-88c811b638'

- name: ort_dml_version
  displayName: 'OnnxRuntime DML version'
  type: string
  default: '1.19.0-dev-20240805-1630-ee2fe87e2d'

- name: ort_rocm_version
  displayName: 'OnnxRuntime ROCm version'
  type: string
  default: '1.19.0-dev-20240805-0337-88c811b638'

- name: cuda_versions
  displayName: 'CUDA versions'
  type: string
  default: '11.8,12.2'

- name: build_config
  displayName: 'Build Configuration'
  type: string
  default: 'release'
  values:
  - 'release'
  - 'relwithdebinfo'
  - 'debug'

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

trigger: none
stages:
- template: stages/py-packaging-stage.yml
  parameters:
    enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
    enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
    enable_linux_rocm: ${{ parameters.enable_linux_rocm }}
    enable_win_cpu: ${{ parameters.enable_win_cpu }}
    enable_win_cuda: ${{ parameters.enable_win_cuda }}
    enable_win_dml: ${{ parameters.enable_win_dml }}
    enable_win_arm64_cpu: ${{ parameters.enable_win_arm64_cpu }}
    enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
    ort_version: ${{ parameters.ort_version }}
    ort_cuda_118_version: ${{ parameters.ort_cuda_118_version }}
    ort_cuda_122_version: ${{ parameters.ort_cuda_122_version }}
    ort_rocm_version: ${{ parameters.ort_rocm_version }}
    ort_dml_version: ${{ parameters.ort_dml_version }}
    cuda_versions: ${{ parameters.cuda_versions }}
    build_config: ${{ parameters.build_config }}
- ${{ if eq(parameters.enable_post_packaging_validation, true) }}:
  - template: stages/py-validation-stage.yml
    parameters:
      enable_linux_cpu: ${{ parameters.enable_linux_cpu }}
      enable_linux_cuda: ${{ parameters.enable_linux_cuda }}
      enable_win_cpu: ${{ parameters.enable_win_cpu }}
      enable_win_cuda: ${{ parameters.enable_win_cuda }}
      enable_win_dml: ${{ parameters.enable_win_dml }}
      enable_win_arm64_cpu: ${{ parameters.enable_win_arm64_cpu }}
      enable_macos_cpu: ${{ parameters.enable_macos_cpu }}
      ort_version: ${{ parameters.ort_version }}
      ort_cuda_118_version: ${{ parameters.ort_cuda_118_version }}
      ort_cuda_122_version: ${{ parameters.ort_cuda_122_version }}
      ort_rocm_version: ${{ parameters.ort_rocm_version }}
      ort_dml_version: ${{ parameters.ort_dml_version }}
      cuda_versions: ${{ parameters.cuda_versions }}
      SpecificArtifact: false