parameters:
- name: enable_linux_cpu
  displayName: 'Whether Linux CPU package is built.'
  type: boolean
  default: true

- name: enable_linux_gpu
  displayName: 'Whether Linux GPU package is built.'
  type: boolean
  default: true

- name: enable_windows_cpu
  displayName: 'Whether Windows CPU package is built.'
  type: boolean
  default: true

- name: enable_windows_gpu
  displayName: 'Whether Windows GPU package is built.'
  type: boolean
  default: true

- name: enable_mac_cpu
  displayName: 'Whether Mac CPU package is built.'
  type: boolean
  default: false

- name: enable_linux_arm
  displayName: 'Whether Linux ARM package is built.'
  type: boolean
  default: false
resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7
trigger: none
stages:
- stage: win-cpu-x64
  jobs:
  - job: win-cpu-x64
    workspace:
      clean: all
    pool:
      onnxruntime-Win-CPU-2022
- stage: win-gpu-x64
  jobs:
  - job: win-gpu-x64
    workspace:
      clean: all
    pool:
      onnxruntime-Win2022-GPU-A10
- stage: linux-cpu-x64
  jobs:
  - job: linux-cpu-x64
    workspace:
      clean: all
    pool:
      onnxruntime-Ubuntu2204-AMD-CPU
- stage: linux-gpu-x64
  jobs:
  - job: linux-gpu-x64
    workspace:
      clean: all
    pool:
      onnxruntime-Ubuntu2204-AMD-CPU