function(genai_set_target_compile_options target)
  if (MSVC)
    check_cxx_compiler_flag(-sdl HAS_SDL)
    check_cxx_compiler_flag(-Qspectre HAS_QSPECTRE)
    if (HAS_SDL)
      target_compile_options(${target} PRIVATE "/sdl")
    endif ()
    if (HAS_QSPECTRE)
      target_compile_options(${target} PRIVATE "/Qspectre")
    endif ()
    if (NOT CMAKE_SYSTEM_PROCESSOR MATCHES "arm" AND NOT USE_CUDA)
      target_compile_options(${target} PRIVATE "/CETCOMPAT")
    endif ()
  endif ()
endfunction()