function(genai_set_target_compile_options target)
  if (MSVC)
    target_compile_options(${target} PRIVATE "/sdl")
    if (NOT USE_CUDA)
      target_compile_options(${target} PRIVATE "/Qspectre")
    endif ()
    if (NOT CMAKE_SYSTEM_PROCESSOR MATCHES "arm" AND NOT USE_CUDA)
      target_link_options(${target} PRIVATE "/CETCOMPAT")
    endif ()
  endif ()
endfunction()