name: Clang Format Lint

on:
  push:
    branches:
      - main
      - rel-*
  pull_request:
    branches:
      - main
      - rel-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true

jobs:
  lint-cpp:
    runs-on:
      - self-hosted
      - "1ES.Pool=onnxruntime-genai-Ubuntu2204-AMD-CPU"
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'false'

      - name: Check format
        uses: microsoft/onnxruntime-github-actions/format-lint-check@176d1fa31b3e7293920e0ba6a105a156274560eb # v0.0.13
        with:
          llvm-version: '20.1.0'
          llvm-sha256-hash: '954ac51498519f6ed9540714fb04bc401f70039b296a8160dd1559be380788d7'
