name: "iOS ARM64 Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true
jobs:
  iphonesimulator-arm64-build:
    runs-on: macos-latest # arm64
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v5
        with:
          submodules: true

      - uses: microsoft/onnxruntime-github-actions/setup-build-tools@v0.0.8
        with:
          vcpkg-version: '2025.06.13'
          vcpkg-hash: '735923258c5187966698f98ce0f1393b8adc6f84d44fd8829dda7db52828639331764ecf41f50c8e881e497b569f463dbd02dcb027ee9d9ede0711102de256cc'
          cmake-version: '3.31.8'
          cmake-hash: '99cc9c63ae49f21253efb5921de2ba84ce136018abf08632c92c060ba91d552e0f6acc214e9ba8123dee0cf6d1cf089ca389e321879fd9d719a60d975bcffcc8'
          add-cmake-to-path: 'true'
          disable-terrapin: 'true'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12.x'

      - name: Install the python wheel and dependencies
        run: |
          python3 -m venv genai-macos-venv
          source genai-macos-venv/bin/activate
          python3 -m pip install requests

      - name: Run iOS Build
        run: |-
          set -e -x
          source genai-macos-venv/bin/activate
          python3 build.py --ios \
              --parallel \
              --apple_sysroot iphonesimulator \
              --osx_arch arm64 \
              --apple_deploy_target 15.4 \
              --cmake_generator 'Xcode' \
              --build_dir build_iphonesimulator \
              --skip_wheel
