name: "Windows WinML x64 Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true

env:
  AZCOPY_AUTO_LOGIN_TYPE: MSI
  AZCOPY_MSI_CLIENT_ID: 63b63039-6328-442f-954b-5a64d124e5b4
  cuda_dir: "${{ github.workspace }}\\cuda_sdk"
  cuda_version: "12.2"
  CUDA_PATH: ${{ github.workspace }}\\cuda_sdk\\v12.2
  binaryDir: 'build/cuda/win-x64'
  ORT_NIGHTLY_REST_API: "https://feeds.dev.azure.com/aiinfra/PublicPackages/_apis/packaging/Feeds/ORT-Nightly/packages?packageNameQuery=Microsoft.ML.OnnxRuntime.Gpu.Windows&api-version=6.0-preview.1"
  ORT_PACKAGE_NAME: "Microsoft.ML.OnnxRuntime.Gpu.Windows"

jobs:
  windows-cuda-x64-build:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-genai-Win2022-GPU-A10"]
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Setup VCPKG
        uses: microsoft/onnxruntime-github-actions/setup-build-tools@v0.0.8
        with:
          vcpkg-version: '2025.03.19'
          vcpkg-hash: '17e96169cd3f266c4716fcdc1bb728e6a64f103941ece463a2834d50694eba4fb48f30135503fd466402afa139abc847ef630733c442595d1c34979f261b0114'
          cmake-version: '3.31.6'
          cmake-hash: '0f1584e8666cf4a65ec514bd02afe281caabf1d45d2c963f3151c41484f457386aa03273ab25776a670be02725354ce0b46f3a5121857416da37366342a833a0'
          add-cmake-to-path: 'true'
          disable-terrapin: 'false'

      - name: Download cuda
        run: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ env.cuda_version }}" ${{ env.cuda_dir}}

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install Rust Toolchain
        run: |
          $exePath = "$env:TEMP\rustup-init.exe"
          (New-Object Net.WebClient).DownloadFile('https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe', $exePath)
          & $exePath -y --default-toolchain=1.86.0
          Add-Content $env:GITHUB_PATH "$env:USERPROFILE\.cargo\bin"

      - name: Configure CMake
        run: |
          cmake --preset windows_x64_winml_relwithdebinfo -T cuda=${{ env.cuda_dir }}\\v${{ env.cuda_version }} -DWINML_SDK_VERSION='1.8.2091'

      - name: Build with CMake
        run: |
          cmake --build --preset windows_x64_winml_relwithdebinfo --parallel
          cmake --build --preset windows_x64_winml_relwithdebinfo --target PyPackageBuild

